import Link from "next/link";
import { redirect } from "next/navigation";
import { Prisma } from "@prisma/client";
import { Activity,ArrowLeft,BadgeCheck,BarChart3,BellRing,BriefcaseBusiness,Building2,CalendarClock,CheckCircle2,CircleAlert,Eye,FileText,Inbox,MailWarning,MousePointerClick,NotebookPen,Palette,Rocket,ShoppingBag,Sparkles,Store,Target,UserRound,Zap } from "lucide-react";
import { getCurrentUser } from "../lib/auth";
import { getActiveBusinessWithPlanForUser } from "../lib/active-business";
import { db } from "../lib/db";
import { getPublicBusinessUrlFromRequest } from "../lib/public-url";

const actionableOrderStatuses=["pending","confirmed","processing"] as const;
const actionableBookingStatuses=["pending","confirmed"] as const;
const interactionEvents=["whatsapp_click","phone_click","share_click","website_click","map_click","company_profile_click","social_click"] as const;
type DashboardClock={since7d:Date;today:string};
type ReminderSummary={id:string;title:string;scheduledAt:Date;timezone:string;workHealth:string;priority:string;responsiblePerson:string|null;businessDueAt:Date|null;nextAction:string|null;progressPercent:number};
type NoteSummary={id:string;title:string;summary:string|null;nextAction:string|null;workHealth:string;priority:string;responsiblePerson:string|null;businessDueAt:Date|null;updatedAt:Date};
type WorkCounts={reminderAttention:bigint;noteAttention:bigint;activeReminders:bigint;activeNotes:bigint};
function metricNumber(v:number|bigint){return new Intl.NumberFormat("ar-SA").format(v)}
function dateText(value:Date,timezone="Asia/Riyadh"){try{return new Intl.DateTimeFormat("ar-SA",{dateStyle:"medium",timeStyle:"short",timeZone:timezone}).format(value)}catch{return new Intl.DateTimeFormat("ar-SA",{dateStyle:"medium",timeStyle:"short",timeZone:"Asia/Riyadh"}).format(value)}}

export default async function DashboardHomePage(){
  const user=await getCurrentUser();if(!user)redirect("/login");
  const business=await getActiveBusinessWithPlanForUser(user.id);
  if(!business)return <section className="mx-auto max-w-2xl rounded-[30px] border border-slate-200 bg-white p-8"><Rocket className="h-6 w-6 text-[#008f87]"/><p className="mt-5 text-[9px] font-black tracking-[.18em] text-[#008f87]" dir="ltr">INFRO WORKSPACE</p><h1 className="mt-2 text-2xl font-black">ابدأ هويتك الرقمية</h1><p className="mt-2 text-sm leading-7 text-slate-500">أنشئ الأساس مرة واحدة، ثم اجعل INFRO مساحة تشغيل حضورك الرقمي والتسويقي.</p><Link href="/onboarding" className="mt-6 inline-flex h-11 items-center rounded-xl bg-[#07181b] px-5 text-sm font-black text-white">إنشاء الصفحة</Link></section>;

  const[clock]=await db.$queryRaw<DashboardClock[]>`SELECT CURRENT_TIMESTAMP - INTERVAL '7 days' AS "since7d",to_char((CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Riyadh')::date,'YYYY-MM-DD') AS "today"`;if(!clock)throw new Error("dashboard clock unavailable");
  const{since7d,today}=clock;
  const[actionableOrders,actionableBookings,pendingOrders,pendingBookings,services,branches,contacts,views7d,interactions7d,orders7d,bookings7d,nextBooking,nextReminder,recentNotes,workCounts]=await Promise.all([
    db.order.count({where:{businessId:business.id,status:{in:[...actionableOrderStatuses]}}}),db.booking.count({where:{businessId:business.id,status:{in:[...actionableBookingStatuses]}}}),db.order.count({where:{businessId:business.id,status:"pending"}}),db.booking.count({where:{businessId:business.id,status:"pending"}}),db.service.count({where:{businessId:business.id,isActive:true,deletedAt:null}}),db.branch.count({where:{businessId:business.id,isActive:true}}),db.contactPerson.count({where:{businessId:business.id,isActive:true}}),db.analyticsEvent.count({where:{businessId:business.id,eventType:"page_view",createdAt:{gte:since7d}}}),db.analyticsEvent.count({where:{businessId:business.id,eventType:{in:[...interactionEvents]},createdAt:{gte:since7d}}}),db.order.count({where:{businessId:business.id,createdAt:{gte:since7d}}}),db.booking.count({where:{businessId:business.id,createdAt:{gte:since7d}}}),db.booking.findFirst({where:{businessId:business.id,status:{in:[...actionableBookingStatuses]},bookingDate:{gte:today}},orderBy:[{bookingDate:"asc"},{bookingTime:"asc"}],select:{bookingDate:true,bookingTime:true,customer:{select:{name:true}},service:{select:{name:true}}}}),
    db.$queryRaw<ReminderSummary[]>(Prisma.sql`SELECT "id","title","scheduledAt","timezone","workHealth","priority","responsiblePerson","businessDueAt","nextAction","progressPercent" FROM "SmartReminder" WHERE "businessId"=${business.id} AND "status"='scheduled' ORDER BY "scheduledAt" ASC LIMIT 1`).then(r=>r[0]??null).catch(()=>null),
    db.$queryRaw<NoteSummary[]>(Prisma.sql`SELECT "id","title","summary","nextAction","workHealth","priority","responsiblePerson","businessDueAt","updatedAt" FROM "BusinessNote" WHERE "businessId"=${business.id} AND "status"<>'archived' ORDER BY "isPinned" DESC,"updatedAt" DESC LIMIT 3`).catch(()=>[]),
    db.$queryRaw<WorkCounts[]>(Prisma.sql`SELECT (SELECT COUNT(*) FROM "SmartReminder" WHERE "businessId"=${business.id} AND "status" IN ('scheduled','paused') AND ("workHealth" IN ('blocked','at_risk') OR ("businessDueAt" IS NOT NULL AND "businessDueAt" < CURRENT_TIMESTAMP AND "progressPercent" < 100)))::bigint AS "reminderAttention",(SELECT COUNT(*) FROM "BusinessNote" WHERE "businessId"=${business.id} AND "status"<>'archived' AND ("workHealth" IN ('blocked','at_risk') OR ("businessDueAt" IS NOT NULL AND "businessDueAt" < CURRENT_TIMESTAMP)))::bigint AS "noteAttention",(SELECT COUNT(*) FROM "SmartReminder" WHERE "businessId"=${business.id} AND "status" IN ('scheduled','paused'))::bigint AS "activeReminders",(SELECT COUNT(*) FROM "BusinessNote" WHERE "businessId"=${business.id} AND "status"<>'archived')::bigint AS "activeNotes"`).then(r=>r[0]??{reminderAttention:0n,noteAttention:0n,activeReminders:0n,activeNotes:0n}).catch(()=>({reminderAttention:0n,noteAttention:0n,activeReminders:0n,activeNotes:0n})),
  ]);
  const attentionCount=Number(workCounts.reminderAttention)+Number(workCounts.noteAttention),actionableTransactions=actionableOrders+actionableBookings,newTransactions=pendingOrders+pendingBookings;
  const publicUrl=await getPublicBusinessUrlFromRequest(business.slug),effectivelyPublished=Boolean(business.isPublished&&user.emailVerifiedAt),identityReady=Boolean(business.name&&business.shortDescription&&(business.phone||business.whatsapp));
  const tasks=[{label:"بيانات الصفحة",ready:identityReady,href:"/dashboard/my-page",icon:UserRound},{label:"الخدمات",ready:services>0,href:"/dashboard/services",icon:Store},{label:"الفروع والفريق",ready:branches>0,href:"/dashboard/directory",icon:Building2},{label:"الشعار والمظهر",ready:Boolean(business.logoUrl),href:"/dashboard/branding",icon:Palette},{label:"الملف التعريفي PDF",ready:Boolean(business.companyProfileUrl),href:"/dashboard/digital-identity#company-profile",icon:FileText}],completed=tasks.filter(t=>t.ready).length,progress=Math.round(completed/tasks.length*100),nextTask=tasks.find(t=>!t.ready);
  const primaryAction=!user.emailVerifiedAt?{title:"أكد بريد الحساب",description:"التأكيد مطلوب قبل النشر العام.",href:"/dashboard/settings",icon:MailWarning}:attentionCount?{title:`${attentionCount} عمل يحتاج انتباهك`,description:"أعمال متعثرة، معرّضة للخطر أو تجاوزت موعدها النهائي.",href:"/dashboard/reminders",icon:CircleAlert}:actionableTransactions?{title:`${actionableTransactions} عنصر يحتاج متابعة`,description:`${newTransactions?`${newTransactions} جديد · `:""}${actionableOrders} طلب · ${actionableBookings} حجز`,href:"/dashboard/inbox",icon:Inbox}:nextTask?{title:`أكمل ${nextTask.label}`,description:"خطوة متبقية لاستكمال حضور منشأتك.",href:nextTask.href,icon:nextTask.icon}:{title:"مساحة العمل جاهزة",description:"راجع الأعمال القادمة أو أضف مذكرة تشغيلية جديدة.",href:"/dashboard/notes",icon:CheckCircle2};const PrimaryIcon=primaryAction.icon;
  const pulse=[{label:"الزيارات",value:views7d,icon:Eye,href:"/dashboard/analytics"},{label:"التفاعل",value:interactions7d,icon:MousePointerClick,href:"/dashboard/analytics"},{label:"الطلبات",value:orders7d,icon:ShoppingBag,href:"/dashboard/inbox"},{label:"الحجوزات",value:bookings7d,icon:CalendarClock,href:"/dashboard/inbox"}];

  return <div className="space-y-4 pb-5">
    <section className="grid overflow-hidden rounded-[28px] border border-[#163538] bg-[#07181b] xl:grid-cols-[1fr_360px]"><div className="relative p-5 text-white sm:p-7"><div className="flex flex-wrap items-center gap-2"><span className="inline-flex items-center gap-1.5 rounded-full border border-white/10 bg-white/[.05] px-2.5 py-1 text-[8px] font-black tracking-[.12em] text-[#8ff5e6]" dir="ltr"><Sparkles className="h-3 w-3"/>INFRO COMMAND SPACE</span><span className={`rounded-full px-2.5 py-1 text-[8px] font-black ${effectivelyPublished?"bg-emerald-400/15 text-emerald-200":"bg-amber-300/15 text-amber-200"}`}>{effectivelyPublished?"LIVE":"DRAFT"}</span>{business.isVerified?<span className="inline-flex items-center gap-1 text-[8px] font-black text-sky-200"><BadgeCheck className="h-3 w-3"/>VERIFIED</span>:null}</div><h1 className="mt-4 text-2xl font-black sm:text-[32px]">{business.name}</h1><p className="mt-2 max-w-xl text-xs leading-6 text-slate-400">هويتك، تسويقك، مذكراتك وأعمالك القادمة في مساحة تشغيل واحدة.</p><div className="mt-6 flex flex-wrap gap-2"><Link href="/dashboard/notes" className="inline-flex h-10 items-center gap-2 rounded-xl bg-[#35e4cb] px-4 text-[11px] font-black text-[#07181b]"><NotebookPen className="h-4 w-4"/>إضافة مذكرة أعمال</Link><Link href="/dashboard/reminders" className="inline-flex h-10 items-center gap-2 rounded-xl border border-white/10 px-4 text-[11px] font-black"><BellRing className="h-4 w-4"/>إضافة تذكير</Link><a href={effectivelyPublished?publicUrl:"/preview"} target="_blank" rel="noreferrer" className="inline-flex h-10 items-center gap-2 rounded-xl border border-white/10 px-4 text-[11px] font-black"><Eye className="h-4 w-4"/>{effectivelyPublished?"فتح الصفحة":"معاينة"}</a></div></div><Link href={primaryAction.href} className="group flex min-h-[190px] flex-col justify-between border-t border-white/[.08] bg-white/[.035] p-5 text-white xl:border-r xl:border-t-0"><div className="flex items-center justify-between"><span className="text-[8px] font-black tracking-[.15em] text-[#66e7d5]" dir="ltr">FOCUS NOW</span><PrimaryIcon className="h-5 w-5 text-[#66e7d5]"/></div><div><h2 className="text-lg font-black">{primaryAction.title}</h2><p className="mt-2 text-[11px] leading-6 text-slate-400">{primaryAction.description}</p></div><span className="flex items-center gap-2 text-[10px] font-black text-[#66e7d5]">ابدأ الآن <ArrowLeft className="h-3.5 w-3.5"/></span></Link></section>

    <section aria-labelledby="work-center" className="overflow-hidden rounded-[26px] border border-slate-200 bg-white"><div className="flex flex-col gap-3 border-b border-slate-100 p-5 sm:flex-row sm:items-end sm:justify-between"><div><span className="text-[8px] font-black tracking-[.16em] text-[#008f87]" dir="ltr">BUSINESS EXECUTION CENTER</span><h2 id="work-center" className="mt-1 text-lg font-black text-slate-950">مركز العمل اليومي</h2><p className="mt-1 text-[10px] leading-5 text-slate-500">ما يجب متابعته الآن، مستخرج من بيانات منشأتك الفعلية دون مؤشرات تقديرية.</p></div><div className="flex gap-2"><Link href="/dashboard/reminders" className="rounded-xl bg-[#07181b] px-3 py-2 text-[9px] font-black text-white">كل التذكيرات</Link><Link href="/dashboard/notes" className="rounded-xl border border-slate-200 px-3 py-2 text-[9px] font-black text-slate-700">ذاكرة الأعمال</Link></div></div><div className="grid gap-0 lg:grid-cols-[.85fr_1.15fr]">
      <div className="border-b border-slate-100 p-5 lg:border-b-0 lg:border-l"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><BellRing className="h-4 w-4 text-[#008f87]"/><b className="text-xs text-slate-900">التذكير القادم</b></div><span className="text-[9px] font-bold text-slate-400">{metricNumber(workCounts.activeReminders)} نشط</span></div>{nextReminder?<Link href="/dashboard/reminders" className="mt-4 block rounded-2xl border border-[#cceee9] bg-[#f5fffd] p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><b className="block truncate text-sm text-slate-900">{nextReminder.title}</b><span className="mt-1 block text-[10px] text-[#008f87]">{dateText(nextReminder.scheduledAt,nextReminder.timezone)}</span></div>{nextReminder.workHealth!=="on_track"?<span className="rounded-full bg-amber-100 px-2 py-1 text-[8px] font-black text-amber-800">يحتاج انتباه</span>:null}</div>{nextReminder.nextAction?<p className="mt-3 line-clamp-2 text-[10px] leading-5 text-slate-500">التالي: {nextReminder.nextAction}</p>:null}{nextReminder.responsiblePerson?<p className="mt-2 text-[9px] font-bold text-slate-400">المسؤول: {nextReminder.responsiblePerson}</p>:null}<div className="mt-3 h-1.5 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-[#00bfae]" style={{width:`${Math.max(0,Math.min(100,nextReminder.progressPercent))}%`}}/></div></Link>:<div className="mt-4 rounded-2xl border border-dashed border-slate-200 p-4"><b className="text-sm text-slate-700">لا يوجد تذكير قادم</b><p className="mt-1 text-[10px] leading-5 text-slate-400">أضف متابعة أو موعدًا لتظهر الأولوية القادمة هنا.</p></div>}</div>
      <div className="p-5"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><NotebookPen className="h-4 w-4 text-[#008f87]"/><b className="text-xs text-slate-900">آخر مذكرات الأعمال</b></div><span className="text-[9px] font-bold text-slate-400">{metricNumber(workCounts.activeNotes)} محفوظة</span></div><div className="mt-4 grid gap-2">{recentNotes.length?recentNotes.map(note=><Link key={note.id} href="/dashboard/notes" className="flex items-start gap-3 rounded-2xl border border-slate-100 bg-[#fbfcfc] p-3 hover:border-[#bdebe5]"><span className={`mt-0.5 grid h-8 w-8 shrink-0 place-items-center rounded-xl ${note.workHealth==="blocked"?"bg-rose-50 text-rose-600":note.workHealth==="at_risk"?"bg-amber-50 text-amber-600":"bg-[#e9fbf8] text-[#008f87]"}`}><BriefcaseBusiness className="h-3.5 w-3.5"/></span><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2"><b className="truncate text-[11px] text-slate-800">{note.title}</b><span className="shrink-0 text-[8px] text-slate-400">{new Intl.DateTimeFormat("ar-SA",{dateStyle:"short",timeZone:"Asia/Riyadh"}).format(note.updatedAt)}</span></div>{note.nextAction||note.summary?<p className="mt-1 line-clamp-1 text-[9px] text-slate-400">{note.nextAction?`التالي: ${note.nextAction}`:note.summary}</p>:null}{note.responsiblePerson?<span className="mt-1 block text-[8px] font-bold text-[#008f87]">{note.responsiblePerson}</span>:null}</div></Link>):<div className="rounded-2xl border border-dashed border-slate-200 p-4 text-[10px] text-slate-400">لا توجد مذكرات بعد. ابدأ بتسجيل قرار أو متابعة مهمة.</div>}</div></div>
    </div><div className="grid grid-cols-2 border-t border-slate-100 sm:grid-cols-4"><WorkStat label="تذكيرات نشطة" value={workCounts.activeReminders}/><WorkStat label="مذكرات نشطة" value={workCounts.activeNotes}/><WorkStat label="تذكيرات تحتاج انتباه" value={workCounts.reminderAttention} attention/><WorkStat label="مذكرات تحتاج انتباه" value={workCounts.noteAttention} attention/></div></section>

    <section aria-labelledby="infro-pillars-title" className="rounded-[26px] border border-slate-200 bg-white p-5"><div><span className="text-[8px] font-black tracking-[.16em] text-[#008f87]" dir="ltr">YOUR DIGITAL & MARKETING IDENTITY</span><h2 id="infro-pillars-title" className="mt-1 text-base font-black text-slate-950">ركائز INFRO</h2></div><div className="mt-4 grid gap-3 md:grid-cols-2"><Pillar href="/dashboard/digital-identity" label="DIGITAL IDENTITY CORE" title="الهوية الرقمية" text="صفحتك، شعارك، ملف الشركة وSEO." icon={<BadgeCheck className="h-5 w-5"/>}/><Pillar href="/dashboard/whatsapp" label="MARKETING CORE" title="تسويق واتساب" text="الحملات والقوالب والمحادثات عبر Meta الرسمي." icon={<WhatsAppGlyph className="h-5 w-5"/>} dark/></div></section>

    <section className="overflow-hidden rounded-[24px] border border-slate-200 bg-white"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div className="flex items-center gap-2"><Activity className="h-4 w-4 text-[#008f87]"/><div><h2 className="text-xs font-black">آخر 7 أيام</h2><p className="text-[9px] text-slate-400">أرقام حقيقية من نشاط صفحتك</p></div></div><Link href="/dashboard/analytics" className="text-[9px] font-black text-[#008f87]">التفاصيل ←</Link></div><div className="grid grid-cols-2 sm:grid-cols-4">{pulse.map(item=>{const Icon=item.icon;return <Link key={item.label} href={item.href} className="flex items-center gap-3 border-slate-100 p-4 sm:border-l"><span className="grid h-9 w-9 place-items-center rounded-xl bg-slate-50 text-[#009d93]"><Icon className="h-3.5 w-3.5"/></span><div><b className="block text-lg text-slate-950">{metricNumber(item.value)}</b><span className="text-[9px] text-slate-400">{item.label}</span></div></Link>})}</div></section>

    <div className="grid gap-4 xl:grid-cols-[1.3fr_.7fr]"><section className="rounded-[24px] border border-slate-200 bg-white p-5"><div className="flex items-center justify-between"><div><span className="text-[8px] font-black tracking-[.15em] text-[#008f87]" dir="ltr">IDENTITY JOURNEY</span><h2 className="mt-1 text-base font-black">من الأساس إلى حضور مكتمل</h2></div><b className="text-xl text-[#008f87]">{progress}%</b></div><div className="mt-4 h-1 overflow-hidden rounded-full bg-slate-100"><div className="h-full bg-[#00bfae]" style={{width:`${progress}%`}}/></div><div className="mt-5 grid gap-2 sm:grid-cols-5">{tasks.map((task,index)=>{const Icon=task.icon;return <Link key={task.label} href={task.href} className={`rounded-2xl border p-3 ${task.ready?"border-emerald-100 bg-emerald-50/45":"border-slate-100 bg-[#fbfcfc]"}`}><div className="flex justify-between"><span className="grid h-8 w-8 place-items-center rounded-lg bg-white text-[#008f87]">{task.ready?<CheckCircle2 className="h-3.5 w-3.5"/>:<Icon className="h-3.5 w-3.5"/>}</span><span className="text-[8px] text-slate-300">0{index+1}</span></div><b className="mt-3 block text-[10px]">{task.label}</b></Link>})}</div></section><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-1">{nextBooking?<Link href="/dashboard/inbox" className="rounded-[24px] border border-slate-200 bg-white p-5"><span className="text-[8px] font-black text-[#008f87]" dir="ltr">NEXT APPOINTMENT</span><b className="mt-4 block text-sm">{nextBooking.customer.name}</b><span className="mt-1 block text-[10px] text-slate-400">{nextBooking.bookingDate} · {nextBooking.bookingTime}{nextBooking.service?.name?` · ${nextBooking.service.name}`:""}</span></Link>:<div className="rounded-[24px] border border-slate-200 bg-white p-5"><span className="text-[8px] font-black text-[#008f87]" dir="ltr">NEXT APPOINTMENT</span><b className="mt-4 block text-sm">لا يوجد موعد قادم</b></div>}<div className="rounded-[24px] bg-[#0b2529] p-5 text-white"><span className="text-[8px] font-black text-[#6eead8]" dir="ltr">CURRENT PLAN</span><h2 className="mt-4 text-lg font-black">{business.plan?.name||"Free"}</h2><Link href="/dashboard/settings" className="mt-4 inline-flex text-[9px] font-black text-[#6eead8]">الحساب والباقات</Link></div></section></div>

    <section className="rounded-[24px] border border-slate-200 bg-white p-5"><div className="flex items-center justify-between"><div><span className="text-[8px] font-black tracking-[.14em] text-slate-400" dir="ltr">WORKSPACE SHORTCUTS</span><h2 className="mt-1 text-sm font-black">أدوات عندما تحتاجها</h2></div><Target className="h-4 w-4 text-[#009d93]"/></div><div className="mt-4 grid gap-2 sm:grid-cols-2 xl:grid-cols-4"><Shortcut href="/dashboard/notes" icon={<NotebookPen className="h-4 w-4"/>} title="مذكرات الأعمال"/><Shortcut href="/dashboard/reminders" icon={<BellRing className="h-4 w-4"/>} title="التذكيرات الذكية"/><Shortcut href="/dashboard/digital-identity" icon={<BadgeCheck className="h-4 w-4"/>} title="الهوية الرقمية"/><Shortcut href="/dashboard/analytics" icon={<BarChart3 className="h-4 w-4"/>} title="الأداء"/></div></section>
  </div>;
}
function WorkStat({label,value,attention=false}:{label:string;value:bigint;attention?:boolean}){return <div className="border-l border-slate-100 p-4"><b className={`block text-lg ${attention&&Number(value)>0?"text-amber-700":"text-slate-900"}`}>{metricNumber(value)}</b><span className="mt-1 block text-[8px] font-bold text-slate-400">{label}</span></div>}
function Pillar({href,label,title,text,icon,dark=false}:{href:string;label:string;title:string;text:string;icon:React.ReactNode;dark?:boolean}){return <Link href={href} className={`rounded-[22px] border p-5 ${dark?"border-[#17484a] bg-[#092426] text-white":"border-slate-200 bg-[#fbfdfd] text-slate-950"}`}><span className={`grid h-11 w-11 place-items-center rounded-2xl ${dark?"bg-[#35e4cb] text-[#07181b]":"bg-[#07181b] text-[#66e7d5]"}`}>{icon}</span><span className={`mt-5 block text-[8px] font-black tracking-[.14em] ${dark?"text-[#66e7d5]":"text-[#008f87]"}`} dir="ltr">{label}</span><h3 className="mt-1 text-lg font-black">{title}</h3><p className={`mt-2 text-[10px] ${dark?"text-slate-300":"text-slate-500"}`}>{text}</p></Link>}
function Shortcut({href,icon,title}:{href:string;icon:React.ReactNode;title:string}){return <Link href={href} className="flex items-center gap-3 rounded-2xl border border-slate-100 bg-[#fbfcfc] p-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-white text-[#008f87]">{icon}</span><b className="text-[10px] text-slate-800">{title}</b><ArrowLeft className="mr-auto h-3 w-3 text-slate-300"/></Link>}
function WhatsAppGlyph({className}:{className?:string}){return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.9" className={className} aria-hidden="true"><path d="M20 11.5a8 8 0 0 1-11.84 7.02L4 19.6l1.12-4.02A8 8 0 1 1 20 11.5Z"/><path d="M9.15 8.15c.18-.36.37-.37.56-.37h.47c.16 0 .31.05.4.28l.72 1.73c.08.2.04.38-.08.54l-.56.72c-.11.14-.09.32 0 .47.48.78 1.1 1.42 1.87 1.91.17.1.35.12.49 0l.77-.63c.16-.13.34-.16.53-.08l1.68.79c.2.09.29.25.27.45"/></svg>}
