import Link from "next/link";
import { redirect } from "next/navigation";
import { AlertCircle, Building2, CheckCircle2, Eye, MapPin, Pencil, Plus, Save, UsersRound } from "lucide-react";
import { getCurrentUser } from "../../lib/auth";
import { getActiveBusinessForUser } from "../../lib/active-business";
import { db } from "../../lib/db";
import { formatPlanLimit, getPlanEntitlements, limitReached } from "../../lib/plan-entitlements";
import { createBranchAction, createContactPersonAction, deleteBranchAction, deleteContactPersonAction, updateBranchAction, updateContactPersonAction } from "../../actions/directory";
import { ConfirmSubmitButton } from "../../../components/dashboard/confirm-submit-button";

const STATUS_MESSAGES: Record<string, { tone: "success" | "error"; text: string }> = {
  "branch-created": { tone: "success", text: "تمت إضافة الفرع." }, "branch-updated": { tone: "success", text: "تم تحديث الفرع." }, "branch-deleted": { tone: "success", text: "تم حذف الفرع." },
  "contact-created": { tone: "success", text: "تمت إضافة عضو الفريق." }, "contact-updated": { tone: "success", text: "تم تحديث عضو الفريق." }, "contact-deleted": { tone: "success", text: "تم حذف عضو الفريق." },
  "error-required": { tone: "error", text: "أكمل الحقول المطلوبة." }, "error-too-long": { tone: "error", text: "أحد الحقول أطول من الحد المسموح. اختصر النص ثم حاول مرة أخرى." }, "error-map": { tone: "error", text: "استخدم رابط Google Maps صالحًا للفرع." },
  "error-email": { tone: "error", text: "أدخل بريدًا إلكترونيًا صالحًا لعضو الفريق." }, "error-plan-branch-limit": { tone: "error", text: "وصلت إلى حد الفروع في باقتك الحالية." }, "error-plan-contact-limit": { tone: "error", text: "وصلت إلى حد أعضاء الفريق في باقتك الحالية." },
  "error-not-found": { tone: "error", text: "تعذر العثور على السجل المطلوب." }, "error-relation": { tone: "error", text: "تعذر ربط البيانات بالفرع المحدد." }, "error-business": { tone: "error", text: "تعذر العثور على نشاطك." },
};

const field = "h-11 min-w-0 rounded-xl border border-[#dce8e7] bg-[#fbfdfd] px-3 text-sm text-[#173437] outline-none transition focus:border-[#00bfae] focus:bg-white";
const save = "inline-flex h-11 items-center justify-center gap-1.5 rounded-xl bg-[#07181b] px-4 text-xs font-black text-white transition hover:bg-[#103236] disabled:bg-slate-300";

export default async function DirectoryPage({ searchParams }: { searchParams?: Promise<Record<string, string | string[] | undefined>> }) {
  const user = await getCurrentUser(); if (!user) redirect("/login");
  const params = await searchParams; const statusKey = Array.isArray(params?.status) ? params.status[0] : params?.status; const status = statusKey ? STATUS_MESSAGES[statusKey] : null;
  const activeBusiness = await getActiveBusinessForUser(user.id); if (!activeBusiness) redirect("/onboarding");
  const business = await db.business.findFirst({ where: { id: activeBusiness.id, ownerId: user.id, deletedAt: null }, include: { plan: true, branches: { orderBy: [{ isMain: "desc" }, { sortOrder: "asc" }, { createdAt: "asc" }] }, contactPersons: { include: { branch: true }, orderBy: [{ isPrimary: "desc" }, { sortOrder: "asc" }, { createdAt: "asc" }] } } });
  if (!business) redirect("/onboarding");
  const entitlements = getPlanEntitlements(business.plan?.code); const branchLimitReached = limitReached(business.branches.length, entitlements.branchLimit); const contactLimitReached = limitReached(business.contactPersons.length, entitlements.contactLimit);
  const visibleBranches = business.branches.filter((branch) => branch.isActive).length; const visibleContacts = business.contactPersons.filter((contact) => contact.isActive).length;

  return <div className="space-y-5 pb-6">
    {status ? <div className={`flex items-start gap-2 rounded-2xl border px-4 py-3 text-sm font-bold ${status.tone === "success" ? "border-emerald-200 bg-emerald-50 text-emerald-800" : "border-rose-200 bg-rose-50 text-rose-800"}`}>{status.tone === "success" ? <CheckCircle2 className="mt-0.5 h-4 w-4" /> : <AlertCircle className="mt-0.5 h-4 w-4" />}{status.text}</div> : null}
    <section className="relative overflow-hidden rounded-[30px] bg-[#07181b] p-5 text-white sm:p-7"><div className="absolute -left-20 -top-24 h-64 w-64 rounded-full bg-[#35e4cb]/10 blur-3xl" /><div className="relative grid gap-6 lg:grid-cols-[1fr_auto] lg:items-end"><div><div className="flex items-center gap-2 text-[10px] font-black tracking-[.2em] text-[#7ff4df]"><MapPin className="h-4 w-4" />INFRO · PRESENCE STUDIO</div><h1 className="mt-3 text-2xl font-black sm:text-3xl">الفروع وفريق التواصل</h1><p className="mt-2 max-w-2xl text-sm leading-7 text-slate-300">ابنِ شبكة حضور واضحة لعميلك: أين يجدك، ومن الشخص المناسب للتواصل معه، بدون تعقيد إداري.</p></div><div className="flex flex-wrap gap-2"><MiniMetric label="فروع ظاهرة" value={`${visibleBranches}/${business.branches.length}`} /><MiniMetric label="فريق ظاهر" value={`${visibleContacts}/${business.contactPersons.length}`} /><Link href="/preview" target="_blank" className="inline-flex min-h-14 items-center gap-2 rounded-2xl bg-[#35e4cb] px-4 text-xs font-black text-[#07181b]"><Eye className="h-4 w-4" />معاينة الصفحة</Link></div></div></section>

    <section className="grid gap-4 xl:grid-cols-2">
      <article className="rounded-[28px] border border-[#dce8e7] bg-white p-5"><SectionHead icon={<Building2 className="h-5 w-5" />} eyebrow="01 · LOCATIONS" title="شبكة الفروع" count={`${business.branches.length}/${formatPlanLimit(entitlements.branchLimit)}`} /><p className="mt-2 text-xs leading-6 text-slate-500">أضف نقاط حضورك الفعلية، واجعل الفرع الرئيسي واضحًا للزائر.</p>
        {branchLimitReached ? <LimitMessage /> : <form action={createBranchAction} className="mt-4 grid gap-2 sm:grid-cols-2"><input name="name" required maxLength={120} placeholder="اسم الفرع" className={field} /><input name="city" maxLength={80} placeholder="المدينة" className={field} /><input name="district" maxLength={80} placeholder="الحي" className={field} /><input name="googleMapsLink" maxLength={500} placeholder="رابط Google Maps" dir="ltr" className={field} /><input name="address" maxLength={300} placeholder="العنوان (اختياري)" className={`${field} sm:col-span-2`} /><input name="phone" maxLength={40} placeholder="هاتف الفرع" dir="ltr" className={field} /><input name="whatsapp" maxLength={40} placeholder="واتساب الفرع" dir="ltr" className={field} /><button className={`${save} sm:w-fit`}><Plus className="h-4 w-4" />إضافة فرع</button></form>}
        <div className="mt-5 space-y-2">{business.branches.length ? business.branches.map((branch, index) => <details key={branch.id} className="group rounded-2xl border border-[#e2ebea] bg-[#f8fbfb] p-3 open:bg-white"><summary className="flex cursor-pointer list-none items-center justify-between gap-3"><div className="flex min-w-0 items-center gap-3"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-xl bg-[#e9fbf7] text-[10px] font-black text-[#008f87]">{String(index + 1).padStart(2, "0")}</span><div className="min-w-0"><b className="block truncate text-sm text-[#0a2426]">{branch.name}{branch.isMain ? <span className="mr-2 rounded-full bg-[#dff9f4] px-2 py-0.5 text-[9px] text-[#007a72]">الرئيسي</span> : null}</b><span className="block truncate text-[10px] text-slate-400">{[branch.city, branch.district].filter(Boolean).join("، ") || "بدون موقع"} · {branch.isActive ? "ظاهر" : "مخفي"}</span></div></div><Pencil className="h-4 w-4 text-[#008f87]" /></summary><form action={updateBranchAction} className="mt-3 grid gap-2 border-t border-[#e5eeed] pt-3 sm:grid-cols-2"><input type="hidden" name="id" value={branch.id} /><input type="hidden" name="sortOrder" value={branch.sortOrder} /><input name="name" required maxLength={120} defaultValue={branch.name} className={field} /><input name="city" maxLength={80} defaultValue={branch.city ?? ""} className={field} /><input name="district" maxLength={80} defaultValue={branch.district ?? ""} className={field} /><input name="googleMapsLink" maxLength={500} defaultValue={branch.googleMapsLink ?? ""} dir="ltr" className={field} /><input name="address" maxLength={300} defaultValue={branch.address ?? ""} className={`${field} sm:col-span-2`} /><input name="phone" maxLength={40} defaultValue={branch.phone ?? ""} dir="ltr" className={field} /><input name="whatsapp" maxLength={40} defaultValue={branch.whatsapp ?? ""} dir="ltr" className={field} /><label className="flex h-10 items-center gap-2 text-xs font-bold text-slate-600"><input type="checkbox" name="isMain" defaultChecked={branch.isMain} />رئيسي</label><label className="flex h-10 items-center gap-2 text-xs font-bold text-slate-600"><input type="checkbox" name="isActive" defaultChecked={branch.isActive} />ظاهر</label><button className={save}><Save className="h-3.5 w-3.5" />حفظ</button></form><form action={deleteBranchAction} className="mt-2"><input type="hidden" name="id" value={branch.id} /><ConfirmSubmitButton confirmMessage={`حذف الفرع «${branch.name}»؟`} /></form></details>) : <Empty text="لا توجد فروع بعد. أضف أول نقطة حضور لعملائك." />}</div>
      </article>

      <article className="rounded-[28px] border border-[#dce8e7] bg-white p-5"><SectionHead icon={<UsersRound className="h-5 w-5" />} eyebrow="02 · PEOPLE" title="فريق التواصل" count={`${business.contactPersons.length}/${formatPlanLimit(entitlements.contactLimit)}`} /><p className="mt-2 text-xs leading-6 text-slate-500">وجّه العميل للشخص الصحيح: مبيعات، خدمة عملاء، عمليات أو مسؤول فرع.</p>
        {contactLimitReached ? <LimitMessage /> : <form action={createContactPersonAction} className="mt-4 grid gap-2 sm:grid-cols-2"><input name="name" required maxLength={120} placeholder="الاسم" className={field} /><input name="jobTitle" maxLength={120} placeholder="المسمى الوظيفي" className={field} /><input name="whatsapp" maxLength={40} placeholder="واتساب" dir="ltr" className={field} /><input name="phone" maxLength={40} placeholder="الهاتف" dir="ltr" className={field} /><select name="branchId" className={field}><option value="">كل الفروع / بدون فرع</option>{business.branches.map((branch) => <option key={branch.id} value={branch.id}>{branch.name}</option>)}</select><input name="email" type="email" maxLength={254} placeholder="البريد" dir="ltr" className={field} /><button className={`${save} sm:w-fit`}><Plus className="h-4 w-4" />إضافة عضو</button></form>}
        <div className="mt-5 space-y-2">{business.contactPersons.length ? business.contactPersons.map((contact, index) => <details key={contact.id} className="rounded-2xl border border-[#e2ebea] bg-[#f8fbfb] p-3 open:bg-white"><summary className="flex cursor-pointer list-none items-center justify-between gap-3"><div className="flex min-w-0 items-center gap-3"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-xl bg-[#e9fbf7] text-[10px] font-black text-[#008f87]">{String(index + 1).padStart(2, "0")}</span><div className="min-w-0"><b className="block truncate text-sm text-[#0a2426]">{contact.name}{contact.isPrimary ? <span className="mr-2 rounded-full bg-[#dff9f4] px-2 py-0.5 text-[9px] text-[#007a72]">الرئيسي</span> : null}</b><span className="block truncate text-[10px] text-slate-400">{contact.jobTitle || "فريق التواصل"}{contact.branch ? ` · ${contact.branch.name}` : ""} · {contact.isActive ? "ظاهر" : "مخفي"}</span></div></div><Pencil className="h-4 w-4 text-[#008f87]" /></summary><form action={updateContactPersonAction} className="mt-3 grid gap-2 border-t border-[#e5eeed] pt-3 sm:grid-cols-2"><input type="hidden" name="id" value={contact.id} /><input type="hidden" name="sortOrder" value={contact.sortOrder} /><input name="name" required maxLength={120} defaultValue={contact.name} className={field} /><input name="jobTitle" maxLength={120} defaultValue={contact.jobTitle ?? ""} className={field} /><input name="whatsapp" maxLength={40} defaultValue={contact.whatsapp ?? ""} dir="ltr" className={field} /><input name="phone" maxLength={40} defaultValue={contact.phone ?? ""} dir="ltr" className={field} /><select name="branchId" defaultValue={contact.branchId ?? ""} className={field}><option value="">كل الفروع / بدون فرع</option>{business.branches.map((branch) => <option key={branch.id} value={branch.id}>{branch.name}</option>)}</select><input name="email" type="email" maxLength={254} defaultValue={contact.email ?? ""} dir="ltr" className={field} /><label className="flex h-10 items-center gap-2 text-xs font-bold text-slate-600"><input type="checkbox" name="isPrimary" defaultChecked={contact.isPrimary} />رئيسي</label><label className="flex h-10 items-center gap-2 text-xs font-bold text-slate-600"><input type="checkbox" name="isActive" defaultChecked={contact.isActive} />ظاهر</label><button className={save}><Save className="h-3.5 w-3.5" />حفظ</button></form><form action={deleteContactPersonAction} className="mt-2"><input type="hidden" name="id" value={contact.id} /><ConfirmSubmitButton confirmMessage={`حذف «${contact.name}» من فريق التواصل؟`} /></form></details>) : <Empty text="لا يوجد أعضاء فريق بعد. أضف أول جهة تواصل مباشرة." />}</div>
      </article>
    </section>
  </div>;
}

function MiniMetric({ label, value }: { label: string; value: string }) { return <div className="min-w-24 rounded-2xl border border-white/10 bg-white/[.05] px-4 py-2.5"><b className="block text-lg font-black text-[#7ff4df]">{value}</b><span className="text-[9px] text-slate-400">{label}</span></div>; }
function SectionHead({ icon, eyebrow, title, count }: { icon: React.ReactNode; eyebrow: string; title: string; count: string }) { return <div className="flex items-start justify-between gap-3"><div className="flex items-center gap-2 text-[#008f87]">{icon}<div><span className="block text-[9px] font-black tracking-[.16em]">{eyebrow}</span><h2 className="text-base font-black text-[#0a2426]">{title}</h2></div></div><span className="rounded-full bg-[#e9fbf7] px-3 py-1 text-[10px] font-black text-[#007a72]">{count}</span></div>; }
function LimitMessage() { return <div className="mt-4 rounded-xl border border-[#ccece6] bg-[#effbf8] px-3 py-2 text-xs font-bold text-[#007a72]">استخدمت حد باقتك الحالي. <Link href="/dashboard/settings" className="underline underline-offset-2">عرض الباقات</Link></div>; }
function Empty({ text }: { text: string }) { return <p className="rounded-2xl border border-dashed border-[#d7e5e3] p-6 text-center text-xs text-slate-400">{text}</p>; }
