"use client";

import { useActionState } from "react";
import { Braces, KeyRound, LockKeyhole, ShieldCheck, Webhook } from "lucide-react";
import { ConfirmSubmitButton } from "../../../../components/dashboard/confirm-submit-button";
import { createWhatsAppAutomationApiKeyAction, revokeWhatsAppAutomationApiKeyAction, type AutomationApiKeyActionState } from "../../../actions/whatsapp-marketing";

type SafeKey = { id: string; name: string; keyPrefix: string; status: string; createdAt: string; lastUsedAt: string | null; revokedAt: string | null };
const initialState: AutomationApiKeyActionState = { status: "idle" };

export function AutomationApiKeyManager({ keys }: { keys: SafeKey[] }) {
  const [state, createAction, pending] = useActionState(createWhatsAppAutomationApiKeyAction, initialState);
  const activeKeys = keys.filter((key) => key.status === "active").length;
  return <section className="min-w-0 overflow-hidden rounded-[26px] border border-slate-200 bg-white shadow-[0_18px_60px_-46px_rgba(7,24,27,.4)]">
    <div className="border-b border-slate-100 bg-[radial-gradient(circle_at_0%_0%,rgba(53,228,203,.14),transparent_34%),linear-gradient(135deg,#07181b,#0d292d)] p-4 text-white sm:p-6">
      <div className="flex flex-col gap-4 sm:flex-row sm:flex-wrap sm:items-start sm:justify-between"><div className="flex min-w-0 gap-3"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-2xl border border-white/10 bg-white/[.07] text-[#5cebd7]"><KeyRound className="h-5 w-5" aria-hidden="true" /></span><div className="min-w-0"><span className="text-[9px] font-black tracking-[.16em] text-[#64e7d5]" dir="ltr">INFRO AUTOMATION API</span><h2 className="mt-1 text-lg font-black">مفاتيح أحداث API</h2><p className="mt-1 max-w-2xl text-xs leading-6 text-slate-300">اربط أنظمتك بالأتمتة بدون كشف بيانات الاعتماد. المفتاح يُعرض مرة واحدة فقط ويخص هذه المنشأة.</p></div></div><div className="grid grid-cols-2 gap-2 sm:flex"><Stat label="المفاتيح" value={String(keys.length)} /><Stat label="النشطة" value={String(activeKeys)} /></div></div>
    </div>
    <div className="p-4 sm:p-6">
      <div className="grid gap-4 lg:grid-cols-[1fr_280px]"><form action={createAction} aria-busy={pending} className="min-w-0 rounded-2xl border border-slate-200 bg-[#fbfdfd] p-4"><label className="text-xs font-black text-slate-800">اسم واضح للمفتاح<input name="name" required maxLength={80} autoComplete="off" className="mt-2 h-12 w-full rounded-xl border border-slate-200 bg-white px-3 text-xs outline-none transition focus:border-[#00a99d] focus:ring-4 focus:ring-[#35e4cb]/10" placeholder="مثال: تكامل المتجر" /></label><button disabled={pending} className="mt-3 inline-flex min-h-11 w-full items-center justify-center gap-2 rounded-xl bg-[#07181b] px-5 text-xs font-black text-white transition hover:bg-[#0d292d] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#00bfae] focus-visible:ring-offset-2 disabled:bg-slate-300 sm:w-auto"><KeyRound className="h-4 w-4 text-[#55e7d3]" aria-hidden="true" />{pending ? "جارٍ الإنشاء…" : "إنشاء مفتاح آمن"}</button></form><div className="rounded-2xl border border-[#ccefe9] bg-[#effbf9] p-4 text-[11px] leading-6 text-[#17645f]"><ShieldCheck className="mb-2 h-5 w-5 text-[#008f87]" aria-hidden="true" /><b className="block text-xs text-[#075d58]">قاعدة أمان مهمة</b>خزّن المفتاح في مدير أسرار على الخادم فقط. لا تضعه داخل JavaScript في المتصفح أو تطبيق عميل أو سجلات عامة.</div></div>
      {state.status === "created" && state.plaintext ? <div role="status" aria-live="polite" className="mt-4 min-w-0 rounded-2xl border border-amber-300 bg-amber-50 p-4"><div className="flex items-center gap-2 text-amber-900"><LockKeyhole className="h-4 w-4 shrink-0" aria-hidden="true" /><b className="text-xs">انسخ المفتاح الآن؛ لن يظهر مجددًا</b></div><code dir="ltr" className="mt-3 block max-w-full overflow-x-auto select-all whitespace-nowrap rounded-xl border border-amber-200 bg-white p-3 text-xs text-slate-900">{state.plaintext}</code></div> : null}
      {state.status === "failed" ? <p role="alert" className="mt-4 rounded-xl bg-rose-50 p-3 text-xs font-bold text-rose-700">{state.error}</p> : null}
      <div className="mt-5 space-y-2">{keys.map((key) => <div key={key.id} className="grid min-w-0 gap-3 rounded-2xl border border-slate-100 bg-slate-50/70 p-3.5 sm:grid-cols-[minmax(0,1fr)_auto] sm:items-center"><div className="min-w-0"><div className="flex min-w-0 flex-wrap items-center gap-2"><b className="max-w-full break-words text-xs text-slate-900">{key.name}</b><code dir="ltr" className="max-w-full overflow-hidden text-ellipsis rounded-md bg-white px-2 py-1 text-[10px] text-slate-500">{key.keyPrefix}…</code><span className={`rounded-full px-2 py-1 text-[9px] font-black ${key.status === "active" ? "bg-emerald-100 text-emerald-700" : "bg-slate-200 text-slate-600"}`}>{key.status === "active" ? "نشط" : "ملغي"}</span></div><span className="mt-1.5 block text-[10px] leading-5 text-slate-400">آخر استخدام: {key.lastUsedAt ? new Date(key.lastUsedAt).toLocaleString("ar-SA", { timeZone: "Asia/Riyadh" }) : "لم يُستخدم"}</span></div>{key.status === "active" ? <form action={revokeWhatsAppAutomationApiKeyAction} className="w-full sm:w-auto"><input type="hidden" name="keyId" value={key.id} /><ConfirmSubmitButton label="إلغاء المفتاح" showIcon={false} className="min-h-11 w-full rounded-xl bg-rose-50 px-3 py-2 text-[10px] font-black text-rose-700 transition hover:bg-rose-100 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-rose-400 focus-visible:ring-offset-2 sm:w-auto" confirmMessage="إلغاء المفتاح يوقف جميع التكاملات التي تستخدمه فورًا ولا يمكن التراجع عنه. هل تريد المتابعة؟" /></form> : null}</div>)}{!keys.length ? <div className="rounded-2xl border border-dashed border-slate-200 p-6 text-center text-xs leading-6 text-slate-400">لا توجد مفاتيح API بعد. أنشئ مفتاحًا فقط عندما يكون لديك تكامل فعلي.</div> : null}</div>
      <div className="mt-5 grid min-w-0 gap-3 lg:grid-cols-2"><Endpoint icon={<Webhook className="h-4 w-4" aria-hidden="true" />} path="POST /api/whatsapp/automations/events">أرسل Bearer key مع JSON يحوي eventId وeventName وsubjectId اختياريًا، وواحدًا فقط من contactId أو phoneE164 بصيغة E.164. الطلب يسجل حدثًا durable ولا يرسل إلى Meta مباشرة.</Endpoint><Endpoint icon={<Braces className="h-4 w-4" aria-hidden="true" />} path="POST /api/whatsapp/automations/carts">أرسل eventId وcartId وstate بقيمة abandoned أو recovered أو completed وoccurredAt، مع contactId أو phoneE164. الاسترداد أو الإكمال يلغي الإرسال المعلق.</Endpoint></div>
    </div>
  </section>;
}
function Stat({label,value}:{label:string;value:string}){return <div className="min-w-0 rounded-xl border border-white/10 bg-white/[.06] px-3 py-2 text-center sm:min-w-[72px]"><b className="block text-base text-white">{value}</b><span className="text-[8px] font-bold text-slate-400">{label}</span></div>}
function Endpoint({icon,path,children}:{icon:React.ReactNode;path:string;children:React.ReactNode}){return <div className="min-w-0 rounded-2xl border border-slate-200 bg-[#fbfdfd] p-4"><div className="flex min-w-0 items-start gap-2 text-[#008f87]">{icon}<code dir="ltr" className="min-w-0 break-all text-left text-[10px] font-black leading-5">{path}</code></div><p className="mt-2 text-[11px] leading-6 text-slate-500">{children}</p></div>}
