import Link from "next/link";
import { redirect } from "next/navigation";
import { BadgeCheck, Download, ExternalLink, FileText, Link2, SearchCheck } from "lucide-react";
import { getCurrentUser } from "../../lib/auth";
import { getActiveBusinessForUser } from "../../lib/active-business";
import { updateCompanyProfileAction, removeCompanyProfileAction } from "../../actions/digital-identity";
import { DigitalPresenceForm } from "../../../components/dashboard/digital-presence-form";
import { IdentityAssets } from "../../../components/dashboard/identity-assets";

export default async function DigitalIdentityPage({ searchParams }: { searchParams?: Promise<Record<string, string | string[] | undefined>> }) {
  const user = await getCurrentUser(); if (!user) redirect("/login");
  const business = await getActiveBusinessForUser(user.id); if (!business) redirect("/onboarding");
  const params = await searchParams; const profile = Array.isArray(params?.profile) ? params?.profile[0] : params?.profile; const presence = Array.isArray(params?.presence) ? params?.presence[0] : params?.presence;
  const publicUrl = `https://ir.sa/${business.slug}`; const socialReady = Boolean(business.instagramUrl || business.xUrl || business.tiktokUrl || business.snapchatUrl || business.facebookUrl);
  const identityChecks = [
    { label: "شعار المنشأة", ok: Boolean(business.logoUrl) }, { label: "وصف واضح", ok: Boolean(business.shortDescription || business.description) }, { label: "وسيلة تواصل", ok: Boolean(business.whatsapp || business.phone || business.email || business.website) }, { label: "موقع المنشأة", ok: Boolean(business.city || business.address || business.googleMapsLink) }, { label: "موقع إلكتروني", ok: Boolean(business.website) }, { label: "شبكة اجتماعية", ok: socialReady }, { label: "تهيئة SEO", ok: Boolean(business.metaTitle || business.metaDescription) }, { label: "الملف التعريفي PDF", ok: Boolean(business.companyProfileUrl) }, { label: "الصفحة منشورة", ok: Boolean(business.isPublished && user.emailVerifiedAt) },
  ]; const complete = identityChecks.filter((item) => item.ok).length;
  return <div className="space-y-4 pb-4">
    <section className="rounded-[24px] border border-[#e7e9f4] bg-white p-4 sm:p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><BadgeCheck className="h-5 w-5 text-[#6f3bd2]" /><h1 className="text-xl font-black text-[#20264f]">الهوية الرقمية</h1></div><p className="mt-1 text-sm text-slate-500">مركز واحد لأصول منشأتك الرقمية الجاهزة للمشاركة مع العملاء والشركاء.</p></div><span className="rounded-full bg-[#f1edff] px-3 py-1.5 text-xs font-black text-[#5d49cc]">{complete}/{identityChecks.length} مكتمل</span></div></section>
    {profile === "saved" ? <div role="status" aria-live="polite" className="rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-bold text-emerald-800">تم حفظ الملف التعريفي PDF وأصبح مرتبطًا بالمنشأة.</div> : null}{profile === "removed" ? <div role="status" aria-live="polite" className="rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-bold text-emerald-800">تمت إزالة الملف التعريفي.</div> : null}{profile === "rate-limited" ? <div role="alert" className="rounded-2xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm font-bold text-amber-900">تم تجاوز عدد محاولات رفع الملف مؤقتًا. حاول مرة أخرى لاحقًا.</div> : null}{profile && !["saved", "removed", "rate-limited"].includes(profile) ? <div role="alert" className="rounded-2xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm font-bold text-rose-800">تعذر تحديث الملف التعريفي. ارفع ملف PDF صالحًا ضمن الحد المسموح ثم حاول مجددًا.</div> : null}
    <section className="grid gap-4 lg:grid-cols-2">
      <article id="company-profile" className="scroll-mt-24 rounded-[24px] border border-[#e7e9f4] bg-white p-4 sm:p-5"><div className="flex items-center gap-2"><FileText className="h-5 w-5 text-[#6f3bd2]" /><h2 className="font-black text-[#20264f]">الملف التعريفي للشركة PDF</h2></div><p className="mt-2 text-xs leading-6 text-slate-500">ارفع الملف التعريفي الرسمي للشركة. يظهر في الصفحة العامة وفي المعاينة فورًا، مع بقاء الملف محميًا عندما تكون الصفحة غير منشورة.</p>{business.companyProfileUrl ? <div className="mt-4 rounded-2xl border border-emerald-200 bg-emerald-50 p-3"><b className="block text-sm text-emerald-800">{business.companyProfileTitle || "الملف التعريفي للشركة"}</b><div className="mt-3 flex flex-wrap gap-2"><a href={business.companyProfileUrl} target="_blank" rel="noreferrer" className="inline-flex min-h-10 items-center gap-2 rounded-xl bg-white px-3 text-xs font-black text-emerald-800"><ExternalLink className="h-4 w-4" />فتح الملف</a><form action={removeCompanyProfileAction}><button className="min-h-10 rounded-xl border border-rose-200 bg-white px-3 text-xs font-black text-rose-700">إزالة</button></form></div></div> : null}<form action={updateCompanyProfileAction} encType="multipart/form-data" className="mt-4 space-y-3"><label className="grid gap-1.5 text-xs font-bold text-slate-600"><span>عنوان الملف</span><input name="profileTitle" defaultValue={business.companyProfileTitle || "الملف التعريفي للشركة"} maxLength={120} className="h-11 rounded-xl border border-[#e5e8f3] bg-[#fbfcff] px-3" /></label><label className="grid gap-1.5 text-xs font-bold text-slate-600"><span>{business.companyProfileUrl ? "استبدال ملف PDF" : "ملف PDF"}</span><input name="profileFile" type="file" required accept="application/pdf,.pdf" className="block min-h-11 rounded-xl border border-[#e5e8f3] bg-white px-3 py-2 text-xs" /></label><button className="min-h-11 rounded-xl bg-[#6f3bd2] px-4 text-xs font-black text-white">{business.companyProfileUrl ? "استبدال الملف" : "رفع الملف التعريفي"}</button></form></article>
      <article className="rounded-[24px] border border-[#e7e9f4] bg-white p-4 sm:p-5"><div className="flex items-center gap-2"><Link2 className="h-5 w-5 text-[#6f3bd2]" /><h2 className="font-black text-[#20264f]">الرابط والاتصال</h2></div><p className="mt-2 text-xs leading-6 text-slate-500">استخدم رابط iR الدائم في التوقيع والكروت والملفات، ونزّل vCard لإضافة بيانات المنشأة إلى جهات الاتصال.</p><div className="mt-4 rounded-2xl bg-[#faf9fd] p-4"><code dir="ltr" className="block max-w-full overflow-hidden text-ellipsis whitespace-nowrap text-[11px] text-slate-500">{publicUrl}</code><div className="mt-3 flex flex-wrap gap-2"><Link href={`/${business.slug}`} target="_blank" className="inline-flex min-h-10 items-center gap-2 rounded-xl bg-[#6f3bd2] px-3 text-xs font-black text-white"><ExternalLink className="h-4 w-4" />فتح الصفحة</Link><Link href="/api/dashboard/vcard" className="inline-flex min-h-10 items-center gap-2 rounded-xl border border-[#ddd8f4] bg-white px-3 text-xs font-black text-[#5d49cc]"><Download className="h-4 w-4" />تنزيل vCard</Link></div></div><p className="mt-3 text-[11px] leading-5 text-slate-500">لا يعتمد مركز الهوية على مولّد QR خارجي، حتى لا تُرسل روابط صفحات العملاء إلى خدمة طرف ثالث أو تتوقف أصول الهوية بتوقفها.</p></article>
    </section>
    <DigitalPresenceForm business={business} presenceStatus={presence} />
    <IdentityAssets businessName={business.name} logoUrl={business.logoUrl} primaryColor={business.primaryColor} phone={business.phone} whatsapp={business.whatsapp} email={business.email} website={business.website} publicUrl={publicUrl} />
    <section className="rounded-[24px] border border-[#e7e9f4] bg-white p-4 sm:p-5"><div className="flex items-center gap-2"><SearchCheck className="h-5 w-5 text-[#6f3bd2]" /><h2 className="font-black text-[#20264f]">اكتمال الهوية الرقمية</h2></div><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{identityChecks.map((item) => <div key={item.label} className={`rounded-xl border px-3 py-2 text-xs font-bold ${item.ok ? "border-emerald-200 bg-emerald-50 text-emerald-800" : "border-amber-200 bg-amber-50 text-amber-800"}`}>{item.ok ? "✓" : "○"} {item.label}</div>)}</div><p className="mt-3 text-[11px] leading-5 text-slate-500">تتضمن الصفحة العامة بيانات SEO وOpen Graph وSchema.org، وتستخدم الحقول أعلاه مباشرة عند النشر.</p></section>
  </div>;
}