import type { Metadata } from "next";
import type { CSSProperties, ReactNode } from "react";
import { Suspense } from "react";
import { IBM_Plex_Sans_Arabic, Inter } from "next/font/google";
import { LanguageSwitcher } from "../components/language-switcher";
import { LOCALE_META, SITE_MESSAGES } from "./lib/i18n";
import { getRequestLocale } from "./lib/i18n-server";
import { DEFAULT_PLATFORM_DESIGN, readPlatformDesign } from "./lib/platform-design";
import "./globals.css";
import "./ir-brand-compat.css";
const inter=Inter({variable:"--font-inter",subsets:["latin"]});const ibmPlexSansArabic=IBM_Plex_Sans_Arabic({variable:"--font-ibm-plex-sans-arabic",subsets:["arabic"],weight:["400","500","600","700"]});
async function publishedDesign(){try{return(await readPlatformDesign()).published}catch{return DEFAULT_PLATFORM_DESIGN}}
export async function generateMetadata():Promise<Metadata>{const locale=await getRequestLocale();const site=SITE_MESSAGES[locale];const d=await publishedDesign();const title=locale==="ar"?d.seoTitleAr:locale==="en"?d.seoTitleEn:site.title;const description=locale==="ar"?d.seoDescriptionAr:locale==="en"?d.seoDescriptionEn:site.description;return{metadataBase:new URL("https://ir.sa"),title:{default:title,template:`%s | ${d.brandNameEn}`},description,keywords:locale==="ar"||locale==="en"?d.seoKeywords:site.keywords,authors:[{name:d.brandNameEn}],creator:d.brandNameEn,publisher:d.brandNameEn,robots:{index:d.robotsIndex,follow:d.robotsFollow},icons:d.faviconUrl?{icon:d.faviconUrl}:undefined,openGraph:{title,description,url:"https://ir.sa",siteName:d.brandNameEn,locale:site.ogLocale,type:"website",images:d.ogImageUrl?[d.ogImageUrl]:undefined},twitter:{card:"summary_large_image",title,description,images:d.ogImageUrl?[d.ogImageUrl]:undefined}}}
export default async function RootLayout({children}:{children:ReactNode}){const locale=await getRequestLocale();const localeMeta=LOCALE_META[locale];const d=await publishedDesign();const vars={"--brand-primary":d.primaryColor,"--brand-secondary":d.secondaryColor,"--brand-accent":d.accentColor,"--brand-background":d.backgroundColor,"--brand-foreground":d.foregroundColor,"--brand-header-background":d.headerBackground,"--brand-header-foreground":d.headerForeground,"--brand-footer-background":d.footerBackground,"--brand-footer-foreground":d.footerForeground} as CSSProperties;return <html lang={localeMeta.htmlLang} dir={localeMeta.dir} suppressHydrationWarning className={`${inter.variable} ${ibmPlexSansArabic.variable} h-full antialiased`} style={vars}><head><link rel="stylesheet" href="/brand/ir-floating-header.css"/></head><body className="min-h-full flex flex-col" style={{background:d.backgroundColor,color:d.foregroundColor}}>{children}<Suspense fallback={null}><LanguageSwitcher locale={locale}/></Suspense></body></html>}
