import Link from "next/link";
import { redirect } from "next/navigation";
import { AlertTriangle, FileText, RefreshCw, CheckCircle2 } from "lucide-react";
import { syncWhatsAppTemplatesAction } from "../../../actions/whatsapp-marketing";
import { db } from "../../../lib/db";
import { hasActiveWhatsAppMarketingEntitlement } from "../../../lib/whatsapp/feature-entitlement";
import { getWhatsAppReadContext } from "../../../lib/whatsapp/rbac";

export default async function WhatsAppTemplatesPage({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  const context = await getWhatsAppReadContext("campaign.manage"); if (!context) redirect("/dashboard/whatsapp?access=denied");
  if (!await hasActiveWhatsAppMarketingEntitlement({ businessId: context.businessId })) redirect("/dashboard/billing/manage?feature=whatsapp-marketing");
  const params = await searchParams;
  const [connection, templates] = await Promise.all([
    db.whatsAppConnection.findFirst({ where: { businessId: context.businessId, provider: "meta" }, select: { id: true, status: true, disabledAt: true, verifiedName: true, displayPhoneNumber: true } }),
    db.whatsAppTemplate.findMany({ where: { businessId: context.businessId, provider: "meta" }, orderBy: [{ status: "asc" }, { updatedAt: "desc" }], take: 200, select: { id: true, name: true, language: true, category: true, status: true, providerStatus: true, qualityScore: true, rejectedReason: true, lastSyncedAt: true } }),
  ]);
  const connectionReady = connection?.status === "connected" && !connection.disabledAt;
  const approvedCount = templates.filter((x) => x.status === "approved").length;
  const pendingCount = templates.filter((x) => x.status === "pending").length;
  const rejectedCount = templates.filter((x) => x.status === "rejected").length;

  return <div className="space-y-5 pb-5">
    <header className="relative overflow-hidden rounded-[28px] border border-slate-200 bg-white p-5 sm:p-6"><div className="absolute -left-16 -top-20 h-48 w-48 rounded-full bg-[#c9f8f0]/80 blur-3xl"/><div className="relative flex flex-wrap items-start justify-between gap-4"><div><p className="flex items-center gap-1.5 text-[9px] font-black tracking-[.16em] text-[#008f87]" dir="ltr"><FileText className="h-3.5 w-3.5"/>META MESSAGE TEMPLATES</p><h1 className="mt-2 text-2xl font-black">قوالب رسائل واتساب</h1><p className="mt-2 max-w-2xl text-xs leading-6 text-slate-500">اعرض القوالب المرتبطة برقم منشأتك وحالتها لدى Meta. القالب المعتمد فقط يمكن استخدامه في الحملات، وقرار الاعتماد يبقى صادرًا من Meta.</p></div>{connectionReady ? <form action={syncWhatsAppTemplatesAction}><input type="hidden" name="connectionId" value={connection.id}/><button className="inline-flex min-h-10 items-center gap-2 rounded-xl bg-[#07181b] px-4 text-[10px] font-black text-white hover:bg-[#0d2a2e]"><RefreshCw className="h-3.5 w-3.5"/>تحديث القوالب</button></form> : <Link href="/dashboard/whatsapp/setup" className="rounded-xl bg-[#07181b] px-4 py-2.5 text-[10px] font-black text-white">ربط رقم واتساب</Link>}</div></header>
    {!connectionReady && connection ? <p className="flex items-center gap-2 rounded-2xl border border-amber-200 bg-amber-50 p-3 text-[10px] font-bold text-amber-800"><AlertTriangle className="h-4 w-4"/>رقم واتساب المرتبط غير جاهز حاليًا. أعد تفعيل الاتصال أولًا ثم حدّث القوالب.</p> : null}
    {params.sync ? <p aria-live="polite" className={`flex items-center gap-2 rounded-2xl border p-3 text-[10px] font-bold ${params.sync === "complete" ? "border-emerald-200 bg-emerald-50 text-emerald-800" : "border-rose-200 bg-rose-50 text-rose-800"}`}>{params.sync === "complete" ? <CheckCircle2 className="h-4 w-4"/> : <AlertTriangle className="h-4 w-4"/>}{params.sync === "complete" ? `تم تحديث القوالب بنجاح (${params.count ?? 0}).` : "تعذر تحديث القوالب. تحقق من اتصال الرقم ثم أعد المحاولة."}</p> : null}
    <section className="grid gap-3 sm:grid-cols-3"><Status label="معتمدة" count={approvedCount} color="emerald"/><Status label="قيد المراجعة" count={pendingCount} color="amber"/><Status label="غير معتمدة" count={rejectedCount} color="rose"/></section>
    <section className="rounded-[26px] border border-slate-200 bg-white p-4 sm:p-5"><div className="overflow-x-auto"><table className="w-full min-w-[800px] text-right text-[10px]"><thead><tr className="border-b border-slate-100 text-slate-400"><th className="p-2">القالب</th><th className="p-2">اللغة</th><th className="p-2">النوع</th><th className="p-2">الحالة</th><th className="p-2">الجودة أو سبب الرفض</th><th className="p-2">آخر تحديث</th></tr></thead><tbody>{templates.map((template)=><tr key={template.id} className="border-b border-slate-100 last:border-0 hover:bg-slate-50/50"><td className="p-2 font-bold text-slate-800">{template.name}</td><td className="p-2">{languageLabel(template.language)}</td><td className="p-2">{categoryLabel(template.category)}</td><td className="p-2"><span className={`rounded-full px-2.5 py-1 font-black ${template.status === "approved" ? "bg-emerald-50 text-emerald-700" : template.status === "rejected" ? "bg-rose-50 text-rose-700" : "bg-amber-50 text-amber-700"}`}>{templateStatusLabel(template.status)}</span></td><td className="max-w-xs p-2 text-slate-500">{template.qualityScore || template.rejectedReason || "—"}</td><td className="p-2 text-slate-400">{template.lastSyncedAt.toLocaleString("ar-SA")}</td></tr>)}{!templates.length ? <tr><td colSpan={6} className="p-8 text-center"><div className="mx-auto max-w-md"><FileText className="mx-auto h-6 w-6 text-slate-300"/><p className="mt-3 font-black">ابدأ بتحديث قوالب رقمك</p><p className="mt-2 leading-6 text-slate-500">{connectionReady ? "إذا أنشأت قالبًا في Meta ولم يظهر هنا بعد، حدّث القوالب لجلب حالته الحالية." : "اربط رقم واتساب التجاري أولًا، وبعد نجاح الربط ستظهر القوالب وحالات اعتمادها هنا."}</p><div className="mt-4 flex flex-wrap justify-center gap-2">{connectionReady ? <form action={syncWhatsAppTemplatesAction}><input type="hidden" name="connectionId" value={connection!.id}/><button className="rounded-xl bg-[#07181b] px-4 py-2 font-black text-white">تحديث القوالب الآن</button></form> : <Link href="/dashboard/whatsapp/setup" className="rounded-xl bg-[#07181b] px-4 py-2 font-black text-white">إكمال ربط الرقم</Link>}<Link href="/dashboard/whatsapp/campaigns" className="rounded-xl border border-[#bdebe5] bg-[#effbf9] px-4 py-2 font-black text-[#008f87]">الانتقال إلى الحملات</Link></div></div></td></tr> : null}</tbody></table></div></section>
  </div>;
}

function Status({ label, count, color }: { label: string; count: number; color: "emerald" | "amber" | "rose" }) { const classes = color === "emerald" ? "border-emerald-100 bg-emerald-50 text-emerald-800" : color === "amber" ? "border-amber-100 bg-amber-50 text-amber-800" : "border-rose-100 bg-rose-50 text-rose-800"; return <article className={`rounded-[20px] border p-4 ${classes}`}><span className="text-[10px] font-bold">{label}</span><b className="mt-1 block text-2xl">{count}</b></article>; }
function templateStatusLabel(status: string) { if (status === "approved") return "معتمد"; if (status === "pending") return "قيد المراجعة"; if (status === "rejected") return "غير معتمد"; if (status === "paused") return "موقوف مؤقتًا"; if (status === "disabled") return "معطّل"; return "قيد التحديث"; }
function categoryLabel(category: string) { const normalized = category.toLowerCase(); if (normalized === "marketing") return "تسويقي"; if (normalized === "utility") return "خدمي"; if (normalized === "authentication") return "مصادقة"; return category || "—"; }
function languageLabel(language: string) { if (language === "ar" || language.startsWith("ar_")) return "العربية"; if (language === "en" || language.startsWith("en_")) return "الإنجليزية"; return language; }
