import Link from "next/link";
import { redirect } from "next/navigation";
import { FileText, RefreshCw } from "lucide-react";
import { syncWhatsAppTemplatesAction } from "../../../actions/whatsapp-marketing";
import { db } from "../../../lib/db";
import { hasActiveWhatsAppMarketingEntitlement } from "../../../lib/whatsapp/feature-entitlement";
import { getWhatsAppReadContext } from "../../../lib/whatsapp/rbac";

export default async function WhatsAppTemplatesPage({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  const context = await getWhatsAppReadContext("campaign.manage"); if (!context) redirect("/dashboard/whatsapp?access=denied");
  if (!await hasActiveWhatsAppMarketingEntitlement({ businessId: context.businessId })) redirect("/dashboard/billing/manage?feature=whatsapp-marketing");
  const params = await searchParams;
  const [connection, templates] = await Promise.all([
    db.whatsAppConnection.findFirst({ where: { businessId: context.businessId, provider: "meta" }, select: { id: true, status: true, verifiedName: true, displayPhoneNumber: true } }),
    db.whatsAppTemplate.findMany({ where: { businessId: context.businessId }, orderBy: [{ status: "asc" }, { updatedAt: "desc" }], take: 200, select: { id: true, name: true, language: true, category: true, status: true, providerStatus: true, qualityScore: true, rejectedReason: true, lastSyncedAt: true } }),
  ]);
  return <div className="space-y-4 pb-5"><header className="flex flex-wrap items-start justify-between gap-3 rounded-[24px] border bg-white p-5"><div><div className="flex items-center gap-2"><FileText className="h-5 w-5 text-[#6543ce]" /><h1 className="text-xl font-black text-[#20264f]">قوالب WhatsApp المعتمدة</h1></div><p className="mt-2 text-sm text-slate-500">الحالة تأتي مباشرة من Meta ولا يمكن لـiR اعتماد قالب مرفوض أو معلق.</p></div><div className="flex gap-2"><Link href="/dashboard/whatsapp" className="rounded-xl border px-3 py-2 text-xs font-black text-[#5d49cc]">مركز واتساب</Link>{connection?.status === "connected" ? <form action={syncWhatsAppTemplatesAction}><input type="hidden" name="connectionId" value={connection.id} /><button className="inline-flex min-h-10 items-center gap-2 rounded-xl bg-[#6f3bd2] px-4 text-xs font-black text-white"><RefreshCw className="h-4 w-4" />مزامنة من Meta</button></form> : <Link href="/dashboard/whatsapp/setup" className="rounded-xl bg-emerald-600 px-4 py-2 text-xs font-black text-white">ربط الرقم أولًا</Link>}</div></header>
    {params.sync ? <p className={`rounded-2xl p-3 text-xs font-bold ${params.sync === "complete" ? "bg-emerald-50 text-emerald-800" : "bg-rose-50 text-rose-800"}`}>{params.sync === "complete" ? `تمت مزامنة ${params.count ?? 0} قالب.` : "تعذرت المزامنة. تحقق من الاتصال واعتماد Meta."}</p> : null}
    <section className="grid gap-3 sm:grid-cols-3"><Status label="Approved" count={templates.filter((x) => x.status === "approved").length} color="emerald" /><Status label="Pending" count={templates.filter((x) => x.status === "pending").length} color="amber" /><Status label="Rejected" count={templates.filter((x) => x.status === "rejected").length} color="rose" /></section>
    <section className="rounded-[24px] border bg-white p-4"><div className="overflow-x-auto"><table className="w-full min-w-[800px] text-right text-xs"><thead><tr className="border-b text-slate-400"><th className="p-2">القالب</th><th className="p-2">اللغة</th><th className="p-2">الفئة</th><th className="p-2">الحالة</th><th className="p-2">الجودة/السبب</th><th className="p-2">آخر مزامنة</th></tr></thead><tbody>{templates.map((template) => <tr key={template.id} className="border-b last:border-0"><td className="p-2 font-bold">{template.name}</td><td className="p-2">{template.language}</td><td className="p-2">{template.category}</td><td className="p-2"><span className={`font-black ${template.status === "approved" ? "text-emerald-700" : template.status === "rejected" ? "text-rose-700" : "text-amber-700"}`}>{template.status}</span></td><td className="max-w-xs p-2 text-slate-500">{template.qualityScore || template.rejectedReason || "—"}</td><td className="p-2 text-slate-400">{template.lastSyncedAt.toLocaleString("ar-SA")}</td></tr>)}{!templates.length ? <tr><td colSpan={6} className="p-8 text-center text-slate-400">لا توجد قوالب متزامنة بعد.</td></tr> : null}</tbody></table></div></section>
  </div>;
}
function Status({ label, count, color }: { label: string; count: number; color: "emerald" | "amber" | "rose" }) { const classes = color === "emerald" ? "bg-emerald-50 text-emerald-800" : color === "amber" ? "bg-amber-50 text-amber-800" : "bg-rose-50 text-rose-800"; return <article className={`rounded-[20px] p-4 ${classes}`}><span className="text-xs font-bold">{label}</span><b className="mt-1 block text-2xl">{count}</b></article>; }
