"use client";
import { usePlatformBrand } from "./platform-brand-provider";
import Image from "next/image";
type IrLogoProps={className?:string;priority?:boolean;showTagline?:boolean};
type IrMarkProps={className?:string;priority?:boolean};
/** Approved compact iR symbol for icon-only brand placements. */
// Keep the compact mark on customer identity pages pixel-identical to the
// approved mark used by the main INFRO navigation. A single source prevents
// subtle differences in crop, gradient, and proportions between surfaces.
export function IrMark({className="h-10",priority=false}:IrMarkProps){const brand=usePlatformBrand();if(brand.symbolUrl)return <Image src={brand.symbolUrl} alt="" aria-hidden="true" width={128} height={128} priority={priority} unoptimized className={`w-auto shrink-0 object-contain ${className}`}/>;return <Image src="/brand/infro-symbol-approved.png" alt="" aria-hidden="true" width={309} height={606} priority={priority} unoptimized sizes="(max-width:640px) 32px,40px" className={`w-auto shrink-0 object-contain ${className}`}/>}
/** INFRO lockup: approved gradient symbol plus adaptive wordmark for light/dark surfaces. */
export function IrLogo({className="h-12",priority=false,showTagline=false}:IrLogoProps){const brand=usePlatformBrand();if(brand.logoUrl||brand.logoDarkUrl)return <span className={`inline-flex ${className}`}><Image src={brand.logoUrl??brand.logoDarkUrl!} alt={brand.brandNameEn} width={400} height={160} priority={priority} unoptimized className={`h-full w-auto object-contain ${brand.logoDarkUrl?"dark:hidden":""}`}/>{brand.logoDarkUrl?<Image src={brand.logoDarkUrl} alt={brand.brandNameEn} width={400} height={160} priority={priority} unoptimized className="hidden h-full w-auto object-contain dark:block"/>:null}</span>;return <span className={`inline-flex items-center gap-2.5 ${className}`}><IrMark className="h-full" priority={priority}/><span className="flex min-w-0 flex-col leading-none"><span className="font-black tracking-[-.055em] text-current" style={{fontSize:"1.12em"}}>INFR<span className="relative">O<span className="absolute left-1/2 top-1/2 h-[.24em] w-[.24em] -translate-x-1/2 -translate-y-1/2 rounded-full bg-gradient-to-br from-[#08bfe8] via-[#00d8c6] to-[#00eea8]"/></span></span>{showTagline&&<span className="mt-1 whitespace-nowrap text-[.23em] font-bold tracking-[.08em] opacity-60">YOUR DIGITAL &amp; MARKETING IDENTITY</span>}</span></span>}
