import test from "node:test";
import assert from "node:assert/strict";
import { requireApprovedBookingAuthentication, sendBookingAuthentication, BookingProviderError } from "../app/lib/booking-verification-provider";
const template={id:"123456789",name:"infro_booking_verification",language:"ar",category:"AUTHENTICATION",status:"APPROVED",components:[{type:"BUTTONS",buttons:[{type:"OTP",otp_type:"COPY_CODE"}]}]};
const approval={url:"https://graph.facebook.com/v23.0/123456789?fields=status",token:"do-not-print-token",id:template.id,name:template.name};
test("approval is rechecked and paused, rejected, wrong tenant/name/language/category templates fail closed",async()=>{await requireApprovedBookingAuthentication({...approval,fetcher:async()=>Response.json(template)});for(const change of [{status:"PENDING"},{status:"PAUSED"},{category:"MARKETING"},{language:"en"},{id:"different"},{name:"other"},{components:[]}])await assert.rejects(requireApprovedBookingAuthentication({...approval,fetcher:async()=>Response.json({...template,...change})}),BookingProviderError);});
test("copy-code sends use official Meta only and return acceptance without claiming delivery",async()=>{let calls=0;const id=await sendBookingAuthentication({url:"https://graph.facebook.com/v23.0/998877/messages",token:approval.token,name:template.name,phone:"+966500009999",code:"012345",fetcher:async(url,init)=>{calls++;assert.equal(String(url),"https://graph.facebook.com/v23.0/998877/messages");assert.equal(init?.method,"POST");assert.equal(init?.redirect,"error");const body=JSON.parse(String(init?.body));assert.equal(body.to,"966500009999");assert.equal(body.template.components[0].parameters[0].text,"012345");return Response.json({messages:[{id:"ci-accepted-receipt"}]});}});assert.equal(id,"ci-accepted-receipt");assert.equal(calls,1);});
test("uncertain sends and Meta billing failures are never retried or exposed as raw messages",async()=>{for(const outcome of ["timeout","billing","bad-receipt"]){let calls=0;await assert.rejects(sendBookingAuthentication({url:"https://graph.facebook.com/v23.0/998877/messages",token:approval.token,name:template.name,phone:"+966500009999",code:"012345",fetcher:async()=>{calls++;if(outcome==="timeout")throw new Error("secret-provider-body");return outcome==="billing"?Response.json({error:{code:131042,message:"secret-provider-body"}},{status:400}):Response.json({messages:[]});}}),error=>error instanceof BookingProviderError && !error.message.includes("secret") && (outcome!=="billing" || error.reason==="meta_131042"));assert.equal(calls,1);}});
test("an alternative provider cannot be used for authentication",async()=>{let called=false;await assert.rejects(sendBookingAuthentication({url:"https://example.com/v23.0/998877/messages",token:approval.token,name:template.name,phone:"+966500009999",code:"012345",fetcher:async()=>{called=true;return Response.json({});}}));assert.equal(called,false);});
