import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import test from "node:test";

function source(path: string) {
  return readFileSync(resolve(process.cwd(), path), "utf8");
}

function assertUsesContentProvenQualityGate(workflow: string) {
  assert.match(workflow, /uses: \.\/\.github\/actions\/require-release-quality/);
  assert.match(workflow, /GH_TOKEN: \$\{\{ github\.token \}\}/);
}

test("release quality provenance accepts only exact green RC or a tree-identical directly tested merge parent", () => {
  const script = source("../../.github/scripts/require-release-quality.sh");
  const action = source("../../.github/actions/require-release-quality/action.yml");
  assert.match(action, /require-release-quality\.sh/);
  assert.match(script, /green_runs_for_sha/);
  assert.match(script, /head_sha=\$\{candidate\}/);
  assert.match(script, /\.conclusion == "success"/);
  assert.match(script, /\.event == "push" or \.event == "pull_request"/);
  assert.match(script, /exact_runs="\$\(green_runs_for_sha "\$sha"\)"/);
  assert.match(script, /git\/commits\/\$\{sha\}/);
  assert.match(script, /release_tree/);
  assert.match(script, /mapfile -t parents/);
  assert.match(script, /if \[ "\$\{#parents\[@\]\}" -lt 2 \]/);
  assert.match(script, /git\/commits\/\$\{parent\}/);
  assert.match(script, /\[ "\$parent_tree" = "\$release_tree" \] \|\| continue/);
  assert.match(script, /parent_runs="\$\(green_runs_for_sha "\$parent"\)"/);
  assert.match(script, /tree-identical directly tested parent/);
  assert.doesNotMatch(script, /git rev-list/);
  assert.doesNotMatch(script, /merge-base --is-ancestor/);
});

test("production migrations stay manually gated to the release branch with writes paused", () => {
  const workflow = source("../../.github/workflows/production-migrations.yml");
  assert.match(workflow, /workflow_dispatch:/);
  assert.match(workflow, /APPLY_PRODUCTION_MIGRATIONS/);
  assert.match(workflow, /PRODUCTION_WRITES_PAUSED/);
  assert.match(workflow, /inputs\.writes_paused_confirmation == 'PRODUCTION_WRITES_PAUSED'/);
  assert.match(workflow, /github\.ref == 'refs\/heads\/hee-v6-rc'/);
  assert.match(workflow, /environment: production/);
  assertUsesContentProvenQualityGate(workflow);
  assert.match(workflow, /production-preflight-v2\.yml\/runs\?head_sha=\$\{GITHUB_SHA\}/);
  assert.match(workflow, /exact release SHA \$\{GITHUB_SHA\} has no successful Production Preflight V2 run/);
});

test("production migrations verify and restore an encrypted recovery backup into a clean isolated schema before deploy", () => {
  const workflow = source("../../.github/workflows/production-migrations.yml");
  const decryptIndex = workflow.indexOf("Verify encrypted backup can be decrypted and parsed");
  const resetIndex = workflow.indexOf("Reset isolated restore schema");
  const restoreIndex = workflow.indexOf("Restore exact pre-migration backup into isolated database");
  const proofIndex = workflow.indexOf("npm run backup:production-proof");
  const migrateIndex = workflow.indexOf("Apply pending migrations");
  assert.ok(decryptIndex >= 0, "encrypted backup decrypt/parse verification step must exist");
  assert.ok(resetIndex > decryptIndex, "isolated restore schema must reset after decrypt verification");
  assert.ok(restoreIndex > resetIndex, "restore must run after clean isolated schema reset");
  assert.ok(proofIndex > restoreIndex, "restore proof must run after isolated restore");
  assert.ok(migrateIndex > proofIndex, "verified restore proof must complete before migrations");
  assert.match(workflow, /openssl enc -d -aes-256-cbc -pbkdf2 -iter 200000/);
  assert.match(workflow, /pg_restore --list/);
  assert.match(workflow, /DROP SCHEMA IF EXISTS public CASCADE; CREATE SCHEMA public/);
  assert.match(workflow, /pg_restore --exit-on-error --dbname="\$RESTORE_DATABASE_URL" --no-owner --no-privileges/);
  assert.match(workflow, /npm run backup:production-proof/);
  assert.match(workflow, /retention-days: 14/);
});

test("production preflight V2 proves external prerequisites read-only before maintenance", () => {
  const workflow = source("../../.github/workflows/production-preflight-v2.yml");
  assert.match(workflow, /VERIFY_PRODUCTION_PREFLIGHT/);
  assert.match(workflow, /github\.ref == 'refs\/heads\/hee-v6-rc'/);
  assert.match(workflow, /environment: production/);
  assertUsesContentProvenQualityGate(workflow);
  assert.match(workflow, /PRODUCTION_DATABASE_URL/);
  assert.match(workflow, /PRODUCTION_RESTORE_DATABASE_URL/);
  assert.match(workflow, /PRODUCTION_VERCEL_TOKEN/);
  assert.match(workflow, /RESTORE_DATABASE_URL must name hee_restore/);
  assert.match(workflow, /must use sslmode=verify-full/);
  assert.match(workflow, /api\.vercel\.com\/v9\/projects/);
  assert.match(workflow, /api\.resend\.com\/domains\?limit=100/);
  assert.match(workflow, /api\.moyasar\.com\/v1\/payments\?page=1/);
  assert.match(workflow, /PAID_CHECKOUT_PUBLIC_ENABLED/);
  assert.match(workflow, /Rehearsal account must not be enabled during preflight/);
  assert.match(workflow, /no production mutation performed/);
  assert.doesNotMatch(workflow, /vercel(?:@latest)? deploy/);
  assert.doesNotMatch(workflow, /prisma migrate deploy/);
  assert.doesNotMatch(workflow, /prisma db push/);
  assert.doesNotMatch(workflow, /billing:renew/);
  assert.doesNotMatch(workflow, /pg_dump/);
  assert.doesNotMatch(workflow, /pg_restore/);
  assert.doesNotMatch(workflow, /\bDROP\s+(?:TABLE|DATABASE|SCHEMA)\b/i);
  assert.doesNotMatch(workflow, /\bDELETE\s+FROM\b/i);
  assert.doesNotMatch(workflow, /\bUPDATE\s+[^\n]+\s+SET\b/i);
  assert.doesNotMatch(workflow, /\bINSERT\s+INTO\b/i);
});

test("production web deployment rebuilds the exact content-proven SHA with one reviewed Production environment sync and proves canonical provenance", () => {
  const workflow = source("../../.github/workflows/production-deploy.yml");
  const sync = source("../../.github/scripts/sync-vercel-production-env.mjs");
  assert.match(workflow, /DEPLOY_EXACT_RELEASE_TO_PRODUCTION/);
  assert.match(workflow, /github\.ref == 'refs\/heads\/hee-v6-rc'/);
  assert.match(workflow, /environment: production/);
  assert.match(workflow, /ref: \$\{\{ github\.sha \}\}/);
  assertUsesContentProvenQualityGate(workflow);
  assert.match(workflow, /production-preflight-v2\.yml/);
  assert.match(workflow, /production-enter-maintenance\.yml/);
  assert.match(workflow, /production-migrations\.yml/);
  assert.match(workflow, /Exact release SHA has no green Production Preflight V2 run/);
  assert.match(workflow, /no fully successful Production Migrations run; refusing live web cutover/);
  assert.match(workflow, /PRODUCTION_VERCEL_TOKEN/);
  assert.match(workflow, /VERCEL_PROJECT_ID: prj_LMlusvAi1f5ByOZM02xyXc1MRxph/);
  assert.match(workflow, /VERCEL_ORG_ID: team_CpksedcfKT4t6GvlcqxHMRjg/);
  assert.match(workflow, /VERCEL_CLI_VERSION: 59\.3\.0/);
  assert.match(workflow, /RELEASE_SHA: \$\{\{ github\.sha \}\}/);
  assert.match(workflow, /node \.github\/scripts\/sync-vercel-production-env\.mjs/);
  assert.match(sync, /process\.env\.RELEASE_SHA !== process\.env\.GITHUB_SHA/);
  assert.match(sync, /"RELEASE_SHA"/);
  assert.match(sync, /api\.vercel\.com\/v10\/projects/);
  assert.match(sync, /upsert=true/);
  assert.match(sync, /QA_AUDIT_SECRET/);
  assert.match(sync, /QA_AUDIT_USER_EMAIL/);
  assert.match(sync, /PRODUCTION_MAINTENANCE_MODE must remain deployment-scoped/);
  assert.match(sync, /CANONICAL_FROM_EMAIL = "HEE <no-reply@ir\.sa>"/);
  assert.match(sync, /key: "HEE_FROM_EMAIL", value: CANONICAL_FROM_EMAIL/);
  assert.match(sync, /key: "PAID_CHECKOUT_PUBLIC_ENABLED", value: "false"/);
  assert.match(sync, /key: "BILLING_REHEARSAL_USER_EMAIL", value: ""/);
  assert.match(workflow, /--env RELEASE_SHA="\$GITHUB_SHA"/);
  assert.match(workflow, /--build-env RELEASE_SHA="\$GITHUB_SHA"/);
  assert.match(workflow, /npx prisma migrate status/);
  assert.match(workflow, /deploy --prod --skip-domain --yes/);
  assert.match(workflow, /\/api\/health\/web-ready/);
  assert.doesNotMatch(workflow, /vercel@latest/);
  assert.doesNotMatch(workflow, /const plainKeys = \[/);
  assert.doesNotMatch(workflow, /const sensitiveKeys = \[/);
  assert.doesNotMatch(workflow, /env\?upsert=true/);
  assert.match(workflow, /https:\/\/ir\.sa\/api\/release/);
  assert.match(workflow, /https:\/\/ir\.sa\/api\/maintenance\/status/);
  assert.match(workflow, /https:\/\/ir\.sa\/api\/health\/web-ready/);
  assert.match(workflow, /status\.maintenance !== false/);
  assert.match(workflow, /webReady\.ready !== true/);
  assert.match(workflow, /\/register/);
  assert.match(workflow, /\/demo/);
  assert.doesNotMatch(workflow, /prisma migrate deploy/);
  assert.doesNotMatch(workflow, /prisma db push/);
  assert.doesNotMatch(workflow, /billing:renew/);
  assert.doesNotMatch(workflow, /pg_restore/);
});

test("production launch readiness proves content-qualified release, verified public paid launch, email domain, runtime, database, billing liveness and canonical surfaces", () => {
  const workflow = source("../../.github/workflows/production-launch-readiness.yml");
  const audit = source("scripts/launch-config-audit.ts");
  const release = source("app/api/release/route.ts");
  const webReadiness = source("app/lib/production-runtime-readiness.ts");
  const ready = source("app/api/health/ready/route.ts");
  const launchStatus = source("app/api/billing/launch-status/route.ts");
  assert.match(workflow, /VERIFY_PRODUCTION_READINESS/);
  assert.match(workflow, /github\.ref == 'refs\/heads\/hee-v6-rc'/);
  assert.match(workflow, /environment: production/);
  assertUsesContentProvenQualityGate(workflow);
  assert.match(workflow, /production-open-paid-checkout\.yml\/runs\?head_sha=\$\{GITHUB_SHA\}/);
  assert.match(workflow, /Exact release SHA has no successful verified Production Open Paid Checkout run/);
  assert.match(workflow, /npm run launch:config-audit/);
  assert.match(workflow, /api\.resend\.com\/domains\?limit=100/);
  assert.match(workflow, /Resend ir\.sa domain is missing or not verified/);
  assert.match(workflow, /sending capability is not enabled/);
  assert.match(workflow, /npx prisma migrate status/);
  assert.match(workflow, /npm run billing:state-audit/);
  assert.doesNotMatch(workflow, /--record-heartbeat/);
  assert.match(workflow, /PRODUCTION_PAID_CHECKOUT_PUBLIC_ENABLED/);
  assert.match(workflow, /PRODUCTION_BILLING_REHEARSAL_USER_EMAIL/);
  assert.match(workflow, /https:\/\/ir\.sa\/api\/release/);
  assert.match(workflow, /release_sha/);
  assert.match(workflow, /test "\$release_sha" = "\$GITHUB_SHA"/);
  assert.match(workflow, /release_env/);
  assert.match(workflow, /https:\/\/ir\.sa\/api\/billing\/launch-status/);
  assert.match(workflow, /launch\.releaseSha !== process\.env\.GITHUB_SHA/);
  assert.match(workflow, /launch\.mode !== "public"/);
  assert.match(workflow, /launch\.billingOperationsReady !== true/);
  assert.match(workflow, /launch\.renewalEnabled !== true/);
  assert.match(workflow, /https:\/\/ir\.sa\/api\/health\/ready/);
  assert.match(workflow, /Canonical production runtime reports not ready/);
  assert.match(workflow, /\/register/);
  assert.match(workflow, /\/login/);
  assert.match(workflow, /\/demo/);
  assert.match(workflow, /strict-transport-security/);
  assert.match(workflow, /content-security-policy/);
  assert.match(workflow, /noindex/);
  assert.match(release, /VERCEL_GIT_COMMIT_SHA/);
  assert.match(release, /RELEASE_SHA/);
  assert.match(release, /Cache-Control/);
  assert.match(release, /no-store/);
  assert.match(release, /X-Robots-Tag/);
  assert.match(launchStatus, /mode: launchMode\(\)/);
  assert.match(launchStatus, /billingOperationsReady/);
  assert.match(launchStatus, /renewalEnabled/);
  assert.match(webReadiness, /isProductionRuntime/);
  assert.match(ready, /productionWebRuntimeReleaseSha/);
  assert.match(ready, /pk_live_/);
  assert.match(ready, /sk_live_/);
  assert.match(ready, /PAID_CHECKOUT_PUBLIC_ENABLED/);
  assert.match(ready, /BILLING_REHEARSAL_USER_EMAIL/);
  assert.match(ready, /billingOperationsHeartbeat/);
  assert.match(ready, /FREE/);
  assert.match(ready, /BUSINESS/);
  assert.match(ready, /PRO/);
  assert.match(ready, /status: ready \? 200 : 503/);
  assert.match(audit, /sslmode=verify-full/);
  assert.match(audit, /DATABASE_URL must use sslmode=verify-full/);
  assert.match(audit, /deployment-scoped/);
  assert.doesNotMatch(audit, /PAID_CHECKOUT_PUBLIC_ENABLED must be true/);
  assert.doesNotMatch(audit, /BILLING_REHEARSAL_USER_EMAIL must be removed/);
  assert.doesNotMatch(workflow, /prisma db push/);
  assert.doesNotMatch(workflow, /prisma migrate deploy/);
  assert.doesNotMatch(workflow, /billing:renew/);
});
