"use client";

import Link from "next/link";
import { Suspense, useActionState, useState } from "react";
import { useSearchParams } from "next/navigation";
import { Eye, EyeOff, ShieldCheck } from "lucide-react";
import { IrLogo } from "../../components/brand/ir-logo";
import { resetPasswordAction } from "../actions/password-reset";

function PasswordInput({ name, label }: { name: string; label: string }) {
  const [visible, setVisible] = useState(false);
  return <div className="relative"><input name={name} type={visible ? "text" : "password"} autoComplete="new-password" required minLength={8} aria-label={label} className="h-12 w-full rounded-2xl border border-slate-200 bg-[#fbfdfd] px-4 ps-12 text-base outline-none transition focus:border-[#00a99d] focus:bg-white focus:ring-4 focus:ring-[#35e4cb]/10"/><button type="button" onClick={() => setVisible((value) => !value)} aria-label={visible ? `إخفاء ${label}` : `إظهار ${label}`} aria-pressed={visible} title={visible ? `إخفاء ${label}` : `إظهار ${label}`} className="absolute inset-y-1 start-1 grid w-10 place-items-center rounded-xl text-slate-500 transition hover:bg-slate-100 hover:text-[#008f87] focus:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-[#00bfae]">{visible ? <EyeOff className="h-5 w-5" aria-hidden="true" /> : <Eye className="h-5 w-5" aria-hidden="true" />}</button></div>;
}

function ResetPasswordContent() {
  const searchParams = useSearchParams();
  const token = searchParams.get("token") ?? "";
  const [state, action, pending] = useActionState(resetPasswordAction, {});
  return <main dir="rtl" className="min-h-screen bg-[radial-gradient(circle_at_80%_0%,rgba(53,228,203,.10),transparent_26rem),#f4f8f8] text-[#0a2426]"><div className="mx-auto flex min-h-screen w-full max-w-md flex-col justify-center px-4 py-8"><Link href="/" aria-label="العودة إلى INFRO" className="w-fit"><IrLogo className="h-12 w-auto" priority /></Link><section className="mt-6 rounded-[28px] border border-[#dfe9e8] bg-white p-5 shadow-[0_28px_80px_-58px_rgba(7,24,27,.65)] sm:p-7"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-[#e9fbf8] text-[#008f87]"><ShieldCheck className="h-5 w-5" aria-hidden="true" /></span><span className="mt-5 block text-[9px] font-black tracking-[.18em] text-[#008f87]" dir="ltr">SECURE PASSWORD RESET</span><h1 className="mt-1 text-2xl font-black">كلمة مرور جديدة</h1><p className="mt-1 text-sm leading-7 text-slate-500">استخدم كلمة قوية لا تستخدمها في حساب آخر.</p>{token ? <form action={action} className="mt-5 space-y-4" aria-label="تعيين كلمة مرور جديدة"><input type="hidden" name="token" value={token} /><label className="block"><span className="mb-1.5 block text-sm font-black">كلمة المرور الجديدة</span><PasswordInput name="password" label="كلمة المرور الجديدة" /></label><label className="block"><span className="mb-1.5 block text-sm font-black">تأكيد كلمة المرور</span><PasswordInput name="confirmPassword" label="تأكيد كلمة المرور" /></label><p className="rounded-xl bg-[#f4faf9] px-3 py-2 text-[11px] leading-6 text-slate-500">8 أحرف على الأقل، مع حرف كبير وصغير ورقم ورمز.</p>{state.error ? <p role="alert" aria-live="assertive" className="rounded-2xl border border-rose-200 bg-rose-50 px-3 py-2.5 text-sm font-bold text-rose-700">{state.error}</p> : null}<button disabled={pending} aria-busy={pending} className="h-12 w-full rounded-2xl bg-[#07181b] px-4 text-sm font-black text-white transition hover:bg-[#0d292d] focus-visible:ring-2 focus-visible:ring-[#00bfae] focus-visible:ring-offset-2 disabled:bg-slate-300">{pending ? "جاري التحديث..." : "تحديث كلمة المرور"}</button></form> : <div role="alert" className="mt-5 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm leading-7 text-amber-800">رابط الاستعادة غير مكتمل. اطلب رابطًا جديدًا من صفحة استعادة كلمة المرور.</div>}<p className="mt-5 border-t border-slate-100 pt-4 text-center text-sm text-slate-500"><Link href="/forgot-password" className="font-black text-[#008f87]">طلب رابط جديد</Link></p></section></div></main>;
}
export default function ResetPasswordPage() {return <Suspense fallback={<main className="min-h-screen bg-[#f4f8f8]" aria-label="تحميل صفحة إعادة تعيين كلمة المرور" />}><ResetPasswordContent /></Suspense>}
