import { Activity, Link2, MessageCircle, Megaphone, Users } from "lucide-react";
import { requireAdmin } from "../../lib/admin";
import { db } from "../../lib/db";

export default async function AdminWhatsAppPage() {
  await requireAdmin();
  const [connections, contacts, campaigns, messages, failedJobs, heartbeat, databaseClock, businesses] = await Promise.all([
    db.whatsAppConnection.count(), db.whatsAppContact.count(), db.whatsAppCampaign.count(), db.whatsAppMessage.count(),
    db.whatsAppDeliveryJob.count({ where: { status: "failed" } }),
    db.whatsAppOperationsHeartbeat.findUnique({ where: { id: "whatsapp-operations" }, select: { lastStartedAt: true, lastSucceededAt: true, lastFailedAt: true, releaseSha: true, lastErrorCode: true } }),
    db.$queryRaw<Array<{ currentTime: Date }>>`SELECT CURRENT_TIMESTAMP AS "currentTime"`,
    db.business.findMany({ where: { whatsappConnections: { some: {} }, deletedAt: null }, orderBy: { updatedAt: "desc" }, take: 100, select: { id: true, name: true, slug: true, plan: { select: { name: true, code: true } }, whatsappConnections: { select: { status: true, verifiedName: true, displayPhoneNumber: true } }, _count: { select: { whatsappContacts: true, whatsappCampaigns: true, whatsappMessages: true, whatsappDeliveryJobs: true } } } }),
  ]);
  const currentTime = databaseClock[0]?.currentTime;
  const workerHealthy = Boolean(heartbeat?.lastSucceededAt && currentTime && currentTime.getTime() - heartbeat.lastSucceededAt.getTime() < 20 * 60 * 1000 && !heartbeat.lastErrorCode);
  return <main dir="rtl" className="min-h-screen bg-[#f7f8fb] px-4 py-8 text-[#1f2552] sm:px-6"><div className="mx-auto max-w-7xl space-y-5"><header className="rounded-[26px] border bg-white p-5"><span className="text-xs font-black text-emerald-600">تشغيل المنصة</span><h1 className="mt-2 text-xl font-black">مركز WhatsApp Marketing</h1><p className="mt-1 text-sm text-slate-500">مراقبة قراءة فقط لحالة المنشآت والطوابير. لا تعرض هذه الصفحة رموز Meta أو نصوص الرسائل أو تمنح انتحال جلسة العميل.</p></header><section className={`rounded-[20px] border p-4 ${workerHealthy ? "border-emerald-200 bg-emerald-50" : "border-amber-200 bg-amber-50"}`}><div className="flex flex-wrap items-center justify-between gap-3"><div><span className="text-xs font-black">عامل WhatsApp: {workerHealthy ? "يعمل" : heartbeat ? "يحتاج فحصًا" : "لم يبدأ بعد"}</span><span className="mt-1 block text-[10px] text-slate-500">آخر نجاح: {heartbeat?.lastSucceededAt?.toLocaleString("ar-SA") || "—"} · آخر بدء: {heartbeat?.lastStartedAt.toLocaleString("ar-SA") || "—"}</span></div><span className="font-mono text-[10px] text-slate-500">{heartbeat?.releaseSha?.slice(0, 12) || "no-release"}{heartbeat?.lastErrorCode ? ` · ${heartbeat.lastErrorCode}` : ""}</span></div></section><section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Metric icon={<Link2 />} label="الاتصالات" value={connections} /><Metric icon={<Users />} label="جهات الاتصال" value={contacts} /><Metric icon={<Megaphone />} label="الحملات" value={campaigns} /><Metric icon={<MessageCircle />} label="الرسائل" value={messages} /><Metric icon={<Activity />} label="مهام فاشلة" value={failedJobs} danger={failedJobs > 0} /></section><section className="rounded-[24px] border bg-white p-4"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-right text-xs"><thead><tr className="border-b text-slate-400"><th className="p-2">المنشأة</th><th className="p-2">الباقة</th><th className="p-2">الرقم</th><th className="p-2">الحالة</th><th className="p-2">جهات الاتصال</th><th className="p-2">الحملات</th><th className="p-2">الرسائل</th><th className="p-2">مهام الإرسال</th></tr></thead><tbody>{businesses.map((business) => { const connection = business.whatsappConnections[0]; return <tr key={business.id} className="border-b last:border-0"><td className="p-2"><b>{business.name}</b><span className="block text-slate-400">ir.sa/{business.slug}</span></td><td className="p-2">{business.plan?.name || business.plan?.code || "Free"}</td><td className="p-2">{connection?.verifiedName || connection?.displayPhoneNumber || "—"}</td><td className="p-2 font-black text-emerald-700">{connection?.status || "—"}</td><td className="p-2">{business._count.whatsappContacts}</td><td className="p-2">{business._count.whatsappCampaigns}</td><td className="p-2">{business._count.whatsappMessages}</td><td className="p-2">{business._count.whatsappDeliveryJobs}</td></tr>; })}</tbody></table></div></section></div></main>;
}
function Metric({ icon, label, value, danger = false }: { icon: React.ReactNode; label: string; value: number; danger?: boolean }) { return <article className={`rounded-[20px] border bg-white p-4 ${danger ? "border-rose-200" : ""}`}><span className={`flex items-center gap-2 text-[10px] font-bold ${danger ? "text-rose-600" : "text-slate-400"}`}>{icon}{label}</span><b className="mt-1 block text-2xl">{value}</b></article>; }
