import { publishPlatformDesignAction, restorePlatformDesignAction, savePlatformDesignDraftAction } from "../../actions/admin-platform-design";
import { requireAdmin } from "../../lib/admin";
import { readPlatformDesign } from "../../lib/platform-design";

const Field=({label,name,value,type="text"}:{label:string;name:string;value:string;type?:string})=><label className="grid gap-1 text-xs font-bold text-slate-600"><span>{label}</span><input name={name} type={type} defaultValue={value} className="h-10 rounded-xl border border-slate-200 px-3 outline-none focus:border-[#00bfb4]" /></label>;
const Check=({label,name,value}:{label:string;name:string;value:boolean})=><label className="flex items-center gap-2 rounded-xl border border-slate-200 p-3 text-xs font-bold"><input name={name} type="checkbox" defaultChecked={value}/>{label}</label>;
export default async function DesignAdminPage(){await requireAdmin(); const {draft:d,publishedAt}=await readPlatformDesign(); return <main dir="rtl" className="min-h-screen bg-[#f6fbfc] px-4 py-8 text-[#0b1724]"><form className="mx-auto max-w-6xl space-y-5"><header className="rounded-[24px] border bg-white p-5"><p className="text-xs font-black text-[#00aebd]">INFRO CENTRAL DESIGN</p><h1 className="mt-2 text-2xl font-black">تصميم وهوية المنصة</h1><p className="mt-2 text-sm text-slate-500">تحكم مركزي في الهوية والألوان والهيدر والفوتر وصفحات العملاء وSEO. الحفظ كمسودة لا يغيّر الإنتاج حتى تضغط نشر.</p><p className="mt-2 text-xs text-slate-400">آخر نشر: {publishedAt?publishedAt.toLocaleString("ar-SA"):"لم يُنشر إعداد مخصص بعد"}</p></header>
<section className="grid gap-4 rounded-[24px] border bg-white p-5 md:grid-cols-2"><h2 className="md:col-span-2 font-black">الهوية والشعار</h2><Field label="الاسم العربي" name="brandNameAr" value={d.brandNameAr}/><Field label="الاسم الإنجليزي" name="brandNameEn" value={d.brandNameEn}/><Field label="رابط الشعار" name="logoUrl" value={d.logoUrl??""}/><Field label="شعار الخلفية الداكنة" name="logoDarkUrl" value={d.logoDarkUrl??""}/><Field label="Favicon" name="faviconUrl" value={d.faviconUrl??""}/><Field label="صورة المشاركة OG" name="ogImageUrl" value={d.ogImageUrl??""}/></section>
<section className="grid gap-4 rounded-[24px] border bg-white p-5 sm:grid-cols-2 lg:grid-cols-4"><h2 className="sm:col-span-2 lg:col-span-4 font-black">الألوان</h2>{[["الأساسي","primaryColor"],["الثانوي","secondaryColor"],["Accent","accentColor"],["الخلفية","backgroundColor"],["النص","foregroundColor"],["خلفية الهيدر","headerBackground"],["نص الهيدر","headerForeground"],["خلفية الفوتر","footerBackground"],["نص الفوتر","footerForeground"]].map(([l,n])=><Field key={n} label={l} name={n} value={String(d[n as keyof typeof d])} type="color"/>)}</section>
<section className="grid gap-4 rounded-[24px] border bg-white p-5 md:grid-cols-2"><h2 className="md:col-span-2 font-black">الهيدر والفوتر والصفحة الرئيسية</h2><Field label="نص زر الهيدر" name="headerCtaLabel" value={d.headerCtaLabel}/><Field label="رابط زر الهيدر" name="headerCtaHref" value={d.headerCtaHref}/><Field label="حقوق الفوتر" name="footerCopyright" value={d.footerCopyright}/><Field label="عنوان Hero" name="homeHeroTitleAr" value={d.homeHeroTitleAr}/><Field label="وصف Hero" name="homeHeroSubtitleAr" value={d.homeHeroSubtitleAr}/></section>
<section className="grid gap-4 rounded-[24px] border bg-white p-5 md:grid-cols-2"><h2 className="md:col-span-2 font-black">SEO</h2><Field label="عنوان SEO عربي" name="seoTitleAr" value={d.seoTitleAr}/><Field label="عنوان SEO إنجليزي" name="seoTitleEn" value={d.seoTitleEn}/><Field label="وصف SEO عربي" name="seoDescriptionAr" value={d.seoDescriptionAr}/><Field label="وصف SEO إنجليزي" name="seoDescriptionEn" value={d.seoDescriptionEn}/><label className="md:col-span-2 grid gap-1 text-xs font-bold"><span>الكلمات المفتاحية، مفصولة بفاصلة</span><input name="seoKeywords" defaultValue={d.seoKeywords.join(", ")} className="h-10 rounded-xl border px-3"/></label><Check label="السماح بالفهرسة" name="robotsIndex" value={d.robotsIndex}/><Check label="السماح بتتبع الروابط" name="robotsFollow" value={d.robotsFollow}/></section>
<section className="grid gap-3 rounded-[24px] border bg-white p-5 md:grid-cols-3"><h2 className="md:col-span-3 font-black">صفحات العملاء</h2><Check label="إظهار هوية INFRO" name="customerPageBrandingEnabled" value={d.customerPageBrandingEnabled}/><Check label="هيدر صفحات العملاء" name="customerHeaderEnabled" value={d.customerHeaderEnabled}/><Check label="فوتر صفحات العملاء" name="customerFooterEnabled" value={d.customerFooterEnabled}/></section>
<div className="sticky bottom-4 flex flex-wrap gap-2 rounded-2xl border bg-white/95 p-3 shadow-lg"><button formAction={savePlatformDesignDraftAction} className="rounded-xl border px-5 py-3 text-xs font-black">حفظ مسودة</button><button formAction={publishPlatformDesignAction} className="rounded-xl bg-[#00bfb4] px-5 py-3 text-xs font-black text-white">نشر التعديلات</button><button formAction={restorePlatformDesignAction} formNoValidate className="mr-auto rounded-xl bg-rose-50 px-5 py-3 text-xs font-black text-rose-700">استعادة هوية INFRO الافتراضية</button></div></form></main>}
