import { Prisma } from "@prisma/client";
import { AlertTriangle, BellRing, CalendarClock, CheckCircle2, CirclePause, Clock3, Mail, MessageCircleMore, NotebookPen, Repeat2, RotateCcw, ShieldCheck, Target, XCircle } from "lucide-react";
import Link from "next/link";
import { redirect } from "next/navigation";
import { cancelSmartReminderAction, completeSmartReminderAction, pauseSmartReminderAction, rescheduleSmartReminderAction, resumeSmartReminderAction, snoozeSmartReminderAction, updateSmartReminderAction, updateSmartReminderProgressAction } from "../../actions/smart-reminders";
import { getActiveBusinessForUser } from "../../lib/active-business";
import { getCurrentUser } from "../../lib/auth";
import { db } from "../../lib/db";
import { infroReminderWhatsAppReady } from "../../lib/reminders/platform-whatsapp";
import { reminderProgressLabel } from "../../lib/reminders/progress";
import { isSmartRemindersSchemaReady } from "../../lib/reminders/schema-readiness";
import { SmartReminderCreateForm } from "../../../components/dashboard/smart-reminder-create-form";

type DeliveryState = { channel:string; status:string; sentAt:string|null; deliveredAt:string|null; readAt:string|null; failedAt:string|null };
type ReminderRow = {
  id:string; title:string; body:string; timezone:string; scheduledAt:Date; nextOccurrenceAt:Date|null; recurrenceType:string; status:string; createdAt:Date;
  deliveryChannels:string[]; whatsappSenderMode:string; progressPercent:number; progressNote:string|null; progressUpdatedAt:Date|null; workCompletedAt:Date|null;
  businessNoteId:string|null; businessNoteTitle:string|null; deliveries:DeliveryState[]|null;
};

const statusLabel:Record<string,string>={scheduled:"قادم",paused:"متوقف مؤقتًا",completed:"انتهى التذكير",cancelled:"ملغى"};
const recurrenceLabel:Record<string,string>={once:"مرة واحدة",daily:"يوميًا",weekly:"أسبوعيًا",monthly:"شهريًا"};
const channelLabel:Record<string,string>={whatsapp:"واتساب",email:"البريد",in_app:"داخل INFRO"};
const progressPresets=[[0,"لم يبدأ"],[25,"منجز جزئيًا"],[50,"منجز نصفه"],[75,"أكثر من النصف"],[100,"منجز بالكامل"]] as const;

function dateText(value:Date,timezone:string){try{return new Intl.DateTimeFormat("ar-SA",{dateStyle:"medium",timeStyle:"short",timeZone:timezone}).format(value)}catch{return new Intl.DateTimeFormat("ar-SA",{dateStyle:"medium",timeStyle:"short",timeZone:"UTC"}).format(value)}}
function dateKey(value:Date,timezone:string){try{return new Intl.DateTimeFormat("en-CA",{year:"numeric",month:"2-digit",day:"2-digit",timeZone:timezone}).format(value)}catch{return""}}
function localInput(value:Date,timezone:string){try{const parts=Object.fromEntries(new Intl.DateTimeFormat("en-CA",{timeZone:timezone,year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(value).filter(p=>p.type!=="literal").map(p=>[p.type,p.value]));return`${parts.year}-${parts.month}-${parts.day}T${parts.hour}:${parts.minute}`}catch{return""}}
function masked(value:string|null){if(!value)return"رقم النشاط المسجل";const digits=value.replace(/\D/g,"");return digits.length>4?`•••• ${digits.slice(-4)}`:"رقم النشاط المسجل"}
function emailMasked(value:string){const[name,domain]=value.split("@");return domain?`${name.slice(0,2)}•••@${domain}`:"بريد الحساب"}
function parseDeliveries(value:DeliveryState[]|null){return Array.isArray(value)?value:[]}
function deliveryText(item:DeliveryState){
  if(item.status==="failed")return"لم يكتمل الإرسال";
  if(item.status==="delivery_unknown")return"جارٍ التحقق";
  if(item.status==="retry_scheduled")return"ستتم إعادة المحاولة";
  if(item.status==="queued"||item.status==="processing")return"بانتظار الإرسال";
  if(item.status==="cancelled")return"أُلغي الإرسال";
  if(item.channel==="whatsapp"&&item.readAt)return"تمت القراءة";
  if(item.channel==="whatsapp"&&item.deliveredAt)return"تم التسليم";
  if(item.channel==="in_app"&&item.status==="sent")return"تم إنشاء الإشعار";
  if(item.status==="sent")return"تم الإرسال";
  return"قيد المتابعة";
}
function Notice({params}:{params:Record<string,string|undefined>}){
  const values=Object.entries(params).filter(([,v])=>v);if(!values.length)return null;
  const success=values.some(([,v])=>v==="success"),busy=values.some(([,v])=>v==="busy"),progressInvalid=values.some(([,v])=>v==="progress-invalid"),progressLocked=values.some(([,v])=>v==="progress-locked");
  const text=success?"تم تحديث التذكير بنجاح.":busy?"التنبيه قيد الإرسال الآن؛ انتظر اكتماله قبل تعديل الموعد.":progressInvalid?"نسبة الإنجاز يجب أن تكون بين 0 و100.":progressLocked?"لا يمكن تعديل إنجاز تذكير ملغى.":values.some(([,v])=>v==="whatsapp-unavailable")?"قناة INFRO REMINDER غير مفعلة في هذه البيئة الآن. استخدم البريد أو إشعار INFRO.":"لم تكتمل العملية. بياناتك الحالية لم تتغير.";
  return <div role="status" className={`rounded-2xl border px-4 py-3 text-sm font-bold ${success?"border-emerald-200 bg-emerald-50 text-emerald-800":"border-amber-200 bg-amber-50 text-amber-900"}`}>{text}</div>;
}
function SchemaPending(){return <div dir="rtl" className="space-y-6 pb-10" data-reminder-schema="pending"><header className="rounded-[28px] bg-[#07181b] p-6 text-white"><p className="text-[10px] font-black tracking-[.16em] text-[#4ee7d4]">INFRO BUSINESS EXECUTION</p><h1 className="mt-3 text-2xl font-black">تذكيرات أعمالك الذكية</h1></header><section className="rounded-[24px] border border-slate-200 bg-white p-6 text-sm text-slate-600">يجري تجهيز تحديث مساحة التذكيرات بأمان.</section></div>}

export default async function SmartRemindersPage({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
  const user=await getCurrentUser();if(!user)redirect("/login");
  const business=await getActiveBusinessForUser(user.id);if(!business)redirect("/dashboard?business=required");
  const params=await searchParams;if(!await isSmartRemindersSchemaReady())return <SchemaPending/>;
  const reminders=await db.$queryRaw<ReminderRow[]>(Prisma.sql`
    SELECT r."id",r."title",r."body",r."timezone",r."scheduledAt",r."nextOccurrenceAt",r."recurrenceType",r."status",r."createdAt",r."deliveryChannels",r."whatsappSenderMode",
      r."progressPercent",r."progressNote",r."progressUpdatedAt",r."workCompletedAt",r."businessNoteId",n."title" AS "businessNoteTitle",COALESCE(ds."deliveries",'[]'::jsonb) AS "deliveries"
    FROM "SmartReminder" r
    LEFT JOIN "BusinessNote" n ON n."id"=r."businessNoteId" AND n."businessId"=r."businessId"
    LEFT JOIN LATERAL (
      SELECT jsonb_agg(jsonb_build_object('channel',x."channel",'status',x."status",'sentAt',x."sentAt",'deliveredAt',x."deliveredAt",'readAt',x."readAt",'failedAt',x."failedAt") ORDER BY x."channel") AS "deliveries"
      FROM (
        SELECT DISTINCT ON ("channel") "channel","status","sentAt","deliveredAt","readAt","failedAt"
        FROM "SmartReminderDelivery"
        WHERE "businessId"=r."businessId" AND "reminderId"=r."id"
        ORDER BY "channel","occurrenceAt" DESC,"updatedAt" DESC,"createdAt" DESC
      ) x
    ) ds ON TRUE
    WHERE r."businessId"=${business.id}
    ORDER BY COALESCE(r."nextOccurrenceAt",r."scheduledAt") ASC,r."createdAt" DESC LIMIT 200
  `);
  const whatsAppAvailable=infroReminderWhatsAppReady()&&Boolean(business.whatsapp||business.phone),now=new Date(),todayKeys=new Map<string,string>();
  const occurrence=(r:ReminderRow)=>r.nextOccurrenceAt??r.scheduledAt;
  const isToday=(r:ReminderRow)=>{if(!todayKeys.has(r.timezone))todayKeys.set(r.timezone,dateKey(now,r.timezone));return dateKey(occurrence(r),r.timezone)===todayKeys.get(r.timezone)};
  const isOverdue=(r:ReminderRow)=>r.status==="scheduled"&&Boolean(r.nextOccurrenceAt)&&occurrence(r).getTime()<now.getTime();
  const needsAttention=(r:ReminderRow)=>parseDeliveries(r.deliveries).some(d=>["failed","delivery_unknown"].includes(d.status));
  const workOpen=(r:ReminderRow)=>r.progressPercent<100&&r.status!=="cancelled";
  const allowed=["today","upcoming","overdue","paused","attention","work","completed","cancelled"],tab=allowed.includes(params.tab??"")?params.tab!:"upcoming";
  const filtered=reminders.filter(r=>tab==="today"?["scheduled","paused"].includes(r.status)&&isToday(r):tab==="overdue"?isOverdue(r):tab==="paused"?r.status==="paused":tab==="attention"?needsAttention(r):tab==="work"?workOpen(r):tab==="completed"?r.progressPercent===100:tab==="cancelled"?r.status==="cancelled":r.status==="scheduled"&&!isOverdue(r));
  const counts={today:reminders.filter(r=>["scheduled","paused"].includes(r.status)&&isToday(r)).length,upcoming:reminders.filter(r=>r.status==="scheduled"&&!isOverdue(r)).length,overdue:reminders.filter(isOverdue).length,paused:reminders.filter(r=>r.status==="paused").length,attention:reminders.filter(needsAttention).length,work:reminders.filter(workOpen).length,completed:reminders.filter(r=>r.progressPercent===100).length,cancelled:reminders.filter(r=>r.status==="cancelled").length};
  const tabs=[["today","اليوم"],["upcoming","القادمة"],["work","قيد الإنجاز"],["overdue","المتأخرة"],["attention","تحتاج مراجعة"],["paused","المتوقفة"],["completed","منجزة"],["cancelled","الملغاة"]] as const;

  return <div dir="rtl" className="space-y-6 pb-10">
    <header className="relative overflow-hidden rounded-[28px] border border-slate-200 bg-[#07181b] p-6 text-white shadow-sm sm:p-7"><div className="absolute -left-20 -top-24 h-64 w-64 rounded-full bg-[#00d8c6]/15 blur-3xl"/><div className="relative flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><div className="mb-3 flex items-center gap-2 text-[10px] font-black tracking-[.16em] text-[#4ee7d4]"><Target className="h-4 w-4"/>INFRO BUSINESS EXECUTION</div><h1 className="text-2xl font-black sm:text-3xl">تذكيرات أعمالك الذكية</h1><p className="mt-2 max-w-2xl text-sm leading-7 text-slate-300">ليس مجرد تنبيه: تابع تنفيذ العمل، سجل ما أُنجز وما بقي، وافصل بين وصول التذكير ونسبة إنجاز المهمة الفعلية.</p></div><div className="flex flex-wrap gap-2"><Link href="/dashboard/notifications" className="rounded-2xl border border-white/10 bg-white/5 px-4 py-3 text-xs font-bold text-[#a8f2e8]">مركز الإشعارات</Link><div className="flex items-center gap-2 rounded-2xl border border-white/10 bg-white/5 px-4 py-3 text-xs font-bold text-[#a8f2e8]"><ShieldCheck className="h-4 w-4"/>خاصة بالمنشأة النشطة</div></div></div></header>
    <Notice params={params}/>
    {counts.attention>0||counts.overdue>0?<section className="rounded-[24px] border border-amber-200 bg-amber-50 p-5 text-amber-950"><div className="flex items-start gap-3"><AlertTriangle className="mt-0.5 h-5 w-5"/><div><p className="font-black">لوحة متابعة التنفيذ تحتاج انتباهك</p><p className="mt-1 text-sm leading-7">{counts.overdue} تذكير متأخر و{counts.attention} حالة إرسال تحتاج مراجعة. الإنجاز الفعلي محفوظ بشكل مستقل عن حالة التنبيه.</p></div></div></section>:null}
    <section className="rounded-[26px] border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="mb-5 flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-[#e9fbf8] text-[#009d93]"><CalendarClock className="h-5 w-5"/></div><div><h2 className="font-black text-slate-900">إضافة تذكير عمل</h2><p className="mt-1 text-xs text-slate-500">اختر الموعد والقنوات ثم تابع الإنجاز من 0% إلى 100%.</p></div></div><SmartReminderCreateForm recipientLabel={masked(business.whatsapp??business.phone??null)} emailLabel={emailMasked(user.email)} whatsAppAvailable={whatsAppAvailable}/>{!whatsAppAvailable?<p className="mt-4 rounded-2xl border border-sky-200 bg-sky-50 p-4 text-xs leading-6 text-sky-900"><b>واتساب INFRO REMINDER غير مفعل في هذه البيئة بعد.</b> البريد وإشعار INFRO يعملان بشكل مستقل.</p>:null}</section>
    <nav aria-label="حالات التذكيرات" className="grid grid-cols-2 gap-2 rounded-[22px] border border-slate-200 bg-white p-2 shadow-sm sm:grid-cols-4 xl:grid-cols-8">{tabs.map(([key,label])=><Link key={key} href={`/dashboard/reminders?tab=${key}`} className={`rounded-2xl px-3 py-3 text-center text-xs font-black ${tab===key?"bg-[#07181b] text-white":"text-slate-500 hover:bg-slate-50"}`}>{label}<span className={`mr-2 rounded-full px-2 py-0.5 text-[10px] ${tab===key?"bg-white/10":"bg-slate-100"}`}>{counts[key]}</span></Link>)}</nav>
    <section className="space-y-3">{filtered.map(reminder=>{const displayOccurrence=occurrence(reminder),overdue=isOverdue(reminder),attention=needsAttention(reminder),deliveries=parseDeliveries(reminder.deliveries);return <article key={reminder.id} className={`rounded-[24px] border bg-white p-5 shadow-sm ${attention?"border-amber-300":overdue?"border-rose-200":"border-slate-200"}`}>
      <div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="text-base font-black text-slate-900">{reminder.title}</h3><span className="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-black text-slate-600">{overdue?"متأخر":statusLabel[reminder.status]??reminder.status}</span><span className="rounded-full bg-[#edfafa] px-2.5 py-1 text-[10px] font-black text-[#007f78]"><Repeat2 className="ml-1 inline h-3 w-3"/>{recurrenceLabel[reminder.recurrenceType]??reminder.recurrenceType}</span></div><p className="mt-2 whitespace-pre-wrap text-sm leading-7 text-slate-600">{reminder.body}</p><div className="mt-3 flex flex-wrap gap-3 text-xs font-bold text-slate-500"><span className="inline-flex items-center gap-1"><Clock3 className="h-3.5 w-3.5"/>{dateText(displayOccurrence,reminder.timezone)}</span>{reminder.businessNoteId?<Link href={`/dashboard/notes?q=${encodeURIComponent(reminder.businessNoteTitle??"")}`} className="inline-flex items-center gap-1 text-[#008f87]"><NotebookPen className="h-3.5 w-3.5"/>المذكرة المرتبطة</Link>:null}</div></div>{["scheduled","paused"].includes(reminder.status)?<div className="flex shrink-0 flex-wrap gap-2">{reminder.status==="scheduled"&&reminder.nextOccurrenceAt?<form action={pauseSmartReminderAction}><input type="hidden" name="reminderId" value={reminder.id}/><button className="rounded-xl border border-slate-200 px-3 py-2 text-xs font-black"><CirclePause className="ml-1 inline h-3.5 w-3.5"/>إيقاف</button></form>:null}{reminder.status==="paused"?<form action={resumeSmartReminderAction}><input type="hidden" name="reminderId" value={reminder.id}/><button className="rounded-xl border border-slate-200 px-3 py-2 text-xs font-black"><RotateCcw className="ml-1 inline h-3.5 w-3.5"/>استئناف</button></form>:null}<form action={completeSmartReminderAction}><input type="hidden" name="reminderId" value={reminder.id}/><button className="rounded-xl border border-slate-200 px-3 py-2 text-xs font-black">إنهاء التذكير</button></form><form action={cancelSmartReminderAction}><input type="hidden" name="reminderId" value={reminder.id}/><button className="rounded-xl border border-rose-200 px-3 py-2 text-xs font-black text-rose-700"><XCircle className="ml-1 inline h-3.5 w-3.5"/>إلغاء</button></form></div>:null}</div>
      <div className="mt-5 rounded-2xl border border-slate-200 bg-slate-50 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-black text-slate-900">إنجاز العمل · {reminderProgressLabel(reminder.progressPercent)}</p><p className="mt-1 text-[11px] text-slate-500">هذا المؤشر يعبّر عن تنفيذ المهمة، وليس عن وصول رسالة التذكير.</p></div><span className="text-xl font-black text-[#008f87]">{reminder.progressPercent}%</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-200"><div className="h-full rounded-full bg-[#00bfae]" style={{width:`${reminder.progressPercent}%`}}/></div>{reminder.progressNote?<p className="mt-3 rounded-xl bg-white p-3 text-xs leading-6 text-slate-600"><b>آخر تحديث:</b> {reminder.progressNote}</p>:null}{reminder.status!=="cancelled"?<form action={updateSmartReminderProgressAction} className="mt-4 grid gap-3 lg:grid-cols-[1fr_2fr_auto]"><input type="hidden" name="reminderId" value={reminder.id}/><select name="progressPercent" defaultValue={String(reminder.progressPercent)} aria-label="نسبة إنجاز العمل" className="min-h-11 rounded-xl border border-slate-200 bg-white px-3 text-sm font-bold">{progressPresets.map(([value,label])=><option key={value} value={value}>{value}% · {label}</option>)}</select><input name="progressNote" defaultValue={reminder.progressNote??""} maxLength={1000} placeholder="ما الذي تم؟ وما الخطوة المتبقية؟" className="min-h-11 rounded-xl border border-slate-200 bg-white px-3 text-sm"/><button className="min-h-11 rounded-xl bg-[#07181b] px-4 text-xs font-black text-white">تحديث الإنجاز</button></form>:null}</div>
      <div className="mt-4 grid gap-2 sm:grid-cols-3">{reminder.deliveryChannels.map(channel=>{const state=deliveries.find(d=>d.channel===channel);return <div key={channel} className="rounded-2xl border border-slate-200 p-3"><div className="flex items-center gap-2 text-xs font-black text-slate-800">{channel==="whatsapp"?<MessageCircleMore className="h-4 w-4 text-[#009d93]"/>:channel==="email"?<Mail className="h-4 w-4 text-[#009d93]"/>:<BellRing className="h-4 w-4 text-[#009d93]"/>}{channel==="whatsapp"&&reminder.whatsappSenderMode==="platform"?"واتساب · INFRO REMINDER":channelLabel[channel]??channel}</div><p className={`mt-2 text-[11px] font-bold ${state&&["failed","delivery_unknown"].includes(state.status)?"text-amber-800":"text-slate-500"}`}>{state?deliveryText(state):"لم يحِن موعد الإرسال"}</p></div>})}</div>
      {attention?<p className="mt-4 rounded-2xl border border-amber-200 bg-amber-50 p-3 text-xs leading-6 text-amber-950"><b>يحتاج مراجعة:</b> تحقق من قناة الاستقبال أو أعد الجدولة. لن نعرض رموز الأخطاء التقنية في مساحة العميل.</p>:null}
      {["scheduled","paused"].includes(reminder.status)?<details className="mt-4 border-t border-slate-100 pt-4"><summary className="cursor-pointer text-xs font-black text-[#008f87]">تعديل أو إعادة جدولة</summary><div className="mt-4 grid gap-4 lg:grid-cols-2"><form action={updateSmartReminderAction} className="space-y-3 rounded-2xl bg-slate-50 p-4"><input type="hidden" name="reminderId" value={reminder.id}/><input name="title" defaultValue={reminder.title} required maxLength={160} className="w-full rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm"/><textarea name="body" defaultValue={reminder.body} required maxLength={2000} rows={3} className="w-full rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm"/><button className="rounded-xl bg-[#07181b] px-4 py-2 text-xs font-black text-white">حفظ التعديل</button></form><div className="space-y-3 rounded-2xl bg-slate-50 p-4"><form action={rescheduleSmartReminderAction} className="space-y-3"><input type="hidden" name="reminderId" value={reminder.id}/><input type="hidden" name="timezone" value={reminder.timezone}/><input type="datetime-local" name="scheduledLocal" required defaultValue={localInput(displayOccurrence,reminder.timezone)} className="w-full rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm"/><button className="rounded-xl bg-[#07181b] px-4 py-2 text-xs font-black text-white">إعادة الجدولة</button></form><div className="flex flex-wrap gap-2">{[[10,"10 دقائق"],[30,"30 دقيقة"],[60,"ساعة"],[1440,"غدًا"]].map(([minutes,label])=><form action={snoozeSmartReminderAction} key={minutes}><input type="hidden" name="reminderId" value={reminder.id}/><input type="hidden" name="minutes" value={minutes}/><button className="rounded-xl border border-slate-200 bg-white px-3 py-2 text-[10px] font-black">{label}</button></form>)}</div></div></div></details>:null}
    </article>})}{!filtered.length?<div className="rounded-[24px] border border-dashed border-slate-300 bg-white px-5 py-12 text-center"><CheckCircle2 className="mx-auto h-7 w-7 text-slate-300"/><p className="mt-3 text-sm font-black text-slate-700">لا توجد تذكيرات في هذه الحالة</p></div>:null}</section>
  </div>;
}
