"use client";
import { useState, useTransition } from "react";
import { Bot, FlaskConical, Plus, Trash2, Save } from "lucide-react";
import { DEFAULT_BOT_CONFIG, type BotConfig } from "../../../lib/whatsapp/bot-domain";
import { saveBotAction, previewBotAction } from "./actions";

export function BotEditor({ connections, initial, aiReady, storageReady }: { connections: { id: string; label: string }[]; initial: { connectionId: string; config: BotConfig; enabled: boolean }[]; aiReady: boolean; storageReady: boolean }) {
  const [connectionId, setConnectionId] = useState(connections[0]?.id ?? "");
  const first = initial.find(b => b.connectionId === connections[0]?.id);
  const [config, setConfig] = useState(first?.config ?? DEFAULT_BOT_CONFIG);
  const [enabled, setEnabled] = useState(first?.enabled ?? false);
  const [acknowledged, setAcknowledged] = useState(false);
  const [notice, setNotice] = useState("");
  const [question, setQuestion] = useState("");
  const [answer, setAnswer] = useState("");
  const [pending, startTransition] = useTransition();
  const update = <K extends keyof BotConfig>(key: K, value: BotConfig[K]) => setConfig(current => ({ ...current, [key]: value }));
  return <div className="wa-split"><form className="wa-panel wa-stack" onSubmit={event => { event.preventDefault(); startTransition(async () => { const result = await saveBotAction(config, connectionId, enabled, acknowledged); setNotice(result.error ?? result.success ?? ""); }); }}>
    <h2><Bot size={22}/> إعداد مساعد المنشأة</h2>
    <label>رقم واتساب<select aria-label="رقم واتساب" value={connectionId} disabled={pending} onChange={event => { const id = event.target.value, bot = initial.find(item => item.connectionId === id); setConnectionId(id); setConfig(bot?.config ?? DEFAULT_BOT_CONFIG); setEnabled(bot?.enabled ?? false); setAcknowledged(false); setNotice(""); setAnswer(""); }}>{connections.map(c => <option key={c.id} value={c.id}>{c.label}</option>)}</select></label>
    <label>اسم البوت<input value={config.name} maxLength={80} required onChange={event => update("name", event.target.value)}/></label>
    <label>طريقة الرد<select value={config.mode} onChange={event => update("mode", event.target.value as BotConfig["mode"])}><option value="rules">أسئلة وأجوبة ثابتة</option><option value="ai">ذكاء اصطناعي من معرفة المنشأة</option></select></label>
    {config.mode === "ai" ? <><p className="wa-notice">{aiReady ? "مزود الذكاء الاصطناعي جاهز." : "مزود الذكاء الاصطناعي يحتاج إعداد مسؤول المنصة قبل التشغيل."} تُرسل معرفة المنشأة والسؤال الحالي إلى OpenAI لصياغة الرد.</p><label>معرفة المنشأة<textarea rows={8} value={config.knowledge} maxLength={8000} minLength={30} required placeholder="ساعات العمل، الخدمات، سياسة الاستبدال، طرق التواصل…" onChange={event => update("knowledge", event.target.value)}/><small>{config.knowledge.length} / 8000 · استخدم معلومات معتمدة وحدّثها عند التغيير.</small></label></> : <p className="wa-note">يرد البوت عند مطابقة السؤال بعد توحيد الكتابة. الأسئلة الأخرى تتحول إلى الفريق.</p>}
    <div className="wa-section-title"><h3>الأسئلة المعتمدة</h3><button type="button" className="wa-button wa-secondary" disabled={config.rules.length >= 30} onClick={() => update("rules", [...config.rules, { question: "", answer: "" }])}><Plus size={16}/>إضافة سؤال</button></div>
    {config.rules.map((rule, index) => <fieldset className="wa-panel wa-stack" key={index}><legend>سؤال {index+1}</legend><label>السؤال<input value={rule.question} maxLength={160} required onChange={event => update("rules", config.rules.map((r, i) => i === index ? { ...r, question: event.target.value } : r))}/></label><label>الإجابة<textarea value={rule.answer} maxLength={2000} rows={3} required onChange={event => update("rules", config.rules.map((r, i) => i === index ? { ...r, answer: event.target.value } : r))}/></label><button className="wa-button wa-secondary" type="button" aria-label={`حذف سؤال ${index+1}`} onClick={() => update("rules", config.rules.filter((_, i) => i !== index))}><Trash2 size={16}/>حذف</button></fieldset>)}
    <label>رسالة التحويل للفريق<textarea rows={2} value={config.handoffText} maxLength={500} required onChange={event => update("handoffText", event.target.value)}/></label>
    <label>الحد اليومي للمعالجة لكل رقم<input type="number" min={1} max={100} value={config.dailyLimit} required onChange={event => update("dailyLimit", Number(event.target.value))}/><small>حتى 100 رسالة جديدة يوميًا؛ يبدأ اليوم بتوقيت UTC. المحاولات غير المكتملة تُحتسب أيضًا.</small></label>
    <label className="wa-check"><input type="checkbox" checked={enabled} onChange={event => { setEnabled(event.target.checked); setAcknowledged(false); }}/>تشغيل الردود التلقائية للرسائل الجديدة</label>
    {enabled ? <label className="wa-check"><input type="checkbox" checked={acknowledged} required onChange={event => setAcknowledged(event.target.checked)}/>أوافق على إرسال ردود آلية من هذا الرقم، ومعالجة السؤال عبر مزود الذكاء الاصطناعي عند اختياره.</label> : null}
    <button className="wa-button" disabled={pending || !storageReady || !connectionId}><Save size={17}/>{pending ? "جارٍ الحفظ…" : "حفظ الإعدادات"}</button><p role="status" aria-live="polite">{notice}</p>
  </form><aside className="wa-stack"><section className="wa-panel wa-stack"><h2><FlaskConical size={21}/>جرّب قبل التشغيل</h2><p className="wa-note">هذه تجربة داخل اللوحة ولا تُرسل رسالة واتساب. أدخل سؤالًا تجريبيًا دون بيانات عملاء حساسة.</p><label>سؤال التجربة<textarea rows={4} maxLength={2000} value={question} onChange={event => setQuestion(event.target.value)}/></label><button className="wa-button wa-secondary" disabled={pending || !question.trim()} onClick={() => startTransition(async () => { const result = await previewBotAction(config, question); setAnswer("error" in result ? result.error ?? "تعذرت التجربة" : `${result.reply}${result.handoff ? "\n\nسيُوقف البوت لهذه المحادثة ويتركها للفريق." : ""}`); })}>اختبار الرد</button>{answer ? <div role="status" className="wa-bot-answer">{answer}</div> : null}</section><section className="wa-panel wa-stack"><h2>متى يتوقف البوت؟</h2><p className="wa-note">عند طلب موظف، أو غياب الإجابة، أو إسناد المحادثة لموظف. ويتحقق من قائمة المنع ونافذة خدمة العميل قبل الإرسال.</p><p className="wa-note">الردود لا تنفذ حجوزات أو استرداد مبالغ ولا تطلع على بيانات الطلبات. يعرض الفريق المحادثات المحالة أدناه.</p><p className="wa-note">يتطلب وصول الرسائل وتشغيل الردود اتصال Meta والعامل التشغيلي. رسالة قبلتها Meta بالفعل قد تصل بعد إيقاف البوت.</p></section></aside></div>;
}
