"use client";
import { useState } from "react";
import { useFormStatus } from "react-dom";
import { removeWhatsAppContactsAction } from "../../../actions/whatsapp-marketing";

export function ContactRemovalControls({ contacts, total, importing }: { contacts: Array<{ id: string; displayName: string | null; phoneE164: string }>; total: number; importing: boolean }) {
  const [selected, setSelected] = useState<string[]>([]);
  const [scope, setScope] = useState<"all" | "selected" | null>(null);
  const [expanded, setExpanded] = useState(false);
  const [confirmation, setConfirmation] = useState("");
  const count = scope === "all" ? total : selected.length;
  return <section className="mt-5 rounded-2xl border border-slate-200 bg-slate-50 p-4">
    <h3 className="font-bold text-slate-900">إدارة وحذف جهات الاتصال</h3>
    <p className="mt-2 text-xs leading-6 text-slate-600">الحذف يزيل الجهة من الجمهور والشرائح ويمنع إرسال الحملات الجديدة لها. نحتفظ بسجل الحملات والرسائل السابقة؛ هذا ليس محوًا لسجل العمليات. لا يعيد الاستيراد التلقائي الجهات المحذوفة إلى الجمهور.</p>
    {importing ? <p role="status" className="mt-2 text-sm text-slate-700">انتظر اكتمال الاستيراد الجاري قبل الحذف.</p> : null}
    <div className="mt-3 flex flex-wrap gap-2"><button type="button" disabled={importing || !contacts.length} onClick={() => setExpanded(!expanded)} className="min-h-11 rounded-xl border border-slate-200 bg-white px-4 text-sm text-slate-900 disabled:opacity-50">تحديد جهات للحذف</button><button type="button" disabled={importing || !total} onClick={() => { setScope("all"); setConfirmation(""); }} className="min-h-11 rounded-xl border border-rose-300 bg-white px-4 text-sm font-bold text-rose-700 disabled:opacity-50">حذف جميع جهات الاتصال ({total})</button></div>
    {expanded ? <fieldset className="mt-4 space-y-2"><legend className="text-sm font-bold text-slate-900">تحديد من نتائج البحث الحالية</legend><label className="flex min-h-11 items-center gap-2 text-sm text-slate-900"><input type="checkbox" checked={contacts.length > 0 && selected.length === contacts.length} onChange={event => { setSelected(event.target.checked ? contacts.map(c => c.id) : []); setScope(null); }}/>تحديد كل النتائج المعروضة ({contacts.length})</label><div className="max-h-64 overflow-y-auto rounded-xl border border-slate-200 bg-white p-2">{contacts.map(contact => <label key={contact.id} className="flex min-h-12 items-center gap-3 border-b border-slate-100 px-2 text-sm text-slate-900 last:border-0"><input type="checkbox" checked={selected.includes(contact.id)} onChange={event => { setSelected(old => event.target.checked ? [...old, contact.id] : old.filter(id => id !== contact.id)); setScope(null); }}/><span className="min-w-0">{contact.displayName || "بدون اسم"}<span dir="ltr" className="block text-xs text-slate-600">{contact.phoneE164}</span></span></label>)}</div><button type="button" disabled={!selected.length || importing} onClick={() => { setScope("selected"); setConfirmation(""); }} className="min-h-11 rounded-xl border border-rose-300 bg-white px-4 text-sm font-bold text-rose-700 disabled:opacity-50">حذف المحدد ({selected.length})</button></fieldset> : null}
    {scope ? <form action={removeWhatsAppContactsAction} className="mt-4 space-y-3 rounded-xl border border-rose-200 bg-white p-4"><input type="hidden" name="scope" value={scope}/><input type="hidden" name="expectedCount" value={count}/>{scope === "selected" ? selected.map(id => <input key={id} type="hidden" name="contactId" value={id}/>) : null}<p className="text-sm font-bold text-slate-900">{scope === "all" ? `سيتم حذف جميع جهات منشأتك (${count})، وليس نتائج البحث فقط.` : `سيتم حذف ${count} جهة محددة.`}</p><p className="text-xs leading-6 text-slate-600">تُلغى الرسائل التسويقية المنتظرة لهذه الجهات. الرسائل الجاري إرسالها بالفعل قد تصل.</p><label className="block text-sm text-slate-900">اكتب «حذف» للتأكيد<input name="confirmation" autoComplete="off" value={confirmation} onChange={event => setConfirmation(event.target.value)} className="mt-2 block min-h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-slate-900"/></label><div className="flex gap-2"><RemoveSubmit ready={confirmation === "حذف" && !importing}/><button type="button" onClick={() => setScope(null)} className="min-h-11 rounded-xl border border-slate-200 px-4 text-sm text-slate-900">تراجع</button></div></form> : null}
  </section>;
}
function RemoveSubmit({ ready }: { ready: boolean }) { const { pending } = useFormStatus(); return <button type="submit" disabled={!ready || pending} className="min-h-11 rounded-xl bg-rose-700 px-4 text-sm font-bold text-white disabled:opacity-50">{pending ? "جارٍ الحذف…" : "تأكيد حذف جهات الاتصال"}</button>; }
