import Link from "next/link";
import { redirect } from "next/navigation";
import { CheckCircle2, ContactRound, FileSpreadsheet, ShieldAlert, UploadCloud } from "lucide-react";
import { importWhatsAppContactsAction, retryWhatsAppContactImportAction } from "../../../actions/whatsapp-marketing";
import { db } from "../../../lib/db";
import { hasActiveWhatsAppMarketingEntitlement } from "../../../lib/whatsapp/feature-entitlement";
import { getWhatsAppReadContext } from "../../../lib/whatsapp/rbac";
import { ImportProgressRefresh } from "./import-progress-refresh";

const buttonFocus = "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#00bfae] focus-visible:ring-offset-2";

export default async function WhatsAppContactsPage({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  const context = await getWhatsAppReadContext("campaign.manage");
  if (!context) redirect("/dashboard/whatsapp?access=denied");
  if (!await hasActiveWhatsAppMarketingEntitlement({ businessId: context.businessId })) redirect("/dashboard/billing/manage?feature=whatsapp-marketing");
  const params = await searchParams;
  const [contacts, imports, contactCount, consentCount, optOutCount] = await Promise.all([
    db.whatsAppContact.findMany({ where: { businessId: context.businessId }, orderBy: { createdAt: "desc" }, take: 100, select: { id: true, displayName: true, phoneE164: true, email: true, source: true, optedOutAt: true, createdAt: true } }),
    db.whatsAppContactImport.findMany({ where: { businessId: context.businessId }, orderBy: { createdAt: "desc" }, take: 10, select: { id: true, fileName: true, status: true, totalRows: true, importedRows: true, duplicateRows: true, rejectedRows: true, createdAt: true } }),
    db.whatsAppContact.count({ where: { businessId: context.businessId } }),
    db.whatsAppConsent.count({ where: { businessId: context.businessId, revokedAt: null } }),
    db.whatsAppContact.count({ where: { businessId: context.businessId, optedOutAt: { not: null } } }),
  ]);
  const hasActiveImport = imports.some((item) => item.status === "queued" || item.status === "processing");

  return <div className="space-y-5 pb-5">
    <ImportProgressRefresh active={hasActiveImport} />
    <header className="relative overflow-hidden rounded-[28px] border border-slate-200 bg-white p-5 sm:p-6"><div className="absolute -left-16 -top-20 h-48 w-48 rounded-full bg-[#c9f8f0]/80 blur-3xl"/><div className="relative"><p className="flex items-center gap-1.5 text-[9px] font-black tracking-[.16em] text-[#008f87]" dir="ltr"><ContactRound className="h-3.5 w-3.5"/>AUDIENCE & CONSENT</p><h1 className="mt-2 text-2xl font-black">جهات اتصال واتساب</h1><p className="mt-2 max-w-3xl text-xs leading-6 text-slate-500">استورد CSV أو Excel حتى 10,000 صف، مع إزالة التكرار وتوثيق الموافقة التسويقية وحماية Opt-out.</p></div></header>

    {params.import === "queued" ? <Notice ok text="تم قبول الملف وبدأت معالجته. ستظهر النتيجة تلقائيًا عند اكتمال الاستيراد." /> : params.import === "existing" ? <Notice ok text="هذا الملف مسجل مسبقًا لنشاطك؛ نعرض لك العملية الحالية بدل إنشاء نسخة مكررة." /> : params.import ? <Notice text="تعذر استيراد الملف. تحقق من النوع والعناوين وأرقام الجوال ثم حاول مرة أخرى." /> : null}
    {params.retry === "queued" ? <Notice ok text="بدأت إعادة معالجة السجلات التي تعذر استيرادها، وستظهر النتيجة تلقائيًا." /> : params.retry ? <Notice text="تعذرت إعادة المعالجة؛ قد تكون العملية ما زالت جارية أو لم تعد قابلة للإعادة." /> : null}

    <section className="grid gap-5 lg:grid-cols-[1.1fr_.9fr]">
      <form id="import-contacts" action={importWhatsAppContactsAction} className="rounded-[26px] border border-slate-200 bg-white p-5"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#e9fbf8] text-[#008f87]"><FileSpreadsheet className="h-4 w-4"/></span><div><h2 className="font-black">استيراد ملف جهات الاتصال</h2><p className="text-[9px] text-slate-400">CSV / XLSX · MAX 5MB</p></div></div><p className="mt-4 text-[10px] leading-6 text-slate-500">استخدم عمودًا باسم <b>phone</b> أو <b>رقم الجوال</b>. الاسم والبريد والوسوم اختيارية.</p><label className={`mt-4 grid cursor-pointer place-items-center rounded-[18px] border border-dashed border-[#9fded6] bg-[#f5fffd] p-6 text-center transition hover:border-[#62cfc4] ${buttonFocus}`}><UploadCloud className="h-6 w-6 text-[#008f87]"/><span className="mt-2 text-[10px] font-black text-slate-700">اختر ملف CSV أو Excel</span><input name="file" type="file" required accept=".csv,.xlsx,text/csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" className="mt-3 block max-w-full text-[10px] text-slate-500" /></label><label className="mt-4 flex items-start gap-2 rounded-2xl border border-amber-200 bg-amber-50 p-3 text-[10px] leading-6 text-amber-900"><input name="explicitConsent" type="checkbox" className="mt-1 h-4 w-4 accent-[#008f87]"/><span><b>تأكيد الموافقة التسويقية:</b> جميع الأرقام في الملف وافقت صراحة على استلام الرسائل ويمكنني إثبات ذلك. وجود علاقة عميل سابقة وحده لا يكفي.</span></label><label className="mt-3 block text-[10px] font-bold text-slate-600">دليل الموافقة <span className="font-normal text-slate-400">(موصى به عند تأكيد الموافقة)</span><textarea name="consentEvidence" maxLength={500} rows={2} placeholder="مثال: نموذج اشتراك حملة رمضان بتاريخ ..." className="mt-1.5 w-full rounded-xl border border-slate-200 bg-slate-50/60 px-3 py-2 text-xs outline-none transition focus:border-[#8ddfd6] focus:ring-2 focus:ring-[#00bfae]/10"/></label><button type="submit" className={`mt-3 min-h-11 rounded-xl bg-[#07181b] px-5 text-xs font-black text-white transition hover:bg-[#0d2a2e] ${buttonFocus}`}>فحص الملف واستيراده</button></form>
      <div className="space-y-3"><div className="grid grid-cols-3 gap-2"><Stat label="إجمالي الجهات" value={contactCount}/><Stat label="موافقة فعالة" value={consentCount}/><Stat label="Opt-out" value={optOutCount}/></div><div className="rounded-[22px] border border-rose-100 bg-rose-50/70 p-4 text-[10px] leading-6 text-rose-900"><ShieldAlert className="mb-2 h-5 w-5"/><b className="block">حماية موافقة المستلمين</b><span className="mt-1 block">من ألغى الاشتراك أو سحب موافقته يبقى محفوظًا في السجل، لكنه يُستبعد تلقائيًا من الحملات ولا تُضاف له رسائل جديدة.</span></div></div>
    </section>

    <section className="rounded-[26px] border border-slate-200 bg-white p-4 sm:p-5"><div className="flex items-end justify-between gap-3"><div><h2 className="font-black">أحدث جهات الاتصال</h2><p className="mt-1 text-[9px] text-slate-400">آخر 100 جهة اتصال</p></div><span className="shrink-0 rounded-full bg-[#e9fbf8] px-3 py-1 text-[9px] font-black text-[#008f87]">{contactCount} إجمالي</span></div>
      {contacts.length ? <><div className="mt-4 grid gap-2 md:hidden">{contacts.map((contact)=><article key={contact.id} className="rounded-[18px] border border-slate-200 bg-[#fbfdfd] p-3.5"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><b className="block truncate text-sm text-slate-900">{contact.displayName||"بدون اسم"}</b><span dir="ltr" className="mt-1 block text-right text-[11px] text-slate-500">{contact.phoneE164}</span>{contact.email?<span dir="ltr" className="mt-1 block truncate text-right text-[10px] text-slate-400">{contact.email}</span>:null}</div><ContactState optedOut={Boolean(contact.optedOutAt)}/></div><div className="mt-3 flex flex-wrap items-center justify-between gap-2 border-t border-slate-100 pt-3 text-[9px] text-slate-400"><span>{contactSourceLabel(contact.source)}</span><span>{contact.createdAt.toLocaleDateString("ar-SA")}</span></div></article>)}</div><div className="mt-3 hidden overflow-x-auto md:block"><table className="w-full min-w-[720px] text-right text-[10px]"><thead><tr className="border-b border-slate-100 text-slate-400"><th scope="col" className="p-2">الاسم</th><th scope="col" className="p-2">رقم الجوال</th><th scope="col" className="p-2">المصدر</th><th scope="col" className="p-2">الحالة</th><th scope="col" className="p-2">أضيفت</th></tr></thead><tbody>{contacts.map((contact)=><tr key={contact.id} className="border-b border-slate-100 last:border-0 hover:bg-slate-50/50"><td className="p-2 font-bold">{contact.displayName||"—"}</td><td dir="ltr" className="p-2 text-right">{contact.phoneE164}</td><td className="p-2">{contactSourceLabel(contact.source)}</td><td className="p-2"><ContactState optedOut={Boolean(contact.optedOutAt)}/></td><td className="p-2 text-slate-400">{contact.createdAt.toLocaleDateString("ar-SA")}</td></tr>)}</tbody></table></div></> : <div className="p-8 text-center"><ContactRound className="mx-auto mb-3 h-6 w-6 text-slate-300"/><b className="block text-sm">لا توجد جهات اتصال بعد</b><span className="mx-auto mt-2 block max-w-md text-[10px] leading-6 text-slate-500">استورد ملف عملائك مع توثيق الموافقة التسويقية عند توفرها.</span><Link href="#import-contacts" className={`mt-4 inline-flex min-h-10 items-center rounded-xl border border-[#bdebe5] bg-[#effbf9] px-3 text-[10px] font-black text-[#008f87] ${buttonFocus}`}>استيراد أول ملف</Link></div>}
    </section>

    <section className="rounded-[26px] border border-slate-200 bg-white p-4 sm:p-5"><div className="flex flex-wrap items-end justify-between gap-2"><div><h2 className="font-black">سجل الاستيراد</h2><p className="mt-1 text-[9px] text-slate-400">آخر 10 عمليات استيراد</p></div>{hasActiveImport?<span role="status" className="rounded-full bg-amber-50 px-3 py-1 text-[9px] font-black text-amber-700">المعالجة جارية</span>:null}</div><div className="mt-4 grid gap-2">{imports.map((item)=>{const handled=Math.min(item.totalRows,item.importedRows+item.duplicateRows+item.rejectedRows),progress=item.totalRows?Math.round(handled/item.totalRows*100):100,active=item.status==="queued"||item.status==="processing";return <article key={item.id} className="rounded-[18px] bg-slate-50/70 p-3 text-[10px]"><div className="flex flex-wrap items-start justify-between gap-2"><div className="min-w-0"><b className="block break-all">{item.fileName}</b><span className="mt-1 block text-[9px] text-slate-400">{item.createdAt.toLocaleString("ar-SA")}</span></div><div className="flex items-center gap-2"><span className={active?"font-bold text-amber-700":item.status==="failed"?"font-bold text-rose-700":"font-bold text-emerald-700"}>{importStatus(item.status)}</span>{item.status==="failed"?<form action={retryWhatsAppContactImportAction}><input type="hidden" name="importId" value={item.id}/><button type="submit" className={`min-h-9 rounded-lg border border-rose-200 bg-white px-2 font-bold text-rose-700 transition hover:bg-rose-50 ${buttonFocus}`}>إعادة المحاولة</button></form>:null}</div></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-200" role="progressbar" aria-label={`تقدم استيراد ${item.fileName}`} aria-valuemin={0} aria-valuemax={100} aria-valuenow={progress}><div className="h-full rounded-full bg-[#00bfae] transition-all" style={{width:`${progress}%`}}/></div><div className="mt-2 flex flex-wrap justify-between gap-2 text-[9px] text-slate-500"><span>{progress}% · {handled} من {item.totalRows}</span><span>{item.importedRows} مستورد · {item.duplicateRows} مكرر · {item.rejectedRows} مرفوض</span></div></article>})}{!imports.length?<div className="p-6 text-center"><b className="block text-sm">لا توجد عمليات استيراد بعد</b><p className="mt-2 text-[10px] text-slate-500">عند استيراد ملف ستظهر هنا حالة المعالجة والنتائج.</p></div>:null}</div></section>
  </div>;
}

function ContactState({ optedOut }: { optedOut: boolean }) { return optedOut ? <span className="shrink-0 rounded-full bg-rose-50 px-2.5 py-1 text-[9px] font-black text-rose-700">ألغى الاشتراك</span> : <span className="shrink-0 rounded-full bg-emerald-50 px-2.5 py-1 text-[9px] font-black text-emerald-700">متاح بموافقة</span>; }
function Stat({label,value}:{label:string;value:string|number}){return <div className="rounded-[18px] border border-slate-200 bg-white p-3"><span className="text-[9px] text-slate-400">{label}</span><b className="mt-1 block text-lg text-slate-900">{value}</b></div>}
function Notice({text,ok=false}:{text:string;ok?:boolean}){return <div role="status" aria-live="polite" className={`flex items-center gap-2 rounded-2xl border p-3 text-[10px] font-bold ${ok?"border-emerald-200 bg-emerald-50 text-emerald-800":"border-rose-200 bg-rose-50 text-rose-800"}`}>{ok?<CheckCircle2 className="h-4 w-4"/>:null}{text}</div>}
function importStatus(status:string){if(status==="queued")return "بانتظار المعالجة";if(status==="processing")return "قيد الاستيراد";if(status==="completed")return "مكتمل";if(status==="completed_with_errors")return "مكتمل مع ملاحظات";return "تعذر الإكمال — يحتاج مراجعة"}
function contactSourceLabel(source:string){if(source==="manual_import")return "استيراد ملف";if(source==="manual")return "إضافة يدوية";if(source==="shopify")return "Shopify";if(source==="api")return "تكامل خارجي";return "مصدر آخر"}
