import Link from "next/link";
import { redirect } from "next/navigation";
import { workspaceSearchMatches } from "../../../lib/whatsapp/workspace-search";
import { Search } from "lucide-react";
import { getWhatsAppReadContext } from "../../../lib/whatsapp/rbac";
import { WorkspaceHeading, WorkspaceEmpty } from "../_components/workspace-ui";
const guides = [
  { id: "links", title: "إنشاء الروابط المختصرة ومتابعتها", category: "الحملات", href: "/dashboard/whatsapp/links", steps: ["أدخل اسمًا واضحًا ورابط HTTPS للمنتج أو الحجز ثم أنشئ الرابط.", "انسخ الرابط وشاركه، ويمكنك تعديل الوجهة أو إيقاف الرابط من بطاقته.", "تابع النقرات أو صدّر النتائج. النقرات ليست عدد أشخاص فريدين."] },
  { id: "reports", title: "قراءة تقارير الأداء", category: "التقارير", href: "/dashboard/whatsapp/insights", steps: ["اختر فترة التقرير ثم راجع مؤشرات التسليم والقراءة والتفاعل.", "افتح تقرير الحملة لمعرفة حالة المستلمين ومحاولات الإرسال.", "النقرات والردود والحجوزات تعرض حسب قواعد الإسناد الموضحة، ولا تمثل وحدها إيرادًا مؤكدًا."] },
  { id: "exports", title: "تنزيل التقارير ومعالجة تعذر التصدير", category: "التقارير", href: "/dashboard/whatsapp/messages", steps: ["طبّق البحث والحالة والفترة أولًا ثم اضغط تصدير CSV وانتظر تجهيز الملف.", "إذا كانت النتائج كبيرة فاختر فترة أقصر. عند تعذر الاتصال يمكنك إعادة المحاولة من الصفحة نفسها.", "التصدير يتطلب صلاحية إدارة الحملات واشتراكًا نشطًا. افتح الملف في Excel مع الحفاظ على أرقام الجوال كنص."] },
  { id: "audit", title: "متابعة سجل عمليات المنشأة", category: "الأمان", href: "/dashboard/whatsapp/audit", steps: ["افتح سجل التدقيق بصلاحية المالك أو مسؤول المنشأة.", "راجع نوع العملية ووقتها ومن نفّذها ونتيجتها.", "استخدم السجل لتتبع عمليات الربط والحملات والتصدير عند مراجعة نشاط الفريق."] },
  { id: "ai-report", title: "متابعة أداء البوت واستخدامه", category: "خدمة العملاء", href: "/dashboard/whatsapp/ai", steps: ["افتح مركز الذكاء الاصطناعي لمراجعة جاهزية الخدمة وحالة كل بوت.", "اختر فترة التقرير، وتابع محاولات المعالجة والردود التي قبلتها Meta والتحويل إلى الفريق.", "راجع الحد اليومي وسجل النشاط؛ تجهيز الرد لا يعني إرساله، وقبول Meta لا يعني وصوله أو قراءته."] },
  { id: "bot", title: "إعداد بوت خدمة العملاء", category: "خدمة العملاء", href: "/dashboard/whatsapp/bots", steps: ["اختر الرقم وطريقة الرد، وأضف الأسئلة المعتمدة أو معرفة المنشأة.", "جرّب أسئلة داخل اللوحة ثم احفظ الإعدادات. يتطلب الذكاء الاصطناعي إعداد مزوده لدى مسؤول المنصة.", "شغّل البوت بموافقة صريحة، وتابع المحادثات المحالة. رد الموظف يوقف البوت في المحادثة حتى الاستئناف."] },
  { id: "carousel", title: "حملة ببطاقات منتجات Meta", category: "الحملات", href: "/dashboard/whatsapp/carousel", steps: ["اربط كتالوج Meta بحساب واتساب، ثم أنشئ قالب كاروسيل للمراجعة.", "بعد الاعتماد والمزامنة، اختر القالب في الحملة واقرأ كتالوج الرقم.", "حدّد من 2 إلى 10 منتجات وراجع ترتيب البطاقات، ثم جهّز الحملة لجمهور موافق."] },
  { id: "connect", title: "ربط رقم المنشأة", category: "البدء", href: "/dashboard/whatsapp/setup", steps: ["افتح ربط واتساب وابدأ الربط الرسمي مع Meta.", "اختر حساب الأعمال ورقم منشأتك ثم أكمل خطوات Meta.", "راجع حالة الاتصال والفوترة لدى Meta قبل إرسال الرسائل."] },
  { id: "contacts", title: "استيراد العملاء وتكوين الجمهور", category: "الجمهور", href: "/dashboard/whatsapp/contacts", steps: ["جهّز CSV أو Excel بعمود رقم الجوال، ويمكن إضافة الاسم والوسوم.", "ارفع الملف وسجّل دليل الموافقة عند تأكيد وجودها.", "تابع نتيجة الاستيراد، ثم راجع الجهات المؤهلة وأنشئ شريحة مناسبة."] },
  { id: "templates", title: "إنشاء قالب وإرساله للمراجعة", category: "الحملات", href: "/dashboard/whatsapp/templates", steps: ["اختر نموذجًا أو أنشئ قالبًا مخصصًا وحدّد فئته ولغته.", "اكتب الرسالة وأمثلة المتغيرات، وأرفق وسائط عند الحاجة.", "أرسل إلى Meta للمراجعة ثم حدّث القوالب. لا تستخدم القالب حتى يظهر معتمدًا."] },
  { id: "campaign", title: "إطلاق حملة ومتابعة وصولها", category: "الحملات", href: "/dashboard/whatsapp/campaigns?new=1#new-campaign", steps: ["حدّد الرقم والجمهور، ثم اختر قالبًا معتمدًا وراجع المعاينة.", "أنشئ الحملة لتثبيت المستلمين، ثم راجع العدد النهائي قبل الإطلاق.", "ابدأ الاختبار المحدود وتابع التقرير المباشر؛ قبول Meta يختلف عن وصول الرسالة."] },
  { id: "products", title: "حملة لمنتجات متجر سلة", category: "المتاجر", href: "/dashboard/whatsapp/campaigns?new=1#new-campaign", steps: ["اربط متجر سلة بتفويض يسمح بقراءة المنتجات.", "في رسالة الحملة، اختر قالبًا معتمدًا ذا متغيرات ثم افتح اختيار منتج من سلة.", "ابحث عن المنتج ووزّع الاسم والسعر والرابط على المتغيرات، ثم راجع الرسالة قبل تثبيت الجمهور."] },
  { id: "carts", title: "متابعة السلال المتروكة", category: "المتاجر", href: "/dashboard/whatsapp/carts", steps: ["اربط المتجر وفعّل أحداث السلال؛ ربط الطلبات وحده لا يوفّر السلال.", "أنشئ مسار السلة المتروكة من الأتمتة بقالب معتمد وموافقة العميل.", "راجع الحالات حسب الفترة، وصفِّ السجل ثم صدّر النتائج CSV لفتحها في Excel. السلة المستعادة لا تثبت وحدها أن رسالة واتساب سببت الشراء."] },
  { id: "inbox", title: "المحادثات والفرز بين الموظفين", category: "خدمة العملاء", href: "/dashboard/whatsapp/inbox/operations", steps: ["افتح الفرز والمتابعة لمعرفة المحادثات التي تحتاج ردًا أو مسؤولًا.", "افتح المحادثة وعيّن المسؤول والأولوية وفق صلاحياتك.", "استخدم الرد المباشر في نافذة الخدمة المتاحة؛ خارجها يلزم قالب معتمد."] },
  { id: "blocked", title: "منع الإرسال وإلغاء الاشتراك", category: "الجمهور", href: "/dashboard/whatsapp/blacklist", steps: ["افتح قائمة المنع وابحث عن الرقم أو اسم العميل.", "لمنع رقم يدويًا، أدخله وأكّد سحب الموافقة من هذه المنشأة.", "إعادة الاستيراد لا تلغي المنع. راجع سجل التدقيق لمعرفة العمليات السابقة."] },
  { id: "messages", title: "فهم حالات الرسائل وتصديرها", category: "التقارير", href: "/dashboard/whatsapp/messages", steps: ["صفِّ السجل بالاتجاه والحالة والفترة أو ابحث عن العميل.", "افتح المحادثة لمراجعة السياق، وميّز قبول الإرسال عن التسليم والقراءة.", "صدّر النتائج CSV إذا كانت لديك صلاحية إدارة الحملات. اختر فترة أقصر للتقارير الكبيرة."] },
  { id: "appointments", title: "إدارة الفروع وتعديل موعد الزائر", category: "المواعيد", href: "/dashboard/appointments", steps: ["راجع القادم والجديد والسجل، واختر الفرع أو ابحث عن العميل.", "من إعدادات الفروع حدّد ساعات العمل ومدة الفترة وسعتها.", "يستخدم الزائر تعديل موعدي للتحقق عبر واتساب وتحديث حجزه نفسه. يلزم رقم حجوزات وقالب تحقق معتمدان."] },
  { id: "sessions", title: "مراجعة جلسات الدخول", category: "الأمان", href: "/dashboard/settings/sessions", steps: ["افتح جلسات الدخول لرؤية الجلسات النشطة وتاريخ بدايتها وانتهائها.", "أنه الجلسة التي لم تعد تستخدمها أو أنه جميع الجلسات الأخرى.", "جلستك الحالية تبقى مفتوحة؛ يحتاج أصحاب الجلسات المنتهية إلى تسجيل الدخول مجددًا."] },
  { id: "support", title: "طلب دعم مع سياق المشكلة", category: "المساعدة", href: "/dashboard/support?context=whatsapp", steps: ["اذكر القسم الذي ظهرت فيه المشكلة والخطوات التي سبقتها.", "أرفق رمز الخطأ أو لقطة توضح الحالة، وأخفِ البيانات السرية.", "تابع طلبك من مركز الدعم. لا تضف كلمات مرور أو مفاتيح اتصال إلى التذكرة."] },
] as const;
export default async function GuidesPage({ searchParams }: { searchParams: Promise<{ q?: string; category?: string }> }) {
  const context = await getWhatsAppReadContext("view");
  if (!context) redirect("/dashboard/whatsapp?access=denied");
  const params = await searchParams, query = (typeof params.q === "string" ? params.q : "").trim().slice(0,80), category = String(params.category ?? "all");
  const categories = [...new Set(guides.map(guide => guide.category))];
  const matching = guides.filter(guide => (category === "all" || guide.category === category) && workspaceSearchMatches(`${guide.title} ${guide.steps.join(" ")}`, query));
  return <div className="wa-page" dir="rtl"><WorkspaceHeading eyebrow="دليل الاستخدام" title="شروحات INFRO" description="خطوات واضحة لأدوات منشأتك، من الربط الأول حتى متابعة الرسائل والمواعيد." action={<Link className="wa-button wa-secondary" href="/dashboard/support?context=whatsapp">تواصل مع الدعم</Link>}/>
    <section className="wa-panel"><form className="wa-filters"><label className="wa-search">البحث في الشروحات<input name="q" defaultValue={query} maxLength={80} placeholder="ربط الرقم، السلال، المواعيد…"/></label><label>الموضوع<select name="category" defaultValue={category}><option value="all">كل الموضوعات</option>{categories.map(item => <option key={item} value={item}>{item}</option>)}</select></label><button className="wa-button"><Search size={17} aria-hidden="true"/>بحث</button>{query || category !== "all" ? <Link href="/dashboard/whatsapp/guides" className="wa-button wa-secondary">مسح التصفية</Link> : null}</form><p className="wa-note">{matching.length.toLocaleString("ar-SA")} شرح · افتح العنوان لعرض الخطوات والانتقال إلى الأداة.</p></section>
    {matching.length ? <section className="wa-guide-list" aria-label="شروحات الاستخدام">{matching.map((guide, index) => <details id={guide.id} key={guide.id} className="wa-guide"><summary><span className="wa-guide-number">{String(index+1).padStart(2,"0")}</span>{guide.title}</summary><ol>{guide.steps.map(step => <li key={step}>{step}</li>)}</ol><Link href={guide.href} className="wa-text-link">فتح القسم ←</Link></details>)}</section> : <WorkspaceEmpty title="لا توجد شروحات مطابقة" description="جرّب كلمات أقصر أو اختر كل الموضوعات."/>}
  </div>;
}
