"use client";

import Link from "next/link";
import { useActionState } from "react";
import { KeyRound, ShieldCheck } from "lucide-react";
import { IrLogo } from "../../components/brand/ir-logo";
import { requestPasswordResetAction } from "../actions/password-reset";

export default function ForgotPasswordPage() {
  const [state, action, pending] = useActionState(requestPasswordResetAction, {});
  return <main dir="rtl" className="min-h-screen bg-[radial-gradient(circle_at_80%_0%,rgba(53,228,203,.10),transparent_26rem),#f4f8f8] text-[#0a2426]"><div className="mx-auto flex min-h-screen w-full max-w-md flex-col justify-center px-4 py-8"><Link href="/" aria-label="العودة إلى INFRO" className="w-fit"><IrLogo className="h-12 w-auto" priority /></Link><section className="mt-6 rounded-[28px] border border-[#dfe9e8] bg-white p-5 shadow-[0_28px_80px_-58px_rgba(7,24,27,.65)] sm:p-7"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-[#e9fbf8] text-[#008f87]"><KeyRound className="h-5 w-5" aria-hidden="true" /></span><span className="mt-5 block text-[9px] font-black tracking-[.18em] text-[#008f87]" dir="ltr">SECURE RECOVERY</span><h1 className="mt-1 text-2xl font-black">استعادة كلمة المرور</h1><p className="mt-1 text-sm leading-7 text-slate-500">أدخل بريد حسابك وسنرسل رابط استعادة صالحًا لمدة 30 دقيقة.</p>{state.success ? <p role="status" aria-live="polite" className="mt-4 rounded-2xl border border-emerald-200 bg-emerald-50 px-3 py-3 text-sm leading-6 text-emerald-800">{state.success}</p> : <form action={action} className="mt-5 space-y-4" aria-label="طلب استعادة كلمة المرور"><label className="block"><span className="mb-1.5 block text-sm font-black">البريد الإلكتروني</span><input name="email" type="email" autoComplete="email" required className="h-12 w-full rounded-2xl border border-slate-200 bg-[#fbfdfd] px-4 text-base outline-none transition focus:border-[#00a99d] focus:bg-white focus:ring-4 focus:ring-[#35e4cb]/10" /></label>{state.error ? <p role="alert" aria-live="assertive" className="rounded-2xl border border-rose-200 bg-rose-50 px-3 py-2.5 text-sm font-bold text-rose-700">{state.error}</p> : null}<button disabled={pending} aria-busy={pending} className="h-12 w-full rounded-2xl bg-[#07181b] px-4 text-sm font-black text-white transition hover:bg-[#0d292d] focus-visible:ring-2 focus-visible:ring-[#00bfae] focus-visible:ring-offset-2 disabled:bg-slate-300">{pending ? "جاري الإرسال..." : "إرسال رابط الاستعادة"}</button></form>}<div className="mt-5 flex items-center justify-between gap-3 border-t border-slate-100 pt-4"><span className="inline-flex items-center gap-1.5 text-[10px] font-bold text-slate-400"><ShieldCheck className="h-3.5 w-3.5 text-[#008f87]"/>INFRO Secure Access</span><Link href="/login" className="text-xs font-black text-[#008f87]">العودة لتسجيل الدخول</Link></div></section></div></main>;
}
