"use client";

import Link from "next/link";
import { useActionState } from "react";
import { KeyRound } from "lucide-react";
import { requestPasswordResetAction } from "../actions/password-reset";

export default function ForgotPasswordPage() {
  const [state, action, pending] = useActionState(requestPasswordResetAction, {});
  return <main dir="rtl" className="min-h-screen bg-[linear-gradient(180deg,#fbfaff,#fff_50%,#f8f6ff)] text-[#1f2552]"><div className="mx-auto flex min-h-screen w-full max-w-md flex-col justify-center px-4 py-8"><Link href="/" aria-label="العودة إلى iR" className="w-fit text-3xl font-black tracking-[-.08em] text-[#6f3bd2]">iR</Link><section className="mt-6 rounded-[28px] border border-[#e8e5f2] bg-white p-5 shadow-[0_24px_70px_-52px_rgba(73,48,125,.5)] sm:p-6"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-[#f1edff] text-[#6543ce]"><KeyRound className="h-5 w-5" aria-hidden="true" /></span><h1 className="mt-4 text-2xl font-black">استعادة كلمة المرور</h1><p className="mt-1 text-sm leading-7 text-slate-500">أدخل بريد حسابك وسنرسل رابطًا صالحًا لمدة 30 دقيقة.</p>{state.success ? <p role="status" aria-live="polite" className="mt-4 rounded-2xl border border-emerald-200 bg-emerald-50 px-3 py-3 text-sm leading-6 text-emerald-800">{state.success}</p> : <form action={action} className="mt-5 space-y-4" aria-label="طلب استعادة كلمة المرور"><label className="block"><span className="mb-1.5 block text-sm font-black">البريد الإلكتروني</span><input name="email" type="email" autoComplete="email" required className="h-12 w-full rounded-2xl border border-[#e5e3ec] bg-[#fbfbfd] px-4 text-sm outline-none focus:border-[#8b72dc]" /></label>{state.error ? <p role="alert" aria-live="assertive" className="rounded-2xl border border-rose-200 bg-rose-50 px-3 py-2.5 text-sm font-bold text-rose-700">{state.error}</p> : null}<button disabled={pending} aria-busy={pending} className="h-12 w-full rounded-2xl bg-[#5b3fd6] px-4 text-sm font-black text-white disabled:bg-slate-300">{pending ? "جاري الإرسال..." : "إرسال رابط الاستعادة"}</button></form>}<p className="mt-5 text-center text-sm text-slate-500"><Link href="/login" className="font-black text-[#5d49cc]">العودة لتسجيل الدخول</Link></p></section></div></main>;
}
