import { redirect } from "next/navigation";
import { CalendarDays, Clock3, Phone, ShoppingBag } from "lucide-react";
import { db } from "../../lib/db";
import { getOwnedBusinessForRead } from "../../lib/ownership";
import { updateBookingStatusAction, updateOrderStatusAction } from "../../actions/transactions";
import { ConfirmSubmitButton } from "../../../components/dashboard/confirm-submit-button";

const orderStatusLabel: Record<string, string> = { pending: "جديد", confirmed: "مؤكد", processing: "قيد التنفيذ", completed: "مكتمل", cancelled: "ملغي" };
const bookingStatusLabel: Record<string, string> = { pending: "جديد", confirmed: "مؤكد", completed: "مكتمل", cancelled: "ملغي", no_show: "لم يحضر" };
const activeOrderStatuses = ["pending", "confirmed", "processing"] as const;
const activeBookingStatuses = ["pending", "confirmed"] as const;
const HISTORY_LIMIT = 50;

function dateTime(value: Date) { return new Intl.DateTimeFormat("ar-SA", { timeZone: "Asia/Riyadh", dateStyle: "medium", timeStyle: "short" }).format(value); }
function statusClass(status: string) { if (status === "completed") return "bg-emerald-50 text-emerald-700"; if (status === "confirmed" || status === "processing") return "bg-blue-50 text-blue-700"; if (status === "cancelled" || status === "no_show") return "bg-rose-50 text-rose-700"; return "bg-amber-50 text-amber-700"; }
function ActionButton({ id, status, label, action, tone = "primary", confirmMessage }: { id: string; status: string; label: string; action: (formData: FormData) => Promise<void>; tone?: "primary" | "danger" | "neutral"; confirmMessage?: string }) { const cls = tone === "danger" ? "border-rose-200 bg-rose-50 text-rose-700" : tone === "neutral" ? "border-[#e5e8f3] bg-white text-slate-600" : "border-[#d9d1f6] bg-[#f5f1ff] text-[#5d49cc]"; const className = `min-h-11 rounded-xl border px-4 text-[11px] font-black ${cls}`; return <form action={action}><input type="hidden" name="id" value={id} /><input type="hidden" name="status" value={status} />{confirmMessage ? <ConfirmSubmitButton label={label} confirmMessage={confirmMessage} showIcon={false} className={className} /> : <button className={className}>{label}</button>}</form>; }

export default async function DashboardInboxPage() {
  const business = await getOwnedBusinessForRead();
  if (!business) redirect("/onboarding");

  const orderInclude = { customer: { select: { name: true, phone: true } }, items: { select: { name: true, quantity: true, total: true } } } as const;
  const bookingInclude = { customer: { select: { name: true, phone: true } }, service: { select: { name: true } } } as const;
  const [activeOrders, orderHistory, activeBookings, bookingHistory] = await Promise.all([
    db.order.findMany({ where: { businessId: business.id, status: { in: [...activeOrderStatuses] } }, orderBy: { createdAt: "desc" }, include: orderInclude }),
    db.order.findMany({ where: { businessId: business.id, status: { notIn: [...activeOrderStatuses] } }, orderBy: { createdAt: "desc" }, take: HISTORY_LIMIT, include: orderInclude }),
    db.booking.findMany({ where: { businessId: business.id, status: { in: [...activeBookingStatuses] } }, orderBy: [{ bookingDate: "asc" }, { bookingTime: "asc" }, { createdAt: "desc" }], include: bookingInclude }),
    db.booking.findMany({ where: { businessId: business.id, status: { notIn: [...activeBookingStatuses] } }, orderBy: { createdAt: "desc" }, take: HISTORY_LIMIT, include: bookingInclude }),
  ]);
  const orders = [...activeOrders, ...orderHistory];
  const bookings = [...activeBookings, ...bookingHistory];
  const newCount = activeOrders.filter((item) => item.status === "pending").length + activeBookings.filter((item) => item.status === "pending").length;

  return <div className="space-y-4 pb-4">
    <section className="rounded-[24px] border border-[#e7e9f4] bg-white p-4 sm:p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-xl font-black text-[#20264f]">الطلبات والحجوزات</h1><p className="mt-1 text-sm text-slate-500">تظهر جميع العناصر التي تحتاج إجراءً، مع أحدث {HISTORY_LIMIT} عنصرًا من السجل المكتمل لكل قسم.</p></div>{newCount ? <span className="rounded-full bg-amber-50 px-3 py-1.5 text-xs font-black text-amber-700">{newCount} جديد</span> : <span className="rounded-full bg-emerald-50 px-3 py-1.5 text-xs font-black text-emerald-700">لا توجد عناصر جديدة</span>}</div></section>

    <section className="space-y-3"><div className="flex items-center gap-2"><ShoppingBag className="h-4 w-4 text-[#6f3bd2]" /><h2 className="font-black text-[#20264f]">الطلبات</h2><span className="text-xs text-slate-400">{orders.length}</span></div>
      {orders.length ? orders.map((order) => <article key={order.id} className="rounded-[22px] border border-[#e7e9f4] bg-white p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full px-2.5 py-1 text-[10px] font-black ${statusClass(order.status)}`}>{orderStatusLabel[order.status] ?? order.status}</span><span className="text-[10px] text-slate-400">{dateTime(order.createdAt)}</span></div><b className="mt-2 block text-sm text-[#20264f]">{order.customer.name}</b><a href={`tel:${order.customer.phone}`} dir="ltr" className="mt-1 inline-flex min-h-8 items-center gap-1 text-xs text-slate-500"><Phone className="h-3 w-3" />{order.customer.phone}</a></div><div className="text-left"><span className="text-[10px] text-slate-400">الإجمالي</span><b className="block text-lg text-[#20264f]">{order.total} ر.س</b></div></div><div className="mt-3 rounded-2xl bg-[#faf9fd] p-3">{order.items.map((item) => <div key={`${order.id}-${item.name}`} className="flex items-center justify-between gap-3 py-1 text-xs"><span className="text-slate-600">{item.name} × {item.quantity}</span><span className="font-bold text-[#20264f]">{item.total} ر.س</span></div>)}{order.notes ? <p className="mt-2 border-t border-[#ece9f4] pt-2 text-xs leading-6 text-slate-500">{order.notes}</p> : null}</div><div className="mt-3 flex flex-wrap gap-2">{order.status === "pending" ? <><ActionButton id={order.id} status="confirmed" label="تأكيد" action={updateOrderStatusAction} /><ActionButton id={order.id} status="cancelled" label="إلغاء" action={updateOrderStatusAction} tone="danger" confirmMessage="هل تريد إلغاء هذا الطلب؟" /></> : null}{order.status === "confirmed" ? <><ActionButton id={order.id} status="processing" label="بدء التنفيذ" action={updateOrderStatusAction} /><ActionButton id={order.id} status="completed" label="إكمال" action={updateOrderStatusAction} /><ActionButton id={order.id} status="cancelled" label="إلغاء" action={updateOrderStatusAction} tone="danger" confirmMessage="هل تريد إلغاء هذا الطلب؟" /></> : null}{order.status === "processing" ? <><ActionButton id={order.id} status="completed" label="تم التنفيذ" action={updateOrderStatusAction} /><ActionButton id={order.id} status="cancelled" label="إلغاء" action={updateOrderStatusAction} tone="danger" confirmMessage="هل تريد إلغاء هذا الطلب؟" /></> : null}</div></article>) : <div className="rounded-[22px] border border-dashed border-[#dcd8ea] bg-white px-4 py-8 text-center"><b className="block text-sm text-[#303653]">لم تصل طلبات بعد</b><span className="mt-1 block text-xs text-slate-500">ستظهر هنا الطلبات الجديدة القادمة من صفحتك.</span></div>}
    </section>

    <section className="space-y-3 pt-2"><div className="flex items-center gap-2"><CalendarDays className="h-4 w-4 text-[#6f3bd2]" /><h2 className="font-black text-[#20264f]">الحجوزات</h2><span className="text-xs text-slate-400">{bookings.length}</span></div>
      {bookings.length ? bookings.map((booking) => <article key={booking.id} className="rounded-[22px] border border-[#e7e9f4] bg-white p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full px-2.5 py-1 text-[10px] font-black ${statusClass(booking.status)}`}>{bookingStatusLabel[booking.status] ?? booking.status}</span><span className="text-[10px] text-slate-400">استقبل {dateTime(booking.createdAt)}</span></div><b className="mt-2 block text-sm text-[#20264f]">{booking.customer.name}</b><a href={`tel:${booking.customer.phone}`} dir="ltr" className="mt-1 inline-flex min-h-8 items-center gap-1 text-xs text-slate-500"><Phone className="h-3 w-3" />{booking.customer.phone}</a></div><div className="rounded-2xl bg-[#f7f4ff] px-3 py-2 text-left"><div className="flex items-center gap-1 text-xs font-black text-[#5d49cc]"><Clock3 className="h-3.5 w-3.5" />{booking.bookingDate} · {booking.bookingTime}</div><span className="mt-1 block text-[10px] text-slate-500">{booking.service?.name ?? "خدمة"}</span></div></div>{booking.notes ? <p className="mt-3 rounded-2xl bg-[#faf9fd] p-3 text-xs leading-6 text-slate-500">{booking.notes}</p> : null}<div className="mt-3 flex flex-wrap gap-2">{booking.status === "pending" ? <><ActionButton id={booking.id} status="confirmed" label="تأكيد الحجز" action={updateBookingStatusAction} /><ActionButton id={booking.id} status="cancelled" label="رفض/إلغاء" action={updateBookingStatusAction} tone="danger" confirmMessage="هل تريد رفض أو إلغاء هذا الحجز؟" /></> : null}{booking.status === "confirmed" ? <><ActionButton id={booking.id} status="completed" label="تم الحضور" action={updateBookingStatusAction} /><ActionButton id={booking.id} status="no_show" label="لم يحضر" action={updateBookingStatusAction} tone="neutral" confirmMessage="تسجيل العميل كـ «لم يحضر»؟" /><ActionButton id={booking.id} status="cancelled" label="إلغاء" action={updateBookingStatusAction} tone="danger" confirmMessage="هل تريد إلغاء هذا الحجز؟" /></> : null}</div></article>) : <div className="rounded-[22px] border border-dashed border-[#dcd8ea] bg-white px-4 py-8 text-center"><b className="block text-sm text-[#303653]">لم تصل حجوزات بعد</b><span className="mt-1 block text-xs text-slate-500">عند تفعيل الحجز ستظهر مواعيد العملاء هنا.</span></div>}
    </section>
  </div>;
}
