"use client";

import {useMemo,useState} from "react";
import type {Prisma} from "@prisma/client";
import {BadgeCheck,BriefcaseBusiness,Building2,ChevronLeft,ChevronDown,Clock3,FileText,Globe2,Mail,MapPin,MessageCircle,Phone,Share2,Sparkles,Star,UserRound,UsersRound,Wrench,CheckCircle2,X} from "lucide-react";

type BusinessPublicPayload=Prisma.BusinessGetPayload<{include:{products:{include:{category:true}};offers:true;services:true;openingHours:true;galleryItems:true;socialLinks:true;branches:true;departments:{include:{contacts:{include:{branch:true}}}}}}>;
type Props={business:BusinessPublicPayload;qrDataUrl:string;publicUrl:string};
const digits=(v?:string|null)=>String(v??"").replace(/\D/g,"");
const phone=(v?:string|null)=>{const d=digits(v);return d.length>=8&&d.length<=15?d:null};
const text=(v?:string|null)=>{const s=String(v??"").trim();return s.length>=2?s:null};
const safeUrl=(v?:string|null)=>{const s=String(v??"").trim();if(!s)return null;try{return new URL(/^https?:\/\//i.test(s)?s:`https://${s}`).toString()}catch{return null}};
const Title=({kicker,children}:{kicker?:string;children:React.ReactNode})=><div><div className="flex items-center gap-2 text-[10px] font-black text-[#6b38b1]">{kicker&&<><span className="h-1.5 w-1.5 rounded-full bg-[#6b38b1]"/>{kicker}</>}</div><h2 className="mt-1 text-[21px] font-black tracking-tight md:text-[28px]">{children}</h2></div>;

export function PublicBusinessPageV10Compact({business,qrDataUrl,publicUrl}:Props){
 const [share,setShare]=useState(false),[branchesOpen,setBranchesOpen]=useState(false),[servicesOpen,setServicesOpen]=useState(false);
 const wa=phone(business.whatsapp)||"966500000000",tel=phone(business.phone)||"966500000001";
 const cover=safeUrl(business.coverUrl),profile=safeUrl(business.companyProfileUrl),website=safeUrl(business.website);
 const about=text(business.shortDescription)||text(business.description)||"منشأة متخصصة تقدم خدماتها باحترافية وموثوقية، مع فريق عمل يركز على جودة التجربة وسهولة التواصل.";
 const category=text(business.businessCategory)||text(business.businessType)||"منشأة أعمال";
 const location=[text(business.city)||"جدة",text(business.district)||"حي الروضة"].filter(Boolean).join("، ");
 const realServices=business.services.filter(s=>s.isActive&&text(s.name)).slice(0,6);
 const services=realServices.length?realServices.map((s,i)=>({id:String(s.id),name:s.name,description:text(s.description)||["خدمة احترافية بمعايير جودة واضحة.","حلول مرنة تناسب احتياج العملاء."][i%2]})):[{id:"d1",name:"الخدمة الأولى",description:"وصف مختصر للخدمة التي تقدمها المنشأة."},{id:"d2",name:"الخدمة الثانية",description:"حلول احترافية تناسب احتياجات العملاء."},{id:"d3",name:"الخدمة الثالثة",description:"تنفيذ موثوق ومتابعة بجودة عالية."},{id:"d4",name:"الخدمة الرابعة",description:"خدمة إضافية ضمن نطاق أعمال المنشأة."}];
 const realContacts=useMemo(()=>business.departments.filter(d=>d.isActive).flatMap(d=>d.contacts.filter(c=>c.isActive&&text(c.name)).map(c=>({id:String(c.id),name:c.name,role:text(c.jobTitle)||text(d.name)||"خدمة العملاء",p:phone(c.phone),w:phone(c.whatsapp),image:safeUrl(c.imageUrl)}))).slice(0,4),[business.departments]);
 const contacts=realContacts.length?realContacts:[{id:"c1",name:"محمد أحمد",role:"مبيعات الشركات",p:tel,w:wa,image:null},{id:"c2",name:"خالد عبدالله",role:"خدمة العملاء",p:tel,w:wa,image:null},{id:"c3",name:"سارة محمد",role:"العلاقات والعملاء",p:tel,w:wa,image:null},{id:"c4",name:"عبدالله سالم",role:"مدير العمليات",p:tel,w:wa,image:null}];
 const realBranches=business.branches.filter(b=>b.isActive&&text(b.name)).slice(0,6);
 const branches=realBranches.length?realBranches.map((b,i)=>({id:String(b.id),name:b.name,place:[b.city,b.district,b.address].filter(Boolean).join("، ")||`جدة، فرع ${i+1}`})):[{id:"b1",name:"الفرع الرئيسي",place:"جدة، حي الروضة"},{id:"b2",name:"فرع شمال جدة",place:"جدة، حي الزهراء"},{id:"b3",name:"فرع جنوب جدة",place:"جدة، حي الأجاويد"}];
 const gallery=business.galleryItems.filter(g=>g.isActive&&safeUrl(g.imageUrl)).slice(0,4);
 const map=safeUrl(business.googleMapsLink)||`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(location)}`;
 const hour=business.openingHours.find(h=>!h.isClosed&&h.opensAt&&h.closesAt);const hours=text(business.workingHours)||(hour?`${hour.opensAt} - ${hour.closesAt}`:"السبت - الخميس، 8:00 ص - 10:00 م");
 const IconSet=[Sparkles,Wrench,Building2,BriefcaseBusiness];
 const doShare=async()=>{if(typeof navigator!=="undefined"&&navigator.share){try{await navigator.share({title:business.name,url:publicUrl});return}catch{}}setShare(true)};
 return <main dir="rtl" data-renderer="hee-v10-3-business-identity" className="min-h-screen bg-[#fcfbfd] text-[#18131d]">
  <section className="relative min-h-[330px] overflow-hidden bg-[#151018] text-white md:min-h-[470px]">
   {cover?<img src={cover} alt="" className="absolute inset-0 h-full w-full object-cover"/>:<div className="absolute inset-0 bg-[radial-gradient(circle_at_72%_20%,rgba(104,51,167,.38),transparent_30%),linear-gradient(125deg,#17111b,#0d0b0f_72%)]"/>}<div className="absolute inset-0 bg-black/35"/>
   <div className="relative mx-auto max-w-[1180px] px-5 pt-5 md:px-8 md:pt-7">
    <header className="flex items-center justify-between" dir="ltr"><a href="/" aria-label="العودة إلى منصة HEE" className="group inline-flex items-center"><b className="text-[27px] font-black tracking-[-.08em] text-[#9b6bd7] transition duration-300 group-hover:scale-105 group-hover:text-[#b58be6]">HEE</b></a><button onClick={doShare} aria-label="مشاركة الصفحة" className="grid h-9 w-9 place-items-center rounded-full bg-white/10 backdrop-blur transition hover:bg-white/20"><Share2 className="h-4 w-4"/></button></header>
    <div className="flex min-h-[260px] items-center py-6 md:min-h-[390px]"><div className="max-w-3xl"><div className="flex max-w-[92vw] items-start gap-2 md:max-w-3xl"><h1 className="line-clamp-2 min-w-0 text-[30px] font-black leading-[1.18] tracking-tight md:text-[52px]">{business.name}</h1>{business.isVerified&&<BadgeCheck aria-label="حساب موثق" className="mt-1.5 h-6 w-6 shrink-0 fill-[#1d9bf0] text-white md:h-7 md:w-7"/>}</div><div className="mt-2 text-[16px] font-bold text-white/90 md:text-[24px]">{category}</div><div className="mt-3 flex flex-wrap items-center gap-x-3 gap-y-2 text-[11px] text-white/75 md:text-sm"><span className="inline-flex items-center gap-1.5"><MapPin className="h-3.5 w-3.5 text-[#b58be6]"/>{location}</span><span className="inline-flex items-center gap-1.5 text-emerald-300"><span className="h-1.5 w-1.5 rounded-full bg-emerald-400"/>مفتوح الآن</span></div><p className="mt-3 line-clamp-2 max-w-2xl text-[12px] leading-6 text-white/65 md:text-[15px]">{about}</p></div></div>
   </div>
  </section>
  <div className="mx-auto max-w-[1180px] space-y-8 px-4 pb-12 pt-5 md:space-y-12 md:px-8 md:pt-8">
   <section className="grid grid-cols-4 divide-x divide-x-reverse divide-[#ece6f0] rounded-[18px] border border-[#ece6f0] bg-white py-3.5"><Metric icon={BadgeCheck} value={business.isVerified?"موثق":"HEE"} label="الهوية"/><Metric icon={Star} value="4.9" label="التقييم"/><Metric icon={UsersRound} value="+500" label="عميل"/><Metric icon={CheckCircle2} value="+1000" label="تجربة"/></section>
   <section><Title kicker="تعرف علينا">نبذة عن المنشأة</Title><p className="mt-3 max-w-4xl text-[13px] leading-7 text-[#68606d]">{about}</p><div className="mt-3 flex flex-wrap gap-x-5 gap-y-2 text-[11px]"><b>+5 سنوات خبرة</b><b>{branches.length} فروع</b><b>+25 فريق العمل</b><b>98% رضا العملاء</b></div>{profile&&<a href={profile} className="mt-4 inline-flex items-center gap-2 text-xs font-black text-[#6333ad]"><FileText className="h-4 w-4"/>عرض الملف التعريفي <ChevronLeft className="h-3.5 w-3.5"/></a>}</section>
   <section><div className="mb-3"><Title kicker="مجالات العمل">خدماتنا</Title></div><button onClick={()=>setServicesOpen(true)} className="flex w-full items-center justify-between rounded-[18px] border border-[#e8e1ed] bg-[#faf7fc] p-4 text-right transition hover:bg-[#f7f2fa]"><span><b className="block text-sm">عرض الخدمات</b><span className="mt-1 block text-[11px] text-[#746d79]">{services.length} خدمات — اضغط لاستعراض التفاصيل</span></span><span className="grid h-10 w-10 place-items-center rounded-full bg-white text-[#6333ad]"><ChevronDown className="h-5 w-5"/></span></button></section>
   <section><div className="mb-3"><Title kicker="مواقع المنشأة">فروعنا</Title></div><button onClick={()=>setBranchesOpen(true)} className="flex w-full items-center justify-between rounded-[18px] border border-[#e8e1ed] bg-[#faf7fc] p-4 text-right transition hover:bg-[#f7f2fa]"><span><b className="block text-sm">عرض الفروع</b><span className="mt-1 block text-[11px] text-[#746d79]">{branches.length} فروع — اضغط لاستعراض المواقع</span></span><span className="grid h-10 w-10 place-items-center rounded-full bg-white text-[#6333ad]"><ChevronDown className="h-5 w-5"/></span></button></section>
   <section><div className="mb-3"><Title kicker="أشخاص لخدمتك">فريق العمل</Title></div><div className="flex gap-3 overflow-x-auto pb-2 snap-x">{contacts.map(c=><article key={c.id} className="min-w-[205px] snap-start rounded-[18px] border border-[#ebe5ef] bg-white p-4"><div className="flex items-center gap-3"><div className="grid h-11 w-11 shrink-0 place-items-center overflow-hidden rounded-full bg-[#f1eaf7]">{c.image?<img src={c.image} alt="" className="h-full w-full object-cover"/>:<UserRound className="h-5 w-5 text-[#6333ad]"/>}</div><div className="min-w-0"><h3 className="truncate text-sm font-black">{c.name}</h3><p className="truncate text-[11px] text-[#766e7b]">{c.role}</p></div></div><div className="mt-3 flex gap-2"><a href={`tel:${c.p||tel}`} className="flex-1 rounded-xl bg-[#f7f4f9] py-2 text-center text-[11px] font-black">اتصال</a>{c.w&&<a href={`https://wa.me/${c.w}`} className="flex-1 rounded-xl bg-[#f7f4f9] py-2 text-center text-[11px] font-black">واتساب</a>}</div></article>)}</div></section>
   {gallery.length>0&&<section><div className="mb-3"><Title kicker="أعمال مختارة">أعمالنا</Title></div><div className="flex gap-3 overflow-x-auto pb-2">{gallery.map((g,i)=><figure key={g.id} className="relative aspect-[1.25] min-w-[220px] overflow-hidden rounded-[18px] bg-[#eee8f3]"><img src={safeUrl(g.imageUrl)!} className="h-full w-full object-cover" alt={g.caption||`عمل ${i+1}`}/></figure>)}</div></section>}
   <section><div className="mb-3"><Title kicker="معلومات مهمة">التواصل والمعلومات</Title></div><div className="grid gap-2 md:grid-cols-3"><Info icon={Clock3} title="ساعات العمل" value={hours}/><Info icon={MapPin} title="الموقع" value={location} href={map}/><Info icon={Phone} title="الهاتف" value={`+${tel}`} href={`tel:${tel}`}/>{business.email&&<Info icon={Mail} title="البريد الإلكتروني" value={business.email} href={`mailto:${business.email}`}/>} {wa&&<Info icon={MessageCircle} title="واتساب" value={`+${wa}`} href={`https://wa.me/${wa}`}/>} {website&&<Info icon={Globe2} title="الموقع الإلكتروني" value="زيارة الموقع" href={website}/>}</div></section>
  </div>
  <footer className="border-t border-[#eee8f2] bg-white"><div className="mx-auto flex max-w-[1180px] items-center justify-between px-5 py-6 text-xs"><a href="/"><b className="text-xl tracking-[-.08em] text-[#6b38b1]">HEE</b></a><span className="text-[#817987]">هوية أعمال رقمية</span></div></footer>
  {servicesOpen&&<Sheet title={`خدمات ${business.name}`} subtitle="استعرض مجالات وخدمات المنشأة" onClose={()=>setServicesOpen(false)}>{services.map((s,i)=>{const I=IconSet[i%4];return <div key={s.id} className="flex items-center gap-3 rounded-[17px] border border-[#ebe5ef] p-4"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-[13px] bg-[#f3edf9] text-[#6333ad]"><I className="h-4 w-4"/></span><span className="min-w-0 flex-1"><b className="block text-sm">{s.name}</b><span className="mt-1 block text-[11px] leading-5 text-[#746d79]">{s.description}</span></span></div>})}</Sheet>}
  {branchesOpen&&<Sheet title={`فروع ${business.name}`} subtitle="اختر الفرع لعرض موقعه" onClose={()=>setBranchesOpen(false)}>{branches.map((b,i)=><a key={b.id} href={map} className="flex items-center gap-3 rounded-[17px] border border-[#ebe5ef] p-4"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-[#f3edf9] text-[#6333ad]"><MapPin className="h-4 w-4"/></span><span className="min-w-0 flex-1"><b className="block text-sm">{b.name}</b><span className="mt-1 block text-[11px] text-[#746d79]">{b.place}</span></span>{i===0&&<span className="rounded-full bg-emerald-50 px-2 py-1 text-[9px] font-black text-emerald-700">رئيسي</span>}<ChevronLeft className="h-4 w-4 text-[#6333ad]"/></a>)}</Sheet>}
  {share&&<div className="fixed inset-0 z-[60] grid place-items-center bg-black/40 p-5" onClick={()=>setShare(false)}><div onClick={e=>e.stopPropagation()} className="w-full max-w-sm rounded-[24px] bg-white p-5 text-center"><button onClick={()=>setShare(false)} className="float-left grid h-9 w-9 place-items-center rounded-full bg-[#f5f1f7]"><X className="h-4 w-4"/></button><img src={qrDataUrl} className="mx-auto mt-7 h-36 w-36 rounded-xl" alt="QR"/><b className="mt-4 block">شارك صفحة {business.name}</b><p className="mt-2 truncate text-[10px] text-gray-500">{publicUrl}</p></div></div>}
 </main>;
}
function Metric({icon:Icon,value,label}:{icon:any;value:string;label:string}){return <div className="px-1 text-center"><Icon className="mx-auto h-4 w-4 text-[#6333ad]"/><b className="mt-1.5 block text-[12px]">{value}</b><span className="block text-[9px] text-[#7a727f]">{label}</span></div>}
function Info({icon:Icon,title,value,href}:{icon:any;title:string;value:string;href?:string}){const body=<><span className="grid h-10 w-10 shrink-0 place-items-center rounded-[13px] bg-[#f3edf9] text-[#6333ad]"><Icon className="h-4 w-4"/></span><span className="min-w-0"><b className="block text-xs">{title}</b><span className="mt-1 block truncate text-[10px] text-[#746d79]">{value}</span></span></>;return href?<a href={href} className="flex items-center gap-3 rounded-[17px] border border-[#ebe5ef] bg-white p-4">{body}</a>:<div className="flex items-center gap-3 rounded-[17px] border border-[#ebe5ef] bg-white p-4">{body}</div>}
function Sheet({title,subtitle,onClose,children}:{title:string;subtitle:string;onClose:()=>void;children:React.ReactNode}){return <div className="fixed inset-0 z-50 flex items-end bg-black/40" onClick={onClose}><div onClick={e=>e.stopPropagation()} className="mx-auto max-h-[72vh] w-full max-w-2xl overflow-y-auto rounded-t-[28px] bg-white p-5 shadow-2xl"><div className="mb-4 flex items-center justify-between"><div><h2 className="text-xl font-black">{title}</h2><p className="mt-1 text-xs text-[#746d79]">{subtitle}</p></div><button onClick={onClose} className="grid h-10 w-10 place-items-center rounded-full bg-[#f5f1f7]"><X className="h-5 w-5"/></button></div><div className="space-y-2">{children}</div></div></div>}
