"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { BadgeCheck, BriefcaseBusiness, Building2, CalendarDays, CheckCircle2, ChevronLeft, Clock3, FileText, Globe2, Images, Mail, MapPin, MessageCircle, Phone, Share2, ShoppingBag, Sparkles, UsersRound } from "lucide-react";
import { IrMark } from "./brand/ir-logo";
import type { PageModuleState } from "../app/lib/page-modules";

type Service={id:string|number;name?:string|null;description?:string|null;isActive?:boolean|null};
type Branch={id:string|number;name?:string|null;city?:string|null;district?:string|null;address?:string|null;googleMapsLink?:string|null;isActive?:boolean|null};
type Contact={id:string|number;name?:string|null;jobTitle?:string|null;imageUrl?:string|null;phone?:string|null;whatsapp?:string|null;email?:string|null;isActive?:boolean|null;department?:{name?:string|null}|null};
type GalleryItem={id:string|number;imageUrl?:string|null;title?:string|null;isActive?:boolean|null};
type Business={id:string|number;slug:string;name:string;nameEn?:string|null;description?:string|null;shortDescription?:string|null;businessCategory?:string|null;businessType?:string|null;city?:string|null;district?:string|null;address?:string|null;country?:string|null;phone?:string|null;whatsapp?:string|null;email?:string|null;website?:string|null;logoUrl?:string|null;coverUrl?:string|null;googleMapsLink?:string|null;workingHours?:string|null;openingHours?:unknown[];isVerified?:boolean|null;services?:Service[];branches?:Branch[];contactPersons?:Contact[];galleryItems?:GalleryItem[]};
type Props={business:Business;publicUrl:string;pageModules?:PageModuleState[]};
const clean=(v?:string|null)=>String(v??"").trim();
const digits=(v?:string|null)=>clean(v).replace(/\D/g,"");
const asset=(v?:string|null)=>{const x=clean(v);return !x?null:/^(https?:\/\/|data:|blob:|\/)/i.test(x)?x:`/${x.replace(/^\/+/g,"")}`};
const external=(v?:string|null)=>{const x=clean(v);if(!x)return null;try{return new URL(/^https?:\/\//i.test(x)?x:`https://${x}`).toString()}catch{return null}};
function activityIntents(value?:string|null){const v=clean(value).toLowerCase();if(/مطعم|مقهى|ضياف|فندق/.test(v))return["استعرض القائمة","احجز أو اطلب","أقرب فرع","تواصل معنا"];if(/نقل|شحن|لوجست/.test(v))return["اطلب خدمة","تابع شحنة","تواصل مع العمليات","أقرب فرع"];if(/متجر|تجزئة|بيع/.test(v))return["تسوّق الآن","اسأل عن منتج","خدمة العملاء","أقرب فرع"];return["طلب عرض سعر","التحدث مع المبيعات","مشروع قائم","التوظيف"]}

export function PublicBusinessBio({business,publicUrl,pageModules=[]}:Props){
 const logo=asset(business.logoUrl),services=(business.services??[]).filter(x=>x.isActive!==false&&clean(x.name)).slice(0,6),branches=(business.branches??[]).filter(x=>x.isActive!==false&&clean(x.name)).slice(0,6),gallery=(business.galleryItems??[]).filter(x=>x.isActive!==false&&asset(x.imageUrl)).slice(0,6),contacts=(business.contactPersons??[]).filter(x=>x.isActive!==false&&clean(x.name));
 const groups=useMemo(()=>{const map=new Map<string,Contact[]>();for(const person of contacts){const key=clean(person.department?.name)||"فريق التواصل";map.set(key,[...(map.get(key)??[]),person])}return[...map.entries()]},[contacts]);
 const [activeDepartment,setActiveDepartment]=useState(groups[0]?.[0]??""),[copied,setCopied]=useState(false);
 const moduleMap=new Map(pageModules.map(x=>[x.id,x])),config=(id:PageModuleState["id"])=>moduleMap.get(id)?.config,contactConfig=config("contact"),profile=config("companyProfile")?.companyProfile,storeUrl=external(config("externalStore")?.externalStoreUrl),website=external(contactConfig?.websiteUrl)||external(business.website),careersUrl=external(contactConfig?.careersExternalUrl),careersEmail=clean(contactConfig?.careersEmail),activePeople=groups.find(([name])=>name===activeDepartment)?.[1]??groups[0]?.[1]??[],intents=activityIntents(business.businessType||business.businessCategory),summary=clean(business.shortDescription)||clean(business.description);
 async function share(){if(navigator.share){try{await navigator.share({title:business.name,url:publicUrl});return}catch{}}try{await navigator.clipboard.writeText(publicUrl);setCopied(true);setTimeout(()=>setCopied(false),1800)}catch{}}
 function intentHref(label:string){if(/وظيف/.test(label))return"#careers";if(/فرع/.test(label))return"#branches";if(/خدم|قائمة|تسوّق/.test(label))return"#highlights";return"#contact"}
 return <main dir="rtl" className="min-h-screen overflow-x-clip bg-[#edf4f7] text-[#071b2e] selection:bg-cyan-200">
  <div className="relative mx-auto min-h-screen w-full max-w-[520px] bg-[radial-gradient(circle_at_50%_0%,#e9fbff_0,white_26rem)] px-4 pb-28 pt-4 shadow-[0_0_80px_rgba(8,34,54,.1)] sm:px-6 lg:my-6 lg:min-h-[calc(100vh-3rem)] lg:rounded-[32px] lg:border lg:border-white/80">
   <div className="pointer-events-none sticky top-3 z-50 h-0" dir="ltr"><Link href="/" aria-label="INFRO" className="pointer-events-auto absolute left-0 grid h-14 w-14 place-items-center overflow-hidden rounded-[19px] border border-white/90 bg-[#061525] p-1.5 shadow-[0_12px_30px_rgba(8,34,54,.22)] transition hover:-translate-y-0.5 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-500"><IrMark className="h-11" priority/></Link></div>
   <div className="flex min-h-14 items-center justify-center text-[13px] font-extrabold tracking-tight text-[#29445a]">هوية أعمال رقمية</div>
   <button type="button" onClick={()=>void share()} aria-label="مشاركة الصفحة" className="absolute right-4 top-4 grid h-14 w-14 place-items-center rounded-[19px] border border-white/90 bg-white/85 text-[#0b2740] shadow-[0_10px_24px_rgba(8,34,54,.08)] backdrop-blur-xl transition hover:-translate-y-0.5 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-500 sm:right-6"><Share2 className="h-5 w-5"/></button>
   <header className="mx-auto pt-7 text-center"><div className="relative mx-auto grid h-[104px] w-[104px] place-items-center overflow-visible rounded-[28px] border border-white bg-white p-2 shadow-[0_16px_45px_rgba(12,42,63,.12)]"><span className="grid h-full w-full place-items-center overflow-hidden rounded-[22px] bg-[#f3f8fa]">{logo?<img src={logo} alt={`شعار ${business.name}`} className="h-full w-full object-contain"/>:<Building2 className="h-10 w-10 text-cyan-600"/>}</span>{business.isVerified?<BadgeCheck aria-label="منشأة موثقة" className="absolute -bottom-2 -right-2 h-8 w-8 fill-[#138cf4] text-white drop-shadow-md"/>:null}</div><h1 className="mt-5 text-[27px] font-black leading-tight tracking-[-.035em]">{business.name}</h1><p className="mt-2 text-[14px] font-bold text-[#526b7c]">{clean(business.businessCategory)||clean(business.businessType)||"منشأة أعمال"}</p><p className="mt-2 inline-flex items-center gap-1.5 text-[13px] font-medium text-[#6a8090]"><MapPin className="h-4 w-4 text-[#168af6]"/>{[clean(business.city),clean(business.district)].filter(Boolean).join("، ")||"المملكة العربية السعودية"}</p>{summary?<p className="mx-auto mt-4 max-w-[420px] text-[15px] font-semibold leading-7 text-[#274257]">{summary}</p>:null}</header>
   <section aria-labelledby="intent-title" className="mt-7"><a id="intent-title" href="#contact" className="group flex min-h-[72px] items-center gap-3 rounded-[22px] border border-[#bfeeff] bg-white/90 px-4 shadow-[0_12px_36px_rgba(0,174,234,.12)] ring-1 ring-cyan-100/70 backdrop-blur-xl transition hover:border-cyan-300 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-500"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-[15px] bg-[linear-gradient(135deg,#0878e8,#00d7cf)] text-white shadow-[0_8px_20px_rgba(0,153,220,.25)]"><MessageCircle className="h-5 w-5"/></span><span className="min-w-0 flex-1"><small className="flex items-center gap-1 text-[11px] font-black text-[#008fa6]"><Sparkles className="h-3.5 w-3.5"/>وصول ذكي</small><b className="mt-0.5 block text-[19px] tracking-[-.025em]">كيف نقدر نخدمك اليوم؟</b></span><ChevronLeft className="h-5 w-5 transition group-hover:-translate-x-1"/></a><div className="scrollbar-none -mx-4 mt-3 flex gap-2 overflow-x-auto px-4 pb-1 sm:-mx-6 sm:px-6">{intents.map(label=><a key={label} href={intentHref(label)} className="inline-flex min-h-11 shrink-0 items-center gap-2 rounded-[14px] border border-[#dce9ee] bg-white px-3.5 text-[12px] font-extrabold text-[#1c3a50] shadow-sm transition hover:border-cyan-300"><Sparkles className="h-3.5 w-3.5 text-[#119bd0]"/>{label}</a>)}</div></section>
   <section aria-label="حالة المنشأة" className="mt-4 grid grid-cols-3 divide-x-reverse divide-x divide-[#dce8ed] rounded-[18px] border border-[#e0eaee] bg-white/65 px-2 py-3 text-center backdrop-blur"><Signal icon={CheckCircle2} label="مفتوح الآن" accent/><Signal icon={Clock3} label="الرد خلال 5 دقائق"/><Signal icon={CalendarDays} label="محدّث اليوم"/></section>
   {groups.length?<section id="contact" className="mt-5 rounded-[24px] border border-[#dce8ed] bg-white/80 p-3 shadow-[0_14px_44px_rgba(12,42,63,.06)] backdrop-blur-xl"><div className="px-1 pb-3"><span className="text-[10px] font-black tracking-[.18em] text-[#009cb5]">توجيه مباشر</span><h2 className="mt-1 text-[18px] font-black tracking-[-.02em]">اختر القسم وسنوصلك بالشخص المناسب</h2></div><div className="scrollbar-none flex gap-2 overflow-x-auto pb-3">{groups.map(([name])=><button key={name} type="button" onClick={()=>setActiveDepartment(name)} aria-pressed={activeDepartment===name} className={`min-h-11 shrink-0 rounded-[14px] px-4 text-[12px] font-black transition focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-500 ${activeDepartment===name?"bg-[linear-gradient(135deg,#0878e8,#00bfc7)] text-white shadow-[0_8px_20px_rgba(0,145,208,.22)]":"bg-[#f0f6f8] text-[#405d70] hover:bg-[#e7f1f4]"}`}>{name}</button>)}</div><div className="space-y-2">{activePeople.map(person=><Person key={String(person.id)} person={person}/>)}</div></section>:null}
   <section id="highlights" className="mt-7"><div className="mb-3 flex items-end justify-between"><div><span className="text-[10px] font-black tracking-[.18em] text-[#009cb5]">استكشف</span><h2 className="mt-1 text-[20px] font-black">أبرز ما نقدمه</h2></div><span className="text-[11px] font-bold text-[#78909f]">اسحب للمزيد</span></div><div className="scrollbar-none -mx-4 flex snap-x gap-2.5 overflow-x-auto px-4 pb-2 sm:-mx-6 sm:px-6">{services.slice(0,2).map((service,index)=><Highlight key={String(service.id)} image={gallery[index]?.imageUrl} icon={BriefcaseBusiness} title={clean(service.name)} note="خدمة" href="#services"/>)}{gallery.length?<Highlight image={gallery[0]?.imageUrl} icon={Images} title="مشاريعنا" note={`${gallery.length} مختارات`} href="#projects"/>:null}{branches.length?<Highlight image={gallery[1]?.imageUrl} icon={MapPin} title="فروعنا" note={`${branches.length} مواقع`} href="#branches"/>:null}{(careersUrl||careersEmail)?<Highlight image={gallery[2]?.imageUrl} icon={BriefcaseBusiness} title="الوظائف" note="فرص جديدة" href="#careers"/>:null}</div></section>
   <section id="services" className="mt-5 grid grid-cols-2 gap-2">{profile?.visible!==false&&profile?.pdfUrl?<Destination icon={FileText} title={profile.title||"ملف الشركة"} href={profile.pdfUrl}/>:null}{storeUrl?<Destination icon={ShoppingBag} title="المتجر" href={storeUrl}/>:null}{website?<Destination icon={Globe2} title={contactConfig?.websiteType==="ONLINE_STORE"?"المتجر الإلكتروني":"الموقع الإلكتروني"} href={website}/>:null}{(business.googleMapsLink||branches[0])?<Destination icon={MapPin} title="خرائط Google" href={external(business.googleMapsLink)||external(branches[0]?.googleMapsLink)||"#branches"}/>:null}</section>
   {branches.length?<section id="branches" className="mt-7 border-t border-[#dfe9ed] pt-5"><h2 className="text-[19px] font-black">فروعنا</h2><div className="mt-3 space-y-2">{branches.map(branch=><a key={String(branch.id)} href={external(branch.googleMapsLink)||`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent([branch.name,branch.city].filter(Boolean).join(" "))}`} target="_blank" rel="noreferrer" className="flex min-h-16 items-center gap-3 rounded-[17px] bg-white px-3.5 ring-1 ring-[#e1eaee]"><span className="grid h-10 w-10 place-items-center rounded-[13px] bg-[#eaf8fb] text-[#009bb2]"><MapPin className="h-5 w-5"/></span><span className="flex-1"><b className="block text-[14px]">{clean(branch.name)}</b><small className="text-[12px] text-[#708692]">{[branch.city,branch.district].filter(Boolean).join("، ")}</small></span><ChevronLeft className="h-4 w-4"/></a>)}</div></section>:null}
   {(careersUrl||careersEmail)?<section id="careers" className="mt-7 overflow-hidden rounded-[22px] bg-[linear-gradient(135deg,#071b2e,#0b3a4e)] p-5 text-white shadow-[0_16px_42px_rgba(7,27,46,.18)]"><span className="text-[10px] font-black tracking-[.18em] text-cyan-300">انضم إلينا</span><h2 className="mt-2 text-[21px] font-black">أحدث الفرص الوظيفية</h2><p className="mt-2 text-[13px] leading-6 text-slate-300">تعرّف على الوظائف المتاحة وشاركنا خبرتك.</p><a href={careersUrl||`mailto:${careersEmail}`} className="mt-4 inline-flex min-h-11 items-center rounded-[14px] bg-white px-5 text-[13px] font-black text-[#071b2e]">استعرض الفرص</a></section>:null}
   <footer className="mt-8 flex items-center justify-between border-t border-[#dfe9ed] pt-5"><div className="flex items-center gap-2"><span className="grid h-9 w-9 place-items-center overflow-hidden rounded-[11px] bg-[#061525] p-1"><IrMark className="h-7"/></span><b className="text-sm">INFRO</b></div><span className="text-[12px] text-[#718491]">هوية أعمال رقمية · ir.sa</span></footer>
   <div className="fixed inset-x-0 bottom-3 z-40 mx-auto flex w-[calc(100%-1.5rem)] max-w-[480px] items-center gap-2 rounded-[21px] border border-white/90 bg-white/88 p-2 shadow-[0_14px_44px_rgba(7,27,46,.2)] backdrop-blur-2xl">{digits(business.whatsapp)?<QuickAction icon={MessageCircle} label="واتساب" href={`https://wa.me/${digits(business.whatsapp)}`} primary/>:null}{digits(business.phone)?<QuickAction icon={Phone} label="اتصال" href={`tel:${digits(business.phone)}`}/>:null}{clean(business.email)?<QuickAction icon={Mail} label="بريد" href={`mailto:${clean(business.email)}`}/>:null}<button type="button" onClick={()=>void share()} className="grid h-12 w-12 shrink-0 place-items-center rounded-[15px] bg-[#eef4f6]" aria-label="مشاركة"><Share2 className="h-4 w-4"/></button></div>
   {copied?<div className="fixed bottom-24 left-1/2 z-50 -translate-x-1/2 rounded-full bg-[#071b2e] px-4 py-2 text-sm font-bold text-white shadow-xl">تم نسخ الرابط</div>:null}
  </div>
 </main>
}
function Signal({icon:Icon,label,accent=false}:{icon:typeof Clock3;label:string;accent?:boolean}){return <span className={`flex min-w-0 flex-col items-center gap-1 text-[10px] font-bold ${accent?"text-emerald-700":"text-[#526b7b]"}`}><Icon className={`h-4 w-4 ${accent?"text-emerald-500":"text-[#168af6]"}`}/><span className="truncate">{label}</span></span>}
function Person({person}:{person:Contact}){const phone=digits(person.phone),whatsapp=digits(person.whatsapp),email=clean(person.email),photo=asset(person.imageUrl);return <article className="flex items-center gap-3 rounded-[17px] border border-[#e1ebef] bg-white p-3"><span className="relative grid h-12 w-12 shrink-0 place-items-center overflow-hidden rounded-[15px] bg-[#eaf3f6]">{photo?<img src={photo} alt="" className="h-full w-full object-cover"/>:<UsersRound className="h-5 w-5 text-[#496577]"/>}<i className="absolute bottom-1 right-1 h-2.5 w-2.5 rounded-full border-2 border-white bg-emerald-500"/></span><span className="min-w-0 flex-1"><b className="block truncate text-[14px]">{clean(person.name)}</b><small className="block truncate text-[11px] text-[#6a7e8b]">{clean(person.jobTitle)||"ممثل المنشأة"}</small><small className="mt-1 block text-[10px] font-bold text-emerald-600">متاح الآن</small></span><span className="flex gap-1">{whatsapp?<MiniAction label={`واتساب ${person.name}`} href={`https://wa.me/${whatsapp}`} icon={MessageCircle} green/>:null}{phone?<MiniAction label={`اتصال ${person.name}`} href={`tel:${phone}`} icon={Phone}/>:null}{email?<MiniAction label={`بريد ${person.name}`} href={`mailto:${email}`} icon={Mail}/>:null}</span></article>}
function MiniAction({label,href,icon:Icon,green=false}:{label:string;href:string;icon:typeof Phone;green?:boolean}){return <a aria-label={label} href={href} className={`grid h-10 w-10 place-items-center rounded-[13px] ${green?"bg-emerald-50 text-emerald-700":"bg-blue-50 text-blue-700"}`}><Icon className="h-4 w-4"/></a>}
function Highlight({image,icon:Icon,title,note,href}:{image?:string|null;icon:typeof Images;title:string;note:string;href:string}){const src=asset(image);return <a href={href} className="group relative h-32 w-[132px] shrink-0 snap-start overflow-hidden rounded-[20px] bg-[#dcecf1] shadow-sm">{src?<img src={src} alt="" className="h-full w-full object-cover transition duration-500 group-hover:scale-105"/>:<span className="grid h-full place-items-center"><Icon className="h-7 w-7 text-[#168fa8]"/></span>}<span className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-[#061525]/90 to-transparent px-3 pb-3 pt-8 text-white"><b className="block truncate text-[13px]">{title}</b><small className="text-[10px] text-white/75">{note}</small></span></a>}
function Destination({icon:Icon,title,href}:{icon:typeof Globe2;title:string;href:string}){const isHttp=href.startsWith("http");return <a href={href} target={isHttp?"_blank":undefined} rel={isHttp?"noreferrer":undefined} className="flex min-h-[72px] items-center gap-3 rounded-[18px] border border-[#e0e9ed] bg-white px-3.5 shadow-sm transition hover:-translate-y-0.5"><span className="grid h-10 w-10 place-items-center rounded-[13px] bg-[#eaf8fb] text-[#058da5]"><Icon className="h-5 w-5"/></span><b className="text-[13px]">{title}</b></a>}
function QuickAction({icon:Icon,label,href,primary=false}:{icon:typeof Phone;label:string;href:string;primary?:boolean}){return <a href={href} target={href.startsWith("http")?"_blank":undefined} rel={href.startsWith("http")?"noreferrer":undefined} className={`flex h-12 min-w-0 flex-1 items-center justify-center gap-2 rounded-[15px] px-3 text-[12px] font-black ${primary?"bg-[linear-gradient(135deg,#0878e8,#00bfc7)] text-white shadow-[0_8px_20px_rgba(0,145,208,.2)]":"bg-[#eef4f6] text-[#183247]"}`}><Icon className="h-4 w-4"/><span className="truncate">{label}</span></a>}
