"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { BadgeCheck, BriefcaseBusiness, ChevronDown, Clock3, Globe2, Headphones, Images, Info, Mail, MapPin, MessageCircle, Phone, Share2, Sparkles, UserRound, type LucideIcon } from "lucide-react";
import { IrMark } from "./brand/ir-logo";
import { getPublicOpenStatus } from "./public/public-page-utils";

type Service={id:string|number;name?:string|null;description?:string|null;isActive?:boolean|null};
type Branch={id:string|number;name?:string|null;city?:string|null;district?:string|null;address?:string|null;googleMapsLink?:string|null;isActive?:boolean|null};
type Contact={id:string|number;name?:string|null;jobTitle?:string|null;imageUrl?:string|null;phone?:string|null;whatsapp?:string|null;isActive?:boolean|null;department?:{name?:string|null}|null};
type Department={id:string|number;name?:string|null;isActive?:boolean|null;contacts?:Contact[]};
type OpeningHour={dayOfWeek?:number|null;opensAt?:string|null;closesAt?:string|null;secondOpensAt?:string|null;secondClosesAt?:string|null;isClosed?:boolean|null};
type GalleryItem={id:string|number;imageUrl?:string|null;title?:string|null;isActive?:boolean|null};
type PublicBusiness={id:string|number;slug:string;name:string;nameEn?:string|null;description?:string|null;shortDescription?:string|null;businessCategory?:string|null;businessType?:string|null;city?:string|null;district?:string|null;address?:string|null;country?:string|null;phone?:string|null;whatsapp?:string|null;email?:string|null;website?:string|null;logoUrl?:string|null;coverUrl?:string|null;googleMapsLink?:string|null;workingHours?:string|null;isVerified?:boolean|null;services?:Service[];branches?:Branch[];contactPersons?:Contact[];departments?:Department[];openingHours?:OpeningHour[];galleryItems?:GalleryItem[]};
type Props={business:PublicBusiness;qrDataUrl:string;publicUrl:string;demoMode?:boolean};
type PanelKey="about"|"services"|"branches"|"team"|"work"|"contact";
type IconType=LucideIcon;

const clean=(value?:string|null)=>String(value??"").trim();
const digits=(value?:string|null)=>clean(value).replace(/\D/g,"");
function assetUrl(value?:string|null){const raw=clean(value);if(!raw)return null;if(/^(https?:\/\/|data:|blob:)/i.test(raw))return raw;if(raw.startsWith("/"))return raw;if(/^[\w@./-]+\.(png|jpe?g|webp|gif|avif|svg)(\?.*)?$/i.test(raw))return`/${raw.replace(/^\/+/,"")}`;return null}
function externalUrl(value?:string|null){const raw=clean(value);if(!raw)return null;try{const url=new URL(/^https?:\/\//i.test(raw)?raw:`https://${raw}`);if(!/^https?:$/.test(url.protocol)||!url.hostname.includes(".")||/\s/.test(url.href))return null;return url.toString()}catch{return null}}
function googleMapSearch(query:string){const value=clean(query);return value?`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(value)}`:null}
function serviceCount(n:number){if(n===1)return"خدمة واحدة";if(n===2)return"خدمتان";if(n>=3&&n<=10)return`${n} خدمات`;return`${n} خدمة`}
function branchCount(n:number){if(n===1)return"فرع واحد";if(n===2)return"فرعان";if(n>=3&&n<=10)return`${n} فروع`;return`${n} فرعًا`}
function teamCount(n:number){if(n===1)return"ممثل واحد للمنشأة";if(n===2)return"ممثّلان للمنشأة";return`${n} من ممثلي المنشأة`}
function photoCount(n:number){if(n===1)return"صورة مختارة";if(n===2)return"صورتان مختارتان";return`${n} صور مختارة`}
function methodCount(n:number){if(n===1)return"وسيلة تواصل واحدة";if(n===2)return"وسيلتا تواصل";return`${n} وسائل تواصل`}

export function PublicBusinessPageV10Light({business,publicUrl}:Props){
  const[openPanel,setOpenPanel]=useState<PanelKey|null>(null);
  const[shareStatus,setShareStatus]=useState<"idle"|"copied"|"failed">("idle");
  const phone=digits(business.phone),whatsapp=digits(business.whatsapp);
  const location=[clean(business.city),clean(business.district)].filter(Boolean).join("، ");
  const category=clean(business.businessCategory)||clean(business.businessType);
  const about=clean(business.shortDescription)||clean(business.description);
  const logo=assetUrl(business.logoUrl),cover=assetUrl(business.coverUrl),website=externalUrl(business.website);
  const businessMap=externalUrl(business.googleMapsLink)||googleMapSearch(location);
  const activeServices=(business.services??[]).filter(s=>s.isActive!==false&&clean(s.name));
  const activeBranches=(business.branches??[]).filter(b=>b.isActive!==false&&clean(b.name));
  const services=activeServices.slice(0,8),branches=activeBranches.slice(0,8);
  const contacts=useMemo(()=>{const direct=(business.contactPersons??[]).filter(c=>c.isActive!==false&&clean(c.name));if(direct.length)return direct.slice(0,8);return(business.departments??[]).filter(d=>d.isActive!==false).flatMap(d=>(d.contacts??[]).filter(c=>c.isActive!==false&&clean(c.name)).map(c=>({...c,department:c.department??{name:d.name}}))).slice(0,8)},[business.contactPersons,business.departments]);
  const gallery=(business.galleryItems??[]).filter(i=>i.isActive!==false&&assetUrl(i.imageUrl)).slice(0,6);
  const openingHours=business.openingHours??[];
  const activeHours=openingHours.find(i=>!i.isClosed&&i.opensAt&&i.closesAt);
  const workingHours=clean(business.workingHours)||(activeHours?`${activeHours.opensAt} - ${activeHours.closesAt}`:"");
  const openStatus=getPublicOpenStatus(openingHours.flatMap((item,index)=>typeof item.dayOfWeek==="number"?[{id:`v11-${index}`,dayOfWeek:item.dayOfWeek,opensAt:item.opensAt??null,closesAt:item.closesAt??null,secondOpensAt:item.secondOpensAt??null,secondClosesAt:item.secondClosesAt??null,isClosed:Boolean(item.isClosed)}]:[]));
  const openNow=openStatus.label===null?null:openStatus.label==="مفتوح الآن";
  const quickActions=[phone?{key:"phone",href:`tel:${phone}`,icon:Phone,label:"اتصال"}:null,whatsapp?{key:"whatsapp",href:`https://wa.me/${whatsapp}`,icon:MessageCircle,label:"واتساب",primary:true}:null,businessMap?{key:"map",href:businessMap,icon:MapPin,label:"الموقع"}:null,{key:"share",onClick:()=>void share(),icon:Share2,label:"مشاركة"}].filter(Boolean) as Array<{key:string;href?:string;onClick?:()=>void;icon:IconType;label:string;primary?:boolean}>;
  const contactMethods=[phone,whatsapp,clean(business.email),website].filter(Boolean).length;
  const toggle=(key:PanelKey)=>setOpenPanel(current=>current===key?null:key);
  async function share(){setShareStatus("idle");if(navigator.share){try{await navigator.share({title:business.name,url:publicUrl});return}catch(error){if(error instanceof DOMException&&error.name==="AbortError")return}}try{if(!navigator.clipboard?.writeText)throw new Error("clipboard-unavailable");await navigator.clipboard.writeText(publicUrl);setShareStatus("copied")}catch{setShareStatus("failed")}}

  return <main dir="rtl" className="min-h-screen overflow-x-clip bg-[#eaf2f0] text-[#102527] selection:bg-[#82f4dc]">
    <div className="relative mx-auto min-h-screen w-full max-w-[760px] bg-[#f8fbfa] shadow-[0_0_70px_rgba(4,25,28,.14)]">
      <header className="relative isolate overflow-hidden bg-[#061b1e] text-white">
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_12%_0%,rgba(0,229,168,.24),transparent_34%),radial-gradient(circle_at_88%_28%,rgba(0,180,216,.2),transparent_30%),linear-gradient(155deg,#061b1e_0%,#0a2a2e_72%,#071d20_100%)]"/>
        <div className="absolute -left-20 top-28 h-48 w-48 rounded-full border border-white/10"/><div className="absolute -right-24 top-12 h-56 w-56 rounded-full border border-[#35e4cb]/15"/>
        <div className="relative z-10 flex items-center justify-between px-4 pb-4 pt-4 sm:px-7 sm:pt-6">
          <Link href="/" aria-label="iR - الصفحة الرئيسية" className="grid h-12 w-12 place-items-center rounded-2xl border border-white/10 bg-white/[.07] backdrop-blur-xl transition hover:bg-white/[.11] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#35e4cb]"><IrMark className="h-8" priority/></Link>
          <button type="button" onClick={()=>void share()} aria-label="مشاركة الصفحة" className="grid h-11 w-11 place-items-center rounded-2xl border border-white/10 bg-white/[.07] text-[#6df0dd] backdrop-blur-xl transition hover:bg-white/[.12] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#35e4cb] active:scale-95"><Share2 className="h-[18px] w-[18px]"/></button>
        </div>
        <div className="relative z-10 px-3 pb-7 sm:px-7 sm:pb-9">
          <div className="relative h-[190px] overflow-hidden rounded-[28px] border border-white/10 bg-[#0b3034] shadow-[0_22px_55px_rgba(0,0,0,.28)] sm:h-[260px] sm:rounded-[34px]">
            {cover?<img src={cover} alt="" className="h-full w-full object-cover" onError={e=>{e.currentTarget.style.display="none"}}/>:<div className="grid h-full place-items-center"><Sparkles className="h-12 w-12 text-[#35e4cb]/50"/></div>}
            <div className="absolute inset-0 bg-[linear-gradient(180deg,transparent_24%,rgba(3,18,20,.2)_55%,rgba(3,18,20,.9)_100%)]"/>
            <div className="absolute inset-x-4 bottom-4 flex items-end gap-3 sm:inset-x-6 sm:bottom-6 sm:gap-4">
              <div className="relative grid h-[82px] w-[82px] shrink-0 place-items-center overflow-hidden rounded-[25px] border-2 border-white/80 bg-white shadow-[0_12px_30px_rgba(0,0,0,.28)] sm:h-[102px] sm:w-[102px] sm:rounded-[30px]"><Sparkles className="h-8 w-8 text-[#00a99d]"/>{logo?<img src={logo} alt={business.name} className="absolute inset-0 h-full w-full object-cover" onError={e=>{e.currentTarget.style.display="none"}}/>:null}</div>
              <div className="min-w-0 flex-1 pb-1 text-right"><div className="flex items-center gap-2"><h1 className="truncate text-[23px] font-black leading-tight tracking-tight sm:text-[34px]">{business.name}</h1>{business.isVerified?<span title="منشأة موثقة"><BadgeCheck className="h-5 w-5 shrink-0 fill-[#35e4cb] text-[#062124] sm:h-6 sm:w-6"/></span>:null}</div>{category?<p className="mt-1 truncate text-[11px] font-bold text-white/65 sm:text-sm">{category}</p>:null}</div>
            </div>
          </div>
          <div className="mt-4 flex flex-wrap items-center gap-2 text-[10px] sm:text-xs">
            {location?<span className="inline-flex min-h-8 items-center gap-1.5 rounded-full border border-white/10 bg-white/[.06] px-3 text-white/75"><MapPin className="h-3.5 w-3.5 text-[#55e8d3]"/>{location}</span>:null}
            {workingHours?<span className="inline-flex min-h-8 items-center gap-1.5 rounded-full border border-white/10 bg-white/[.06] px-3 text-white/75"><Clock3 className="h-3.5 w-3.5 text-[#55e8d3]"/>{workingHours}</span>:null}
            {openNow!==null?<span className={`inline-flex min-h-8 items-center gap-1.5 rounded-full border px-3 font-black ${openNow?"border-emerald-300/20 bg-emerald-300/10 text-[#84f3cf]":"border-white/10 bg-white/[.06] text-white/60"}`}><span className={`h-2 w-2 rounded-full ${openNow?"bg-[#53edb7] shadow-[0_0_12px_#53edb7]":"bg-white/35"}`}/>{openNow?"مفتوح الآن":"مغلق الآن"}</span>:null}
          </div>
          {about?<p className="mt-4 max-w-[640px] text-[12.5px] leading-7 text-white/68 sm:text-sm sm:leading-8">{about}</p>:null}
        </div>
      </header>

      <div aria-live="polite" aria-atomic="true" className="pointer-events-none fixed inset-x-3 top-4 z-[160] mx-auto max-w-[340px] text-center">{shareStatus==="copied"?<span className="inline-flex rounded-full bg-[#071d20] px-4 py-2 text-xs font-bold text-white shadow-xl">تم نسخ رابط الصفحة</span>:null}{shareStatus==="failed"?<span className="inline-flex rounded-full bg-rose-700 px-4 py-2 text-xs font-bold text-white shadow-xl">تعذر نسخ الرابط. حاول مرة أخرى.</span>:null}</div>
      <div className="px-3 pb-9 pt-3 sm:px-7 sm:pb-12 sm:pt-5">
        <section aria-label="ملخص المنشأة" className="grid grid-cols-3 divide-x divide-x-reverse divide-[#dce9e6] rounded-[22px] border border-[#d7e6e3] bg-white px-1 py-3.5 shadow-[0_12px_35px_rgba(7,37,39,.055)] sm:rounded-[26px] sm:py-4"><Metric icon={BadgeCheck} value={business.isVerified?"موثق":"رقمية"} label={business.isVerified?"هوية معتمدة":"هوية أعمال"}/><Metric icon={BriefcaseBusiness} value={String(activeServices.length)} label={activeServices.length===1?"خدمة":"خدمات"}/><Metric icon={MapPin} value={String(activeBranches.length)} label={activeBranches.length===1?"فرع":"فروع"}/></section>
        <section aria-label="إجراءات سريعة" className="mt-3 grid gap-2" style={{gridTemplateColumns:`repeat(${Math.max(quickActions.length,1)},minmax(0,1fr))`}}>{quickActions.map(({key,...action})=><QuickAction key={key}{...action}/>)}</section>
        <div data-public-highlights-slot className="mt-4"/>
        <div className="mb-3 mt-5 flex items-end justify-between gap-3 px-1"><div><span className="text-[9px] font-black tracking-[.17em] text-[#008f87]" dir="ltr">BUSINESS PROFILE</span><h2 className="mt-1 text-[18px] font-black tracking-tight text-[#0b282b] sm:text-xl">اكتشف المنشأة</h2></div><span className="text-[10px] font-bold text-[#718583]">كل ما تحتاجه في مكان واحد</span></div>
        <section className="space-y-2.5">
          {about?<AccordionRow title="عن المنشأة" subtitle="تعرف على هويتنا وقصتنا" icon={Info} open={openPanel==="about"} onClick={()=>toggle("about")}><p className="text-[13px] leading-7 text-[#526866]">{clean(business.description)||about}</p></AccordionRow>:null}
          <AccordionRow title="خدماتنا" subtitle={activeServices.length?`${serviceCount(activeServices.length)} متاحة`:"لم تتم إضافة خدمات بعد"} icon={BriefcaseBusiness} open={openPanel==="services"} onClick={()=>toggle("services")}>{services.length?<div className="grid gap-2 sm:grid-cols-2">{services.map(service=><div key={String(service.id)} className="rounded-2xl border border-[#deebe8] bg-[#f3f8f7] px-4 py-3.5"><b className="block text-[13px] text-[#123033]">{clean(service.name)}</b>{clean(service.description)?<p className="mt-1.5 text-[11px] leading-5 text-[#667b79]">{clean(service.description)}</p>:null}</div>)}</div>:<EmptyState text="لم تتم إضافة خدمات بعد."/>}</AccordionRow>
          <AccordionRow title="فروعنا" subtitle={activeBranches.length?branchCount(activeBranches.length):"لم تتم إضافة فروع بعد"} icon={MapPin} open={openPanel==="branches"} onClick={()=>toggle("branches")}>{branches.length?<div className="space-y-2">{branches.map(branch=>{const place=[branch.city,branch.district,branch.address].filter(Boolean).join("، ");const map=externalUrl(branch.googleMapsLink)||googleMapSearch(place);const content=<><div><b className="block text-[13px]">{clean(branch.name)}</b>{place?<span className="mt-1 block text-[11px] text-[#667b79]">{place}</span>:null}</div><MapPin className="h-4 w-4 text-[#008f87]"/></>;return map?<a key={String(branch.id)} href={map} target="_blank" rel="noreferrer" className="flex min-h-14 items-center justify-between rounded-2xl border border-[#deebe8] bg-[#f3f8f7] px-4 py-3 transition hover:border-[#9eddd2]">{content}</a>:<div key={String(branch.id)} className="flex min-h-14 items-center justify-between rounded-2xl border border-[#deebe8] bg-[#f3f8f7] px-4 py-3">{content}</div>})}</div>:<EmptyState text="لم تتم إضافة فروع بعد."/>}</AccordionRow>
          {contacts.length?<AccordionRow title="فريق العمل" subtitle={teamCount(contacts.length)} icon={UserRound} open={openPanel==="team"} onClick={()=>toggle("team")}><div className="space-y-2">{contacts.map(contact=>{const image=assetUrl(contact.imageUrl),contactPhone=digits(contact.phone),contactWhatsapp=digits(contact.whatsapp);return <div key={String(contact.id)} className="flex items-center gap-3 rounded-2xl border border-[#deebe8] bg-[#f3f8f7] px-3 py-3"><div className="relative grid h-11 w-11 shrink-0 place-items-center overflow-hidden rounded-2xl bg-[#dff7f2]"><UserRound className="h-5 w-5 text-[#008f87]"/>{image?<img src={image} alt="" className="absolute inset-0 h-full w-full object-cover"/>:null}</div><div className="min-w-0 flex-1"><b className="block truncate text-[12px]">{clean(contact.name)}</b><span className="mt-0.5 block truncate text-[10px] text-[#667b79]">{clean(contact.jobTitle)||clean(contact.department?.name)||"فريق العمل"}</span></div>{contactPhone?<a href={`tel:${contactPhone}`} className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-white text-[#008f87] shadow-sm" aria-label={`اتصال بـ${clean(contact.name)}`}><Phone className="h-4 w-4"/></a>:null}{contactWhatsapp?<a href={`https://wa.me/${contactWhatsapp}`} target="_blank" rel="noreferrer" className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-[#dff8ef] text-emerald-700" aria-label={`واتساب ${clean(contact.name)}`}><MessageCircle className="h-4 w-4"/></a>:null}</div>})}</div></AccordionRow>:null}
          {gallery.length?<AccordionRow title="أعمالنا" subtitle={photoCount(gallery.length)} icon={Images} open={openPanel==="work"} onClick={()=>toggle("work")}><div className="grid grid-cols-2 gap-2 sm:grid-cols-3">{gallery.map(item=><div key={String(item.id)} className="aspect-[4/3] overflow-hidden rounded-2xl bg-[#edf5f3]"><img src={assetUrl(item.imageUrl)||""} alt={clean(item.title)||"من أعمال المنشأة"} loading="lazy" className="h-full w-full object-cover transition duration-500 hover:scale-[1.03] motion-reduce:transition-none"/></div>)}</div></AccordionRow>:null}
          <AccordionRow title="معلومات التواصل" subtitle={contactMethods?methodCount(contactMethods):"بيانات التواصل"} icon={Headphones} open={openPanel==="contact"} onClick={()=>toggle("contact")}>{contactMethods||businessMap?<div className="divide-y divide-[#dce9e6] rounded-2xl border border-[#deebe8] bg-[#f3f8f7] px-4">{phone?<ContactLine icon={Phone} label="الهاتف" value={clean(business.phone)||phone} href={`tel:${phone}`}/>:null}{whatsapp?<ContactLine icon={MessageCircle} label="واتساب" value={clean(business.whatsapp)||whatsapp} href={`https://wa.me/${whatsapp}`} green/>:null}{business.email?<ContactLine icon={Mail} label="البريد الإلكتروني" value={business.email} href={`mailto:${business.email}`}/>:null}{website?<ContactLine icon={Globe2} label="الموقع الإلكتروني" value={clean(business.website)} href={website}/>:null}{businessMap?<ContactLine icon={MapPin} label="الموقع" value={location||clean(business.address)||"فتح الخريطة"} href={businessMap}/>:null}</div>:<EmptyState text="لم تتم إضافة بيانات تواصل بعد."/>}</AccordionRow>
        </section>
        <footer className="mt-8 rounded-[24px] bg-[#071d20] px-5 py-5 text-white shadow-[0_18px_45px_rgba(7,29,32,.16)]"><Link href="/" className="flex items-center justify-between gap-4 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#35e4cb]" aria-label="أنشئ هويتك الرقمية عبر iR"><div className="flex items-center gap-3"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl border border-white/10 bg-white/[.06]"><IrMark className="h-8"/></span><p className="max-w-[190px] text-[10px] font-semibold leading-5 text-white/55">هوية رقمية وتسويقية موثوقة لمنشأتك</p></div><span className="shrink-0 rounded-full border border-[#35e4cb]/25 bg-[#35e4cb]/10 px-3 py-2 text-[9px] font-black text-[#6df0dd]" dir="ltr">ir.sa</span></Link></footer>
      </div>
    </div>
  </main>
}

function Metric({icon:Icon,value,label}:{icon:IconType;value:string;label:string}){return <div className="px-1 text-center"><Icon className="mx-auto h-4 w-4 text-[#008f87]"/><b className="mt-1.5 block text-[13px] text-[#102527]">{value}</b><span className="mt-0.5 block text-[9px] font-semibold text-[#718583]">{label}</span></div>}
function QuickAction({href,onClick,icon:Icon,label,primary}:{href?:string;onClick?:()=>void;icon:IconType;label:string;primary?:boolean}){const c=`flex min-h-[62px] flex-col items-center justify-center rounded-[18px] border text-[10px] font-black shadow-[0_8px_24px_rgba(7,37,39,.045)] transition focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#00a99d] active:scale-[.98] ${primary?"border-[#0cae91] bg-[linear-gradient(145deg,#073437,#0c5552)] text-white":"border-[#d7e6e3] bg-white text-[#19383b] hover:border-[#9eddd2]"}`;const body=<><Icon className={`mb-1.5 h-[18px] w-[18px] ${primary?"text-[#65f1d4]":"text-[#008f87]"}`}/>{label}</>;return href?<a href={href} target={href.startsWith("http")?"_blank":undefined} rel={href.startsWith("http")?"noreferrer":undefined} className={c}>{body}</a>:<button type="button" onClick={onClick} className={c}>{body}</button>}
function AccordionRow({title,subtitle,icon:Icon,open,onClick,children}:{title:string;subtitle:string;icon:IconType;open:boolean;onClick:()=>void;children:React.ReactNode}){return <section className="overflow-hidden rounded-[21px] border border-[#d7e6e3] bg-white shadow-[0_9px_28px_rgba(7,37,39,.045)]"><button type="button" onClick={onClick} aria-expanded={open} className="flex min-h-[66px] w-full items-center gap-3 px-4 py-3 text-right transition hover:bg-[#f7fbfa] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-[#00a99d]"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-[14px] bg-[#e2f8f4] text-[#008f87]"><Icon className="h-[18px] w-[18px]"/></span><span className="min-w-0 flex-1"><b className="block text-[13.5px] text-[#102527]">{title}</b><span className="mt-0.5 block text-[9.5px] font-semibold text-[#718583]">{subtitle}</span></span><span className={`grid h-8 w-8 place-items-center rounded-full bg-[#f0f7f5] text-[#008f87] transition-transform duration-200 motion-reduce:transition-none ${open?"rotate-180":""}`}><ChevronDown className="h-4 w-4"/></span></button>{open?<div className="border-t border-[#e5efed] px-3.5 pb-4 pt-3.5 sm:px-4">{children}</div>:null}</section>}
function ContactLine({icon:Icon,label,value,href,green}:{icon:IconType;label:string;value:string;href:string;green?:boolean}){return <a href={href} target={href.startsWith("http")?"_blank":undefined} rel={href.startsWith("http")?"noreferrer":undefined} className="flex min-h-14 items-center gap-3 py-3 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#00a99d]"><span className={`grid h-9 w-9 shrink-0 place-items-center rounded-xl ${green?"bg-[#dff8ef] text-emerald-700":"bg-white text-[#008f87]"}`}><Icon className="h-4 w-4"/></span><span className="min-w-0 flex-1"><b className="block text-[10px] text-[#667b79]">{label}</b><span className="mt-0.5 block truncate text-[12px] text-[#173437]">{value}</span></span></a>}
function EmptyState({text}:{text:string}){return <div className="rounded-2xl border border-dashed border-[#cfe1dd] bg-[#f3f8f7] px-4 py-5 text-center text-[11px] leading-5 text-[#718583]">{text}</div>}
