"use client";

import {useMemo,useState} from "react";
import type {Prisma} from "@prisma/client";
import {BadgeCheck,BriefcaseBusiness,Building2,CalendarDays,ChevronDown,ChevronLeft,Clock3,FileText,Globe2,Mail,MapPin,Menu,MessageCircle,Phone,Share2,ShieldCheck,Sparkles,UserRound,UsersRound,Wrench} from "lucide-react";

type BusinessPublicPayload=Prisma.BusinessGetPayload<{include:{products:{include:{category:true}};offers:true;services:true;openingHours:true;galleryItems:true;socialLinks:true;branches:true;departments:{include:{contacts:{include:{branch:true}}}}}}>;
type Props={business:BusinessPublicPayload;qrDataUrl:string;publicUrl:string};
const digits=(v?:string|null)=>String(v??"").replace(/\D/g,"");
const phone=(v?:string|null)=>{const d=digits(v);return d.length>=8&&d.length<=15?d:null};
const text=(v?:string|null)=>{const s=String(v??"").trim();return s.length>=2&&/[\p{L}\p{N}]/u.test(s)?s:null};
const email=(v?:string|null)=>{const s=String(v??"").trim();return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(s)?s:null};
const url=(v?:string|null)=>{const s=String(v??"").trim();if(!s)return null;try{return new URL(/^https?:\/\//i.test(s)?s:`https://${s}`).toString()}catch{return null}};
const SectionTitle=({children}:{children:React.ReactNode})=><h2 className="text-[22px] font-black tracking-tight text-[#17131c] md:text-[28px]">{children}</h2>;

export function PublicBusinessPageV10({business,qrDataUrl,publicUrl}:Props){
 const [share,setShare]=useState(false),[branchesOpen,setBranchesOpen]=useState(false);
 const wa=phone(business.whatsapp),tel=phone(business.phone),mail=email(business.email),logo=url(business.logoUrl),cover=url(business.coverUrl),profile=url(business.companyProfileUrl),website=url(business.website);
 const map=url(business.googleMapsLink)||(business.address||business.city?`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent([business.address,business.district,business.city].filter(Boolean).join(" "))}`:null);
 const about=text(business.shortDescription)||text(business.description); const category=text(business.businessCategory)||text(business.businessType)||"منشأة أعمال"; const location=[text(business.city),text(business.district)].filter(Boolean).join("، ");
 const services=business.services.filter(s=>s.isActive&&text(s.name)).slice(0,8); const gallery=business.galleryItems.filter(g=>g.isActive&&url(g.imageUrl)).slice(0,8); const branches=business.branches.filter(b=>b.isActive&&text(b.name));
 const contacts=useMemo(()=>business.departments.filter(d=>d.isActive).flatMap(d=>d.contacts.filter(c=>c.isActive&&text(c.name)).map(c=>({...c,department:d.name,p:phone(c.phone),w:phone(c.whatsapp),e:email(c.email),image:url(c.imageUrl)}))).filter(c=>c.p||c.w||c.e).slice(0,6),[business.departments]);
 const hour=business.openingHours.find(h=>!h.isClosed&&h.opensAt&&h.closesAt); const hours=text(business.workingHours)||(hour?`${hour.opensAt} - ${hour.closesAt}`:null); const request=wa?`https://wa.me/${wa}?text=${encodeURIComponent(`مرحباً، أرغب في طلب خدمة من ${business.name}`)}`:null;
 const socials=[business.instagramUrl,business.tiktokUrl,business.snapchatUrl,business.xUrl,business.facebookUrl].map(url).filter(Boolean) as string[];
 return <main dir="rtl" data-renderer="hee-v10-complete-business-profile" className="min-h-screen bg-[#fbfafc] text-[#17131c]">
  <section className="relative min-h-[570px] overflow-hidden bg-[#18131d] text-white md:min-h-[610px]">
   {cover?<img src={cover} alt="" className="absolute inset-0 h-full w-full object-cover"/>:<div className="absolute inset-0 bg-[radial-gradient(circle_at_72%_28%,rgba(111,56,165,.34),transparent_32%),linear-gradient(125deg,#23192b,#110e14_65%)]"/>}
   <div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(13,10,16,.84),rgba(19,13,23,.65)_48%,rgba(13,10,16,.28))]"/>
   <div className="relative mx-auto max-w-[1280px] px-5 pb-28 pt-5 md:px-8 md:pt-7">
    <header className="flex items-center justify-between"><div className="flex items-center gap-2"><button onClick={()=>setShare(!share)} className="rounded-full bg-white px-4 py-2.5 text-xs font-black text-black"><Share2 className="ml-2 inline h-4 w-4"/>مشاركة</button>{wa&&<a href={`https://wa.me/${wa}`} className="grid h-10 w-10 place-items-center rounded-full bg-white text-emerald-600"><MessageCircle className="h-4 w-4"/></a>}{tel&&<a href={`tel:${tel}`} className="grid h-10 w-10 place-items-center rounded-full bg-white text-[#5d35a0]"><Phone className="h-4 w-4"/></a>}</div><div className="flex items-center gap-3 text-[#8154c4]"><b className="text-3xl tracking-[-.08em]">HEE</b><Menu className="text-white"/></div></header>
    {share&&<div className="absolute left-5 top-20 z-30 flex w-72 gap-3 rounded-2xl bg-white p-3 text-black shadow-2xl"><img src={qrDataUrl} className="h-14 w-14 rounded-lg" alt="QR"/><div className="min-w-0"><b className="text-xs">رابط الصفحة</b><p className="truncate text-[10px] text-gray-500">{publicUrl}</p></div></div>}
    <div className="mt-16 grid items-center gap-12 md:mt-20 md:grid-cols-[1.3fr_.7fr]">
     <div><span className="inline-flex items-center gap-1 rounded-full bg-white px-3 py-1.5 text-[11px] font-black text-[#5d35a0]"><BadgeCheck className="h-4 w-4"/>{business.isVerified?"موثق من HEE":"صفحة أعمال على HEE"}</span><h1 className="mt-5 max-w-3xl text-[38px] font-black leading-[1.12] md:text-[58px]">{business.name}</h1><h2 className="mt-2 text-[24px] font-black md:text-[34px]">{category}</h2>{about&&<p className="mt-4 max-w-2xl text-[15px] leading-8 text-white/80 md:text-[17px]">{about}</p>}<div className="mt-6 flex flex-wrap gap-3 text-sm">{location&&<span className="inline-flex items-center gap-2"><MapPin className="h-4 w-4 text-[#a77ae0]"/>{location}</span>}<span className="rounded-full bg-emerald-950/60 px-3 py-1.5 text-emerald-300">● مفتوح الآن</span></div></div>
     <div className="hidden justify-self-end md:block"><div className="grid h-60 w-60 place-items-center overflow-hidden rounded-[34px] bg-white p-7 shadow-2xl">{logo?<img src={logo} alt={business.name} className="h-full w-full object-contain"/>:<div className="text-center text-[#6035a3]"><div className="text-7xl font-black">{business.name.charAt(0)}</div><b className="mt-5 block text-xl">{business.name}</b></div>}</div></div>
    </div>
   </div>
  </section>
  <div className="relative z-20 mx-auto -mt-14 max-w-[1280px] px-4 md:px-8"><div className="grid gap-2 rounded-[24px] border border-[#e8e1ef] bg-white p-3 shadow-xl sm:grid-cols-5">{request&&<a href={request} className="flex min-h-16 items-center justify-center gap-2 rounded-2xl bg-[#5d2fa8] font-black text-white"><CalendarDays className="h-5 w-5"/>اطلب الخدمة الآن</a>}<button onClick={()=>setShare(!share)} className="flex min-h-16 items-center justify-center gap-2 rounded-2xl border border-[#e5ddeb] font-bold"><Share2 className="h-5 w-5"/>مشاركة</button>{map&&<a href={map} className="flex min-h-16 items-center justify-center gap-2 rounded-2xl border border-[#e5ddeb] font-bold"><MapPin className="h-5 w-5"/>الموقع</a>}{tel&&<a href={`tel:${tel}`} className="flex min-h-16 items-center justify-center gap-2 rounded-2xl border border-[#e5ddeb] font-bold"><Phone className="h-5 w-5"/>اتصال</a>}{wa&&<a href={`https://wa.me/${wa}`} className="flex min-h-16 items-center justify-center gap-2 rounded-2xl border border-[#e5ddeb] font-bold"><MessageCircle className="h-5 w-5"/>واتساب</a>}</div></div>
  <div className="mx-auto max-w-[1280px] space-y-12 px-4 pb-12 pt-12 md:px-8">
   {services.length>0&&<section><div className="mb-5 flex items-center justify-between"><SectionTitle>خدماتنا</SectionTitle><span className="text-sm font-bold text-[#6035a3]">عرض الكل</span></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{services.slice(0,4).map((s,i)=>{const I=[Sparkles,Wrench,Building2,BriefcaseBusiness][i%4];return <article key={s.id} className="rounded-[22px] border border-[#ece5f2] bg-white p-5 shadow-sm"><I className="h-11 w-11 text-[#6236a5]"/><h3 className="mt-4 font-black">{s.name}</h3>{text(s.description)&&<p className="mt-2 line-clamp-3 text-xs leading-6 text-[#706978]">{s.description}</p>}<span className="mt-4 inline-flex text-xs font-black text-[#6035a3]">المزيد <ChevronLeft className="h-4 w-4"/></span></article>})}</div></section>}
   {gallery.length>0&&<section><div className="mb-5 flex items-center justify-between"><SectionTitle>أعمالنا</SectionTitle><span className="text-sm font-bold text-[#6035a3]">عرض الكل</span></div><div className="grid grid-cols-2 gap-3 md:grid-cols-4">{gallery.slice(0,4).map(g=><figure key={g.id} className="relative aspect-[1.2] overflow-hidden rounded-[20px]"><img src={url(g.imageUrl)!} className="h-full w-full object-cover" alt={g.caption||business.name}/>{g.caption&&<figcaption className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/70 to-transparent p-4 pt-10 text-xs font-bold text-white">{g.caption}</figcaption>}</figure>)}</div></section>}
   {about&&<section className="grid gap-4 lg:grid-cols-[1.7fr_.8fr]"><div className="rounded-[24px] border border-[#e9e2ef] bg-[#f8f5fb] p-6 md:p-8"><SectionTitle>نبذة عن المنشأة</SectionTitle><p className="mt-4 max-w-3xl text-sm leading-8 text-[#5e5864]">{about}</p><div className="mt-7 grid grid-cols-2 gap-4 border-t border-[#e4dceb] pt-6 md:grid-cols-4"><Stat icon={ShieldCheck} value={business.isVerified?"موثق":"HEE"} label="حالة الصفحة"/><Stat icon={Building2} value={String(branches.length)} label="فروع"/><Stat icon={BriefcaseBusiness} value={String(services.length)} label="خدمات"/><Stat icon={UsersRound} value={String(contacts.length)} label="جهات تواصل"/></div></div>{profile&&<a href={profile} className="flex min-h-56 flex-col justify-between rounded-[24px] bg-gradient-to-br from-[#7040ba] to-[#4b1d82] p-6 text-white"><div><FileText className="h-12 w-12"/><h3 className="mt-4 text-xl font-black">الملف التعريفي للشركة</h3><p className="mt-2 text-xs text-white/70">تعرف على خدماتنا وخبراتنا</p></div><span className="rounded-xl bg-white py-3 text-center text-sm font-black text-[#5b2ca4]">عرض الملف</span></a>}</section>}
   {branches.length>0&&<section><SectionTitle>فروعنا</SectionTitle><button onClick={()=>setBranchesOpen(!branchesOpen)} className="mt-5 flex w-full items-center justify-between rounded-[20px] border border-[#e6deed] bg-[#faf7fc] p-5 text-right"><span><b className="block">عرض جميع الفروع</b><small className="text-gray-500">{branches.length} فروع</small></span><ChevronDown className={`h-5 w-5 text-[#6337a6] transition ${branchesOpen?'rotate-180':''}`}/></button>{branchesOpen&&<div className="mt-3 grid gap-3 md:grid-cols-2">{branches.map(b=><div key={b.id} className="rounded-[18px] border border-[#ece5f1] bg-white p-5"><b>{b.name}</b><p className="mt-2 text-xs text-gray-500">{[b.city,b.district,b.address].filter(Boolean).join("، ")}</p></div>)}</div>}</section>}
   {contacts.length>0&&<section><SectionTitle>تواصل مع فريقنا</SectionTitle><div className="mt-5 grid gap-4 md:grid-cols-2">{contacts.map(c=><article key={c.id} className="flex items-center gap-4 rounded-[22px] border border-[#ece5f1] bg-[#faf7fc] p-5">{c.image?<img src={c.image} className="h-20 w-20 rounded-full object-cover" alt=""/>:<div className="grid h-20 w-20 place-items-center rounded-full bg-white"><UserRound className="h-8 w-8 text-[#6237a6]"/></div>}<div className="flex-1"><b>{c.name}</b><p className="text-xs text-gray-500">{text(c.jobTitle)||text(c.department)}</p><div className="mt-3 flex gap-2">{c.w&&<a href={`https://wa.me/${c.w}`} className="rounded-lg border border-emerald-300 px-3 py-2 text-xs font-bold text-emerald-700">واتساب</a>}{c.p&&<a href={`tel:${c.p}`} className="rounded-lg border px-3 py-2 text-xs font-bold">اتصال</a>}</div></div></article>)}</div></section>}
   {(wa||tel||mail||hours||map)&&<section className="grid gap-4 md:grid-cols-3">{(wa||tel||mail)&&<InfoCard icon={Mail} title="تواصل سريع">{wa&&<a href={`https://wa.me/${wa}`} className="block text-emerald-700">واتساب: +{wa}</a>}{tel&&<a href={`tel:${tel}`} className="mt-2 block">اتصال: +{tel}</a>}{mail&&<a href={`mailto:${mail}`} className="mt-2 block">{mail}</a>}</InfoCard>}{hours&&<InfoCard icon={Clock3} title="ساعات العمل"><p>{hours}</p><span className="mt-4 inline-block rounded-lg bg-emerald-100 px-3 py-1 text-xs font-bold text-emerald-700">مفتوح الآن</span></InfoCard>}{map&&<a href={map}><InfoCard icon={MapPin} title="موقعنا"><p>{[business.city,business.district,business.address].filter(Boolean).join("، ")}</p><span className="mt-4 inline-block font-bold text-[#6035a3]">الاتجاهات على الخريطة</span></InfoCard></a>}</section>}
   {(website||socials.length>0)&&<section className="rounded-[24px] border border-[#e9e2ef] bg-white p-6"><div className="flex flex-wrap items-center justify-between gap-4"><SectionTitle>روابط المنشأة</SectionTitle><div className="flex flex-wrap gap-2">{website&&<a href={website} className="rounded-full border px-4 py-2 text-xs font-bold"><Globe2 className="ml-1 inline h-4 w-4"/>الموقع الإلكتروني</a>}{socials.map((s,i)=><a key={s} href={s} className="rounded-full border px-4 py-2 text-xs font-bold">شبكة اجتماعية {i+1}</a>)}</div></div></section>}
   <section className="rounded-[28px] bg-[#19141f] p-7 text-center text-white md:p-10"><h2 className="text-2xl font-black md:text-3xl">تواصل مع {business.name}</h2><p className="mx-auto mt-3 max-w-xl text-sm leading-7 text-white/65">ابدأ التواصل مباشرة مع المنشأة عبر قنواتها الرسمية.</p><div className="mt-6 flex justify-center gap-3">{wa&&<a href={`https://wa.me/${wa}`} className="rounded-xl bg-emerald-600 px-6 py-3 text-sm font-black">واتساب</a>}{tel&&<a href={`tel:${tel}`} className="rounded-xl bg-white px-6 py-3 text-sm font-black text-black">اتصال</a>}</div></section>
  </div>
  <footer className="border-t border-[#ece6f0] bg-white py-9"><div className="mx-auto flex max-w-[1280px] flex-col items-center justify-between gap-4 px-5 md:flex-row md:px-8"><div><b className="text-2xl tracking-[-.08em] text-[#6840a8]">HEE</b><p className="text-[11px] text-gray-500">صفحة أعمال رقمية موحدة</p></div><span className="text-xs text-gray-500">© HEE — صفحات الأعمال</span></div></footer>
 </main>
}
function Stat({icon:Icon,value,label}:{icon:any;value:string;label:string}){return <div className="text-center"><Icon className="mx-auto h-6 w-6 text-[#6337a6]"/><b className="mt-2 block text-lg">{value}</b><small className="text-gray-500">{label}</small></div>}
function InfoCard({icon:Icon,title,children}:{icon:any;title:string;children:React.ReactNode}){return <div className="h-full rounded-[22px] border border-[#e9e2ef] bg-[#f9f6fc] p-6"><Icon className="h-6 w-6 text-[#6337a6]"/><h3 className="mt-4 text-lg font-black">{title}</h3><div className="mt-4 text-xs leading-6 text-[#5f5965]">{children}</div></div>}
