"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { BadgeCheck, BriefcaseBusiness, Building2, ChevronLeft, FileText, Globe2, Images, Mail, MapPin, MessageCircle, Phone, Share2, ShoppingBag, UsersRound } from "lucide-react";
import { IrMark } from "./brand/ir-logo";
import type { PageModuleState } from "../app/lib/page-modules";

type Service={id:string|number;name?:string|null;description?:string|null;isActive?:boolean|null};
type Branch={id:string|number;name?:string|null;city?:string|null;district?:string|null;address?:string|null;googleMapsLink?:string|null;isActive?:boolean|null};
type Contact={id:string|number;name?:string|null;jobTitle?:string|null;imageUrl?:string|null;phone?:string|null;whatsapp?:string|null;email?:string|null;isActive?:boolean|null;department?:{name?:string|null}|null};
type GalleryItem={id:string|number;imageUrl?:string|null;title?:string|null;isActive?:boolean|null};
type Business={id:string|number;slug:string;name:string;description?:string|null;shortDescription?:string|null;businessCategory?:string|null;businessType?:string|null;city?:string|null;district?:string|null;phone?:string|null;whatsapp?:string|null;email?:string|null;website?:string|null;logoUrl?:string|null;googleMapsLink?:string|null;isVerified?:boolean|null;services?:Service[];branches?:Branch[];contactPersons?:Contact[];galleryItems?:GalleryItem[]};
type Props={business:Business;publicUrl:string;pageModules?:PageModuleState[]};

const clean=(v?:string|null)=>String(v??"").trim();
const digits=(v?:string|null)=>clean(v).replace(/\D/g,"");
const asset=(v?:string|null)=>{const x=clean(v);return !x?null:/^(https?:\/\/|data:|blob:|\/)/i.test(x)?x:`/${x.replace(/^\/+/g,"")}`};
const external=(v?:string|null)=>{const x=clean(v);if(!x)return null;try{return new URL(/^https?:\/\//i.test(x)?x:`https://${x}`).toString()}catch{return null}};

export function PublicBusinessBio({business,publicUrl,pageModules=[]}:Props){
  const [openDepartment,setOpenDepartment]=useState<string|null>(null);
  const [copied,setCopied]=useState(false);
  const logo=asset(business.logoUrl);
  const services=(business.services??[]).filter(x=>x.isActive!==false&&clean(x.name)).slice(0,6);
  const branches=(business.branches??[]).filter(x=>x.isActive!==false&&clean(x.name)).slice(0,6);
  const gallery=(business.galleryItems??[]).filter(x=>x.isActive!==false&&asset(x.imageUrl)).slice(0,4);
  const contacts=(business.contactPersons??[]).filter(x=>x.isActive!==false&&clean(x.name));
  const groups=useMemo(()=>{const map=new Map<string,Contact[]>();for(const person of contacts){const key=clean(person.department?.name)||"فريق التواصل";map.set(key,[...(map.get(key)??[]),person])}return [...map.entries()]},[contacts]);
  const moduleMap=new Map(pageModules.map(x=>[x.id,x]));
  const config=(id:PageModuleState["id"])=>moduleMap.get(id)?.config;
  const contactConfig=config("contact");
  const profile=config("companyProfile")?.companyProfile;
  const storeUrl=external(config("externalStore")?.externalStoreUrl);
  const website=external(contactConfig?.websiteUrl)||external(business.website);
  const careersUrl=external(contactConfig?.careersExternalUrl);
  const careersEmail=clean(contactConfig?.careersEmail);
  const featured=gallery[0];
  async function share(){if(navigator.share){try{await navigator.share({title:business.name,url:publicUrl});return}catch{}}try{await navigator.clipboard.writeText(publicUrl);setCopied(true);setTimeout(()=>setCopied(false),1800)}catch{}}
  const intent=[{label:"خدمات",href:"#services"},{label:"تواصل",href:"#contact"},{label:"فروع",href:"#branches"},{label:"وظائف",href:"#careers"}];
  return <main dir="rtl" className="min-h-screen bg-[#f3f7f8] text-[#071b2e] selection:bg-cyan-200">
    <div className="relative mx-auto min-h-screen w-full max-w-[1120px] bg-white px-5 pb-10 pt-5 shadow-[0_24px_80px_rgba(8,34,54,.08)] sm:px-9 lg:my-6 lg:min-h-0 lg:rounded-[30px] lg:border lg:border-[#dfe8ec] lg:px-8">
      <div className="pointer-events-none sticky top-3 z-50 h-0" dir="ltr"><Link href="/" aria-label="INFRO" className="pointer-events-auto absolute left-0 grid h-12 w-12 place-items-center overflow-hidden rounded-[15px] border border-white bg-[#061525] p-1.5 shadow-[0_12px_30px_rgba(8,34,54,.18)]"><IrMark className="h-9" priority/></Link></div>
      <div className="flex min-h-12 items-center justify-center gap-3 text-[13px] font-bold text-[#496070]"><span className="h-px w-8 bg-[#d7e2e7]"/>هوية أعمال رقمية<span className="h-px w-8 bg-[#d7e2e7]"/></div>
      <button type="button" onClick={()=>void share()} aria-label="مشاركة الصفحة" className="absolute right-5 top-5 grid h-12 w-12 place-items-center rounded-full bg-[#f3f7f9] text-[#0b2740] transition hover:bg-[#e9f2f5] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-500 sm:right-9"><Share2 className="h-5 w-5"/></button>
      <header className="mx-auto max-w-2xl pt-5 text-center"><div className="relative mx-auto grid h-24 w-24 place-items-center overflow-hidden rounded-[22px] border border-[#d8e3e8] bg-white p-2 shadow-sm">{logo?<img src={logo} alt={`شعار ${business.name}`} className="h-full w-full object-contain"/>:<Building2 className="h-9 w-9 text-cyan-600"/>}</div><div className="mt-4 flex items-center justify-center gap-2"><h1 className="text-[26px] font-black leading-tight tracking-[-.025em] sm:text-[34px]">{business.name}</h1>{business.isVerified?<BadgeCheck aria-label="منشأة موثقة" className="h-6 w-6 fill-[#168af6] text-white"/>:null}</div><p className="mt-2 text-[14px] font-bold text-[#536b7b]">{clean(business.businessCategory)||clean(business.businessType)||"منشأة أعمال"}</p><p className="mt-2 inline-flex items-center gap-1.5 text-[13px] text-[#627886]"><MapPin className="h-4 w-4"/>{[clean(business.city),clean(business.district)].filter(Boolean).join("، ")||"المملكة العربية السعودية"}</p>{clean(business.shortDescription)||clean(business.description)?<p className="mx-auto mt-3 max-w-xl text-[16px] font-bold leading-7 text-[#183247]">{clean(business.shortDescription)||clean(business.description)}</p>:null}</header>
      <nav aria-label="ماذا تبحث عنه؟" className="mx-auto mt-7 max-w-3xl border-t border-[#dfe7eb] pt-5"><h2 className="text-center text-[18px] font-black">ماذا تبحث عنه؟</h2><div className="mt-3 grid grid-cols-4 gap-2">{intent.map(item=><a key={item.label} href={item.href} className="flex min-h-12 items-center justify-center rounded-[14px] bg-[#f4f7fa] px-2 text-[13px] font-black transition hover:bg-[#eaf4ff] hover:text-[#0765d8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-500">{item.label}</a>)}</div></nav>
      {featured?<section className="mt-5 grid overflow-hidden rounded-[20px] border border-[#dfe7eb] bg-[#f8fafb] md:grid-cols-[.42fr_.58fr]"><img src={asset(featured.imageUrl)||""} alt={clean(featured.title)||"مشروع مميز"} className="h-48 w-full object-cover md:h-full"/><div className="flex flex-col justify-center p-5"><span className="text-[11px] font-black text-[#0878e8]">مشروع مميز</span><h2 className="mt-2 text-[21px] font-black">{clean(featured.title)||"من أعمالنا"}</h2><p className="mt-2 text-[13px] leading-6 text-[#607583]">تعرّف على أحدث أعمال المنشأة وخبراتها.</p></div></section>:null}
      <section id="services" className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{services.length?<BioLink icon={BriefcaseBusiness} title="خدماتنا" note={`${services.length} خدمات متاحة`} href="#services-list"/>:null}{gallery.length?<BioLink icon={Images} title="مشاريعنا" note="مختارات من أعمالنا" href="#projects"/>:null}{branches.length?<BioLink icon={MapPin} title="فروعنا" note={branches.map(x=>clean(x.city)).filter(Boolean).slice(0,3).join("، ")||`${branches.length} فروع`} href="#branches"/>:null}{profile?.visible!==false&&profile?.pdfUrl?<BioLink icon={FileText} title={profile.title||"الملف التعريفي للشركة"} note="PDF · نبذة عن الشركة" href={profile.pdfUrl}/>:null}{storeUrl?<BioLink icon={ShoppingBag} title="متجرنا" note="منتجات وخدمات مختارة" href={storeUrl}/>:null}{website?<BioLink icon={Globe2} title={contactConfig?.websiteType==="ONLINE_STORE"?"المتجر الإلكتروني":"الموقع الإلكتروني"} note={website.replace(/^https?:\/\//,"").replace(/\/$/,"")} href={website}/>:null}</section>
      {services.length?<section id="services-list" className="mt-7"><h2 className="text-[20px] font-black">خدماتنا</h2><div className="mt-3 grid gap-2 md:grid-cols-2">{services.map(service=><article key={String(service.id)} className="rounded-[16px] border border-[#dfe7eb] p-4"><h3 className="font-black">{clean(service.name)}</h3>{clean(service.description)?<p className="mt-1.5 text-[13px] leading-6 text-[#607583]">{clean(service.description)}</p>:null}</article>)}</div></section>:null}
      {groups.length?<section id="contact" className="mt-8 border-t border-[#dfe7eb] pt-6"><h2 className="text-[20px] font-black">أقسام التواصل المباشر</h2><div className="mt-3 space-y-2">{groups.map(([name,people])=><div key={name} className="overflow-hidden rounded-[16px] border border-[#dfe7eb]"><button type="button" onClick={()=>setOpenDepartment(openDepartment===name?null:name)} className="flex min-h-16 w-full items-center gap-3 px-4 text-right"><UsersRound className="h-5 w-5 text-[#0878e8]"/><span className="flex-1"><b className="block text-[15px]">{name}</b><small className="text-[12px] text-[#6a7e8b]">{people.length} من ممثلي المنشأة</small></span><ChevronLeft className={`h-5 w-5 transition ${openDepartment===name?"-rotate-90":""}`}/></button>{openDepartment===name?<div className="border-t border-[#e4ebee] p-3">{people.map(person=><Person key={String(person.id)} person={person}/>)}</div>:null}</div>)}</div></section>:null}
      {branches.length?<section id="branches" className="mt-8 border-t border-[#dfe7eb] pt-6"><h2 className="text-[20px] font-black">فروعنا</h2><div className="mt-3 grid gap-2 md:grid-cols-2">{branches.map(branch=><BioLink key={String(branch.id)} icon={MapPin} title={clean(branch.name)} note={[branch.city,branch.district].filter(Boolean).join("، ")} href={external(branch.googleMapsLink)||`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent([branch.name,branch.city].filter(Boolean).join(" "))}`}/>)}</div></section>:null}
      {(careersUrl||careersEmail)?<section id="careers" className="mt-8 rounded-[20px] bg-[#071b2e] p-5 text-white"><span className="text-[11px] font-black text-cyan-300">CAREERS</span><h2 className="mt-2 text-[22px] font-black">الوظائف المتاحة</h2><p className="mt-2 text-[13px] text-slate-300">انضم إلى فريق المنشأة واطلع على الفرص الحالية.</p><a href={careersUrl||`mailto:${careersEmail}`} className="mt-4 inline-flex min-h-11 items-center rounded-full bg-white px-5 text-[13px] font-black text-[#071b2e]">استعرض الفرص</a></section>:null}
      <section className="mt-8 grid gap-2 sm:grid-cols-3">{digits(business.whatsapp)?<ContactLink icon={MessageCircle} label="واتساب" href={`https://wa.me/${digits(business.whatsapp)}`}/>:null}{digits(business.phone)?<ContactLink icon={Phone} label="اتصال" href={`tel:${digits(business.phone)}`}/>:null}{clean(business.email)?<ContactLink icon={Mail} label="البريد" href={`mailto:${clean(business.email)}`}/>:null}</section>
      <footer className="mt-8 flex items-center justify-between border-t border-[#dfe7eb] pt-5"><div className="flex items-center gap-2"><span className="grid h-9 w-9 place-items-center overflow-hidden rounded-[10px] bg-[#061525] p-1"><IrMark className="h-7"/></span><b className="text-sm">INFRO</b></div><span className="text-[12px] text-[#718491]">هوية أعمال رقمية</span></footer>
      {copied?<div className="fixed bottom-5 left-1/2 z-50 -translate-x-1/2 rounded-full bg-[#071b2e] px-4 py-2 text-sm font-bold text-white shadow-xl">تم نسخ الرابط</div>:null}
    </div>
  </main>
}

function BioLink({icon:Icon,title,note,href}:{icon:typeof BriefcaseBusiness;title:string;note:string;href:string}){const externalLink=/^https?:|^mailto:|^tel:/.test(href);return <a href={href} target={externalLink&&href.startsWith("http")?"_blank":undefined} rel={externalLink&&href.startsWith("http")?"noreferrer":undefined} className="group flex min-h-[72px] items-center gap-3 rounded-[16px] border border-[#dfe7eb] bg-white px-4 transition hover:-translate-y-0.5 hover:border-[#b9d6e5] hover:shadow-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-500"><span className="grid h-11 w-11 place-items-center rounded-[13px] bg-[#edf6ff] text-[#0878e8]"><Icon className="h-5 w-5"/></span><span className="min-w-0 flex-1"><b className="block text-[15px]">{title}</b><small className="mt-0.5 block truncate text-[12px] text-[#6a7e8b]">{note}</small></span><ChevronLeft className="h-5 w-5 transition group-hover:-translate-x-1"/></a>}
function ContactLink({icon:Icon,label,href}:{icon:typeof Phone;label:string;href:string}){return <a href={href} target={href.startsWith("http")?"_blank":undefined} rel={href.startsWith("http")?"noreferrer":undefined} className="flex min-h-12 items-center justify-center gap-2 rounded-[14px] bg-[#071b2e] px-4 text-[14px] font-black text-white"><Icon className="h-4 w-4 text-cyan-300"/>{label}</a>}
function Person({person}:{person:Contact}){const phone=digits(person.phone),whatsapp=digits(person.whatsapp),email=clean(person.email),photo=asset(person.imageUrl);return <div className="flex items-center gap-3 border-b border-[#e5ecef] py-3 last:border-0"><span className="grid h-11 w-11 shrink-0 place-items-center overflow-hidden rounded-full bg-[#edf4f7]">{photo?<img src={photo} alt="" className="h-full w-full object-cover"/>:<UsersRound className="h-5 w-5"/>}</span><span className="min-w-0 flex-1"><b className="block truncate text-[14px]">{clean(person.name)}</b><small className="block truncate text-[12px] text-[#6a7e8b]">{clean(person.jobTitle)||"ممثل المنشأة"}</small></span><span className="flex gap-1">{whatsapp?<a aria-label={`واتساب ${person.name}`} href={`https://wa.me/${whatsapp}`} className="grid h-10 w-10 place-items-center rounded-full bg-emerald-50 text-emerald-700"><MessageCircle className="h-4 w-4"/></a>:null}{phone?<a aria-label={`اتصال ${person.name}`} href={`tel:${phone}`} className="grid h-10 w-10 place-items-center rounded-full bg-blue-50 text-blue-700"><Phone className="h-4 w-4"/></a>:null}{email?<a aria-label={`بريد ${person.name}`} href={`mailto:${email}`} className="grid h-10 w-10 place-items-center rounded-full bg-slate-100"><Mail className="h-4 w-4"/></a>:null}</span></div>}
