"use client";

import {useMemo,useState} from "react";
import type {Prisma} from "@prisma/client";
import {BadgeCheck,BriefcaseBusiness,Building2,ChevronLeft,ChevronDown,Clock3,FileText,Globe2,MapPin,MessageCircle,Phone,Share2,ShieldCheck,Sparkles,Star,UserRound,UsersRound,Wrench,CheckCircle2,X} from "lucide-react";

type BusinessPublicPayload=Prisma.BusinessGetPayload<{include:{products:{include:{category:true}};offers:true;services:true;openingHours:true;galleryItems:true;socialLinks:true;branches:true;departments:{include:{contacts:{include:{branch:true}}}}}}>;
type Props={business:BusinessPublicPayload;qrDataUrl:string;publicUrl:string};
const digits=(v?:string|null)=>String(v??"").replace(/\D/g,"");
const phone=(v?:string|null)=>{const d=digits(v);return d.length>=8&&d.length<=15?d:null};
const text=(v?:string|null)=>{const s=String(v??"").trim();return s.length>=2?s:null};
const safeUrl=(v?:string|null)=>{const s=String(v??"").trim();if(!s)return null;try{return new URL(/^https?:\/\//i.test(s)?s:`https://${s}`).toString()}catch{return null}};
const Title=({kicker,children}:{kicker?:string;children:React.ReactNode})=><div><div className="flex items-center gap-2 text-[11px] font-black text-[#6b38b1]">{kicker&&<><span className="h-1.5 w-1.5 rounded-full bg-[#6b38b1]"/>{kicker}</>}</div><h2 className="mt-1 text-[22px] font-black tracking-tight md:text-[30px]">{children}</h2></div>;

export function PublicBusinessPageV10Compact({business,qrDataUrl,publicUrl}:Props){
 const [share,setShare]=useState(false),[branchesOpen,setBranchesOpen]=useState(false);
 const wa=phone(business.whatsapp)||"966500000000",tel=phone(business.phone)||"966500000001";
 const logo=safeUrl(business.logoUrl),cover=safeUrl(business.coverUrl),profile=safeUrl(business.companyProfileUrl),website=safeUrl(business.website);
 const about=text(business.shortDescription)||text(business.description)||"نقدم حلولاً منزلية متكاملة بمعايير احترافية، وفريقاً متخصصاً يركز على الجودة والموثوقية وسرعة الاستجابة.";
 const category=text(business.businessCategory)||text(business.businessType)||"الخدمات المنزلية";
 const location=[text(business.city)||"جدة",text(business.district)||"حي الروضة"].filter(Boolean).join("، ");
 const realServices=business.services.filter(s=>s.isActive&&text(s.name)).slice(0,4);
 const services=realServices.length?realServices.map((s,i)=>({id:String(s.id),name:s.name,description:text(s.description)||["تنفيذ احترافي مع متابعة دقيقة للجودة.","حلول مرنة وسريعة تناسب احتياجك."][i%2]})):[{id:"d1",name:"تنظيف المنازل",description:"تنظيف شامل للمنازل والفلل بأفضل المعدات."},{id:"d2",name:"صيانة منزلية",description:"حلول صيانة وإصلاح للأعمال المنزلية."},{id:"d3",name:"تركيب وصيانة المكيفات",description:"تركيب وصيانة دورية لمختلف أنواع المكيفات."},{id:"d4",name:"تنظيف الواجهات",description:"تنظيف الواجهات والزجاج بعناية واحترافية."}];
 const realContacts=useMemo(()=>business.departments.filter(d=>d.isActive).flatMap(d=>d.contacts.filter(c=>c.isActive&&text(c.name)).map(c=>({id:String(c.id),name:c.name,role:text(c.jobTitle)||text(d.name)||"خدمة العملاء",p:phone(c.phone),w:phone(c.whatsapp),image:safeUrl(c.imageUrl)}))).slice(0,4),[business.departments]);
 const contacts=realContacts.length?realContacts:[{id:"c1",name:"محمد أحمد",role:"مبيعات الشركات",p:tel,w:wa,image:null},{id:"c2",name:"خالد عبدالله",role:"خدمة العملاء",p:tel,w:wa,image:null},{id:"c3",name:"سارة محمد",role:"الحجوزات والمتابعة",p:tel,w:wa,image:null},{id:"c4",name:"عبدالله سالم",role:"المشرف الميداني",p:tel,w:wa,image:null}];
 const realBranches=business.branches.filter(b=>b.isActive&&text(b.name)).slice(0,5);
 const branches=realBranches.length?realBranches.map((b,i)=>({id:String(b.id),name:b.name,place:[b.city,b.district,b.address].filter(Boolean).join("، ")||`جدة، فرع ${i+1}`})):[{id:"b1",name:"الفرع الرئيسي",place:"جدة، حي الروضة"},{id:"b2",name:"فرع شمال جدة",place:"جدة، حي الزهراء"},{id:"b3",name:"فرع جنوب جدة",place:"جدة، حي الأجاويد"}];
 const gallery=business.galleryItems.filter(g=>g.isActive&&safeUrl(g.imageUrl)).slice(0,4);
 const request=`https://wa.me/${wa}?text=${encodeURIComponent(`مرحباً، أرغب في طلب خدمة من ${business.name}`)}`;
 const map=safeUrl(business.googleMapsLink)||`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(location)}`;
 const hour=business.openingHours.find(h=>!h.isClosed&&h.opensAt&&h.closesAt);const hours=text(business.workingHours)||(hour?`${hour.opensAt} - ${hour.closesAt}`:"السبت - الخميس، 8:00 ص - 10:00 م");
 const IconSet=[Sparkles,Wrench,Building2,BriefcaseBusiness];
 const doShare=async()=>{if(typeof navigator!=="undefined"&&navigator.share){try{await navigator.share({title:business.name,url:publicUrl});return}catch{}}setShare(true)};
 return <main dir="rtl" data-renderer="hee-v10-2-compact" className="min-h-screen bg-[#fcfbfd] pb-20 text-[#18131d] md:pb-0">
  <section className="relative min-h-[455px] overflow-hidden bg-[#151018] text-white md:min-h-[620px]">
   {cover?<img src={cover} alt="" className="absolute inset-0 h-full w-full object-cover"/>:<div className="absolute inset-0 bg-[radial-gradient(circle_at_72%_25%,rgba(104,51,167,.42),transparent_30%),linear-gradient(125deg,#17111b,#0d0b0f_72%)]"/>}<div className="absolute inset-0 bg-black/30"/>
   <div className="relative mx-auto max-w-[1180px] px-5 pt-5 md:px-8 md:pt-7">
    <header className="flex items-center justify-between" dir="ltr"><a href="/" aria-label="HEE" className="group inline-flex items-center"><b className="text-[27px] font-black tracking-[-.08em] text-[#9b6bd7] transition duration-300 group-hover:scale-105 group-hover:text-[#b58be6]">HEE</b></a><div className="flex gap-2"><button onClick={doShare} aria-label="مشاركة" className="grid h-10 w-10 place-items-center rounded-full bg-white/10 backdrop-blur"><Share2 className="h-4 w-4"/></button><a href={`https://wa.me/${wa}`} aria-label="واتساب" className="grid h-10 w-10 place-items-center rounded-full bg-white text-emerald-600"><MessageCircle className="h-4 w-4"/></a></div></header>
    <div className="flex min-h-[375px] items-center py-8 md:min-h-[525px]"><div className="max-w-3xl"><span className="inline-flex items-center gap-1 rounded-full bg-white/95 px-3 py-1.5 text-[10px] font-black text-[#6035a3]"><BadgeCheck className="h-3.5 w-3.5"/>{business.isVerified?"موثق من HEE":"صفحة أعمال على HEE"}</span><h1 className="mt-4 text-[34px] font-black leading-[1.12] md:text-[58px]">{business.name}</h1><h2 className="mt-2 text-[20px] font-black md:text-[30px]">{category}</h2><p className="mt-3 line-clamp-2 max-w-2xl text-[13px] leading-6 text-white/70 md:text-base">{about}</p><div className="mt-4 flex flex-wrap items-center gap-2 text-[12px]"><span className="inline-flex items-center gap-1.5"><MapPin className="h-3.5 w-3.5 text-[#b58be6]"/>{location}</span><span className="rounded-full bg-emerald-950/70 px-2.5 py-1 text-emerald-300">● مفتوح الآن</span><button onClick={()=>setBranchesOpen(true)} className="rounded-full border border-white/15 px-2.5 py-1">{branches.length} فروع</button></div></div></div>
   </div>
  </section>
  <div className="relative z-20 mx-auto -mt-8 max-w-[1180px] px-4 md:px-8"><div className="flex items-center gap-2 rounded-[22px] border border-[#e9e2ee] bg-white p-2.5 shadow-[0_12px_35px_rgba(44,29,56,.10)]"><a href={request} className="flex h-12 flex-1 items-center justify-center gap-2 rounded-[15px] bg-[#6333ad] text-sm font-black text-white">اطلب الخدمة</a><a href={`tel:${tel}`} aria-label="اتصال" className="grid h-12 w-12 place-items-center rounded-[15px] border border-[#e7e0eb]"><Phone className="h-4 w-4"/></a><a href={map} aria-label="الموقع" className="grid h-12 w-12 place-items-center rounded-[15px] border border-[#e7e0eb]"><MapPin className="h-4 w-4"/></a><button onClick={doShare} aria-label="مشاركة" className="grid h-12 w-12 place-items-center rounded-[15px] border border-[#e7e0eb]"><Share2 className="h-4 w-4"/></button></div></div>
  <div className="mx-auto max-w-[1180px] space-y-10 px-4 pb-12 pt-8 md:space-y-14 md:px-8 md:pt-12">
   <section className="grid grid-cols-4 divide-x divide-x-reverse divide-[#ece6f0] rounded-[20px] border border-[#ece6f0] bg-white py-4"><Metric icon={ShieldCheck} value="موثق" label="موثوق"/><Metric icon={Star} value="4.9" label="التقييم"/><Metric icon={UsersRound} value="+500" label="عميل"/><Metric icon={CheckCircle2} value="+1000" label="خدمة"/></section>
   <section><Title kicker="تعرف علينا">نبذة عن المنشأة</Title><p className="mt-3 max-w-4xl text-[13px] leading-7 text-[#68606d]">{about}</p><div className="mt-4 flex flex-wrap gap-x-6 gap-y-2 text-xs"><b>+5 سنوات خبرة</b><b>{branches.length} فروع</b><b>+25 فريق العمل</b><b>98% رضا العملاء</b></div>{profile&&<a href={profile} className="mt-4 inline-flex items-center gap-2 text-xs font-black text-[#6333ad]"><FileText className="h-4 w-4"/>عرض الملف التعريفي <ChevronLeft className="h-3.5 w-3.5"/></a>}</section>
   <section><div className="mb-4 flex items-end justify-between"><Title kicker="ما نقدمه">خدماتنا</Title><span className="text-xs font-black text-[#6333ad]">عرض الكل</span></div><div className="grid gap-2.5 md:grid-cols-2">{services.map((s,i)=>{const I=IconSet[i%4];return <article key={s.id} className="flex min-h-[104px] items-center gap-4 rounded-[20px] border border-[#ebe5ef] bg-white p-4"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-[14px] bg-[#f3edf9] text-[#6333ad]"><I className="h-5 w-5"/></div><div className="min-w-0 flex-1"><h3 className="text-sm font-black">{s.name}</h3><p className="mt-1 line-clamp-2 text-[11px] leading-5 text-[#746d79]">{s.description}</p></div><ChevronLeft className="h-4 w-4 shrink-0 text-[#6333ad]"/></article>})}</div></section>
   <section><div className="mb-4"><Title kicker="أشخاص لخدمتك">فريقنا</Title></div><div className="flex gap-3 overflow-x-auto pb-2 snap-x">{contacts.map(c=><article key={c.id} className="min-w-[220px] snap-start rounded-[20px] border border-[#ebe5ef] bg-white p-4"><div className="flex items-center gap-3"><div className="grid h-12 w-12 shrink-0 place-items-center overflow-hidden rounded-full bg-[#f1eaf7]">{c.image?<img src={c.image} alt="" className="h-full w-full object-cover"/>:<UserRound className="h-5 w-5 text-[#6333ad]"/>}</div><div className="min-w-0"><h3 className="truncate text-sm font-black">{c.name}</h3><p className="truncate text-[11px] text-[#766e7b]">{c.role}</p></div></div><div className="mt-3 flex gap-2"><a href={`https://wa.me/${c.w||wa}`} className="flex-1 rounded-xl bg-emerald-50 py-2 text-center text-[11px] font-black text-emerald-700">واتساب</a><a href={`tel:${c.p||tel}`} className="flex-1 rounded-xl bg-[#f7f4f9] py-2 text-center text-[11px] font-black">اتصال</a></div></article>)}</div></section>
   {gallery.length>0&&<section><div className="mb-4"><Title kicker="أعمال مختارة">أعمالنا</Title></div><div className="flex gap-3 overflow-x-auto pb-2">{gallery.map((g,i)=><figure key={g.id} className="relative aspect-[1.25] min-w-[220px] overflow-hidden rounded-[20px] bg-[#eee8f3]"><img src={safeUrl(g.imageUrl)!} className="h-full w-full object-cover" alt={g.caption||`عمل ${i+1}`}/></figure>)}</div></section>}
   <section><button onClick={()=>setBranchesOpen(true)} className="flex w-full items-center justify-between rounded-[20px] border border-[#e8e1ed] bg-[#faf7fc] p-4 text-right"><span><b className="block text-sm">فروعنا</b><span className="mt-1 block text-[11px] text-[#746d79]">{branches.length} فروع — اضغط لعرض المواقع</span></span><span className="grid h-10 w-10 place-items-center rounded-full bg-white text-[#6333ad]"><ChevronDown className="h-5 w-5"/></span></button></section>
   <section className="grid gap-2 md:grid-cols-3"><Info icon={Clock3} title="ساعات العمل" text={hours}/><Info icon={MapPin} title="الموقع" text={location}/><Info icon={MessageCircle} title="التواصل" text={`واتساب +${wa}`}/></section>
   <section className="rounded-[24px] bg-[#17121c] px-5 py-7 text-white md:flex md:items-center md:justify-between md:px-8"><div><h2 className="text-xl font-black">جاهز لطلب خدمتك؟</h2><p className="mt-2 text-xs leading-6 text-white/60">تواصل مباشرة مع {business.name} عبر القنوات الرسمية.</p></div><div className="mt-4 flex gap-2 md:mt-0"><a href={request} className="rounded-xl bg-emerald-500 px-6 py-2.5 text-xs font-black">واتساب</a><a href={`tel:${tel}`} className="rounded-xl border border-white/20 px-6 py-2.5 text-xs font-black">اتصال</a></div></section>
  </div>
  <footer className="border-t border-[#eee8f2] bg-white"><div className="mx-auto flex max-w-[1180px] items-center justify-between px-5 py-6 text-xs"><a href="/"><b className="text-xl tracking-[-.08em] text-[#6b38b1]">HEE</b></a><div className="flex gap-4 text-[#655d6a]">{website&&<a href={website}><Globe2 className="inline h-3.5 w-3.5"/> الموقع</a>}<a href="/">منصة HEE</a></div></div></footer>
  <div className="fixed inset-x-0 bottom-0 z-40 border-t border-[#e9e2ee] bg-white/95 p-2.5 backdrop-blur md:hidden"><div className="mx-auto flex max-w-md gap-2"><a href={request} className="flex h-12 flex-1 items-center justify-center rounded-[14px] bg-[#6333ad] text-sm font-black text-white">اطلب الخدمة</a><a href={`https://wa.me/${wa}`} aria-label="واتساب" className="grid h-12 w-12 place-items-center rounded-[14px] bg-emerald-500 text-white"><MessageCircle className="h-5 w-5"/></a><a href={`tel:${tel}`} aria-label="اتصال" className="grid h-12 w-12 place-items-center rounded-[14px] border border-[#e7e0eb]"><Phone className="h-5 w-5"/></a></div></div>
  {branchesOpen&&<div className="fixed inset-0 z-50 flex items-end bg-black/40" onClick={()=>setBranchesOpen(false)}><div onClick={e=>e.stopPropagation()} className="mx-auto max-h-[72vh] w-full max-w-2xl overflow-y-auto rounded-t-[28px] bg-white p-5 shadow-2xl"><div className="mb-4 flex items-center justify-between"><div><h2 className="text-xl font-black">فروع {business.name}</h2><p className="mt-1 text-xs text-[#746d79]">اختر الفرع الأقرب إليك</p></div><button onClick={()=>setBranchesOpen(false)} className="grid h-10 w-10 place-items-center rounded-full bg-[#f5f1f7]"><X className="h-5 w-5"/></button></div><div className="space-y-2">{branches.map((b,i)=><a key={b.id} href={map} className="flex items-center gap-3 rounded-[18px] border border-[#ebe5ef] p-4"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-[#f3edf9] text-[#6333ad]"><MapPin className="h-4 w-4"/></span><span className="min-w-0 flex-1"><b className="block text-sm">{b.name}</b><span className="mt-1 block text-[11px] text-[#746d79]">{b.place}</span></span>{i===0&&<span className="rounded-full bg-emerald-50 px-2 py-1 text-[9px] font-black text-emerald-700">رئيسي</span>}<ChevronLeft className="h-4 w-4 text-[#6333ad]"/></a>)}</div></div></div>}
  {share&&<div className="fixed inset-0 z-[60] grid place-items-center bg-black/40 p-5" onClick={()=>setShare(false)}><div onClick={e=>e.stopPropagation()} className="w-full max-w-sm rounded-[24px] bg-white p-5 text-center"><button onClick={()=>setShare(false)} className="float-left grid h-9 w-9 place-items-center rounded-full bg-[#f5f1f7]"><X className="h-4 w-4"/></button><img src={qrDataUrl} className="mx-auto mt-7 h-36 w-36 rounded-xl" alt="QR"/><b className="mt-4 block">شارك صفحة {business.name}</b><p className="mt-2 truncate text-[10px] text-gray-500">{publicUrl}</p></div></div>}
 </main>;
}
function Metric({icon:Icon,value,label}:{icon:any;value:string;label:string}){return <div className="px-1 text-center"><Icon className="mx-auto h-4 w-4 text-[#6333ad]"/><b className="mt-1.5 block text-[13px]">{value}</b><span className="block text-[9px] text-[#7a727f]">{label}</span></div>}
function Info({icon:Icon,title,text}:{icon:any;title:string;text:string}){return <div className="flex items-center gap-3 rounded-[18px] border border-[#ebe5ef] bg-white p-4"><span className="grid h-10 w-10 place-items-center rounded-[13px] bg-[#f3edf9] text-[#6333ad]"><Icon className="h-4 w-4"/></span><div><b className="block text-xs">{title}</b><span className="mt-1 block text-[10px] text-[#746d79]">{text}</span></div></div>}
