"use client";
import {useMemo,useState} from "react";
import type {Prisma} from "@prisma/client";
import {BadgeCheck,Building2,ChevronDown,Clock3,FileText,Headphones,Mail,MapPin,MessageCircle,MoreHorizontal,Phone,Share2,ShoppingBag,UserRound,UsersRound} from "lucide-react";
type B=Prisma.BusinessGetPayload<{include:{products:{include:{category:true}};offers:true;services:true;openingHours:true;galleryItems:true;socialLinks:true;branches:true;departments:{include:{contacts:{include:{branch:true}}}}}}>;
type Props={business:B;qrDataUrl:string;publicUrl:string};
const digits=(v?:string|null)=>String(v??"").replace(/\D/g,"");
const ph=(v?:string|null)=>{const d=digits(v);return d.length>=8&&d.length<=15?d:null};
const tx=(v?:string|null)=>{const s=String(v??"").trim();return s.length>=2&&/[\p{L}\p{N}]/u.test(s)?s:null};
const em=(v?:string|null)=>{const s=String(v??"").trim();return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(s)?s:null};
const ur=(v?:string|null)=>{const s=String(v??"").trim();if(!/^https?:\/\//i.test(s))return null;try{return new URL(s).toString()}catch{return null}};
export function PublicBusinessPageV8({business,qrDataUrl,publicUrl}:Props){
 const [share,setShare]=useState(false),[branchesOpen,setBranchesOpen]=useState(false);
 const wa=ph(business.whatsapp),tel=ph(business.phone),logo=ur(business.logoUrl),store=ur(business.website),profile=ur(business.companyProfileUrl);
 const location=[tx(business.city),tx(business.district)].filter(Boolean).join("، ");
 const hours=tx(business.workingHours)||(()=>{const h=business.openingHours.find(x=>!x.isClosed&&x.opensAt&&x.closesAt);return h?`${h.opensAt} - ${h.closesAt}`:null})();
 const map=ur(business.googleMapsLink)||(business.address||business.city?`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent([business.address,business.city,business.district].filter(Boolean).join(" "))}`:null);
 const services=business.services.filter(s=>s.isActive&&tx(s.name)).slice(0,8),gallery=business.galleryItems.filter(g=>g.isActive&&ur(g.imageUrl)),branches=business.branches.filter(b=>b.isActive&&tx(b.name));
 const contacts=useMemo(()=>business.departments.filter(d=>d.isActive).flatMap(d=>d.contacts.filter(c=>c.isActive&&tx(c.name)).map(c=>({...c,department:d.name,p:ph(c.phone),w:ph(c.whatsapp),e:em(c.email)}))).filter(c=>c.p||c.w||c.e),[business.departments]);
 const about=tx(business.shortDescription)||tx(business.description)||`${business.name} — صفحة الأعمال الرسمية على HEE.`;
 const actions=[{l:"واتساب",I:MessageCircle,h:wa?`https://wa.me/${wa}`:null,a:true},{l:"اتصال",I:Phone,h:tel?`tel:${tel}`:null},{l:"الموقع",I:MapPin,h:map},{l:"التواصل",I:UsersRound,h:"#hee-directory"}];
 return <main dir="rtl" data-renderer="hee-v8-modern-business-app" className="min-h-screen bg-[#f4f7f5] pb-28 text-[#12211b] md:pb-10"><div className="mx-auto w-full max-w-[430px] md:max-w-[1120px] md:px-8 md:pt-8"><div className="overflow-hidden bg-[#f4f7f5] md:rounded-[34px] md:border md:border-[#e4ebe7] md:shadow-[0_30px_90px_-55px_rgba(0,55,38,.35)]">
 <header className="relative overflow-hidden bg-[#053f33] px-5 pb-[78px] pt-5 text-white md:px-10 md:pb-[86px] md:pt-8"><div className="pointer-events-none absolute inset-0 [background:radial-gradient(circle_at_75%_5%,rgba(30,175,119,.32),transparent_30%),radial-gradient(circle_at_0%_80%,rgba(16,112,82,.55),transparent_38%),linear-gradient(145deg,#032e27,#064d3d_58%,#05392f)]"/><div className="relative flex items-center justify-between"><button onClick={()=>setShare(v=>!v)} className="grid h-11 w-11 place-items-center rounded-full border border-white/20 bg-white/[.07]" aria-label="مشاركة"><Share2 className="h-[18px] w-[18px]"/></button><span className="inline-flex h-9 items-center gap-2 rounded-full border border-white/15 bg-white/[.08] px-3.5 text-[11px] font-bold"><BadgeCheck className="h-4 w-4 text-[#62e3a8]"/>{business.isVerified?"موثق":"صفحة أعمال HEE"}</span></div>
 <div className="relative mx-auto mt-7 flex max-w-[760px] flex-col items-center text-center"><div className="grid h-[104px] w-[104px] place-items-center overflow-hidden rounded-[30px] border border-white/25 bg-white shadow-[0_18px_45px_rgba(0,0,0,.28)]">{logo?<img src={logo} alt={business.name} className="h-full w-full object-contain p-2"/>:<span className="text-[40px] font-black text-[#07805f]">{business.name.charAt(0)}</span>}</div><h1 className="mt-5 text-[26px] font-black leading-tight tracking-[-.04em] md:text-[34px]">{business.name}</h1><p className="mt-2 text-[13px] font-semibold text-white/70">{tx(business.businessCategory)||tx(business.businessType)||"منشأة أعمال"}</p><span className="mt-3 inline-flex items-center gap-2 rounded-full bg-[#0d6d54] px-3.5 py-1.5 text-[11px] font-bold text-[#8aefc1]"><i className="h-2 w-2 rounded-full bg-[#48e49d]"/>منشأة تعمل بنشاط</span></div>
 <div className="relative mx-auto mt-7 grid max-w-[680px] grid-cols-3 divide-x-reverse divide-x divide-white/15"><div className="px-2 text-center"><MapPin className="mx-auto h-5 w-5 text-[#62dfa7]"/><span className="mt-2 block truncate text-[11px] font-semibold">{location||"الموقع"}</span></div><div className="px-2 text-center"><Clock3 className="mx-auto h-5 w-5 text-[#62dfa7]"/><span className="mt-2 block truncate text-[11px] font-semibold">{hours||"ساعات العمل"}</span></div><div className="px-2 text-center"><UserRound className="mx-auto h-5 w-5 text-[#62dfa7]"/><span className="mt-2 block text-[11px] font-semibold">صفحة موحدة</span></div></div>{share?<div className="relative mx-auto mt-5 flex max-w-sm items-center gap-3 rounded-2xl border border-white/15 bg-white/10 p-3"><img src={qrDataUrl} alt="QR" className="h-14 w-14 rounded-xl bg-white p-1"/><span className="min-w-0 truncate text-[10px] text-white/70">{publicUrl}</span></div>:null}</header>
 <section className="relative z-20 -mt-[52px] px-4 md:px-10"><div className="grid grid-cols-4 gap-1 rounded-[26px] border border-[#e6ebe8] bg-white p-2.5 shadow-[0_18px_45px_-25px_rgba(0,55,39,.4)]">{actions.map(({l,I,h,a})=><a key={l} href={h||"#"} target={h?.startsWith("http")?"_blank":undefined} rel="noreferrer" className={`flex min-h-[82px] flex-col items-center justify-center gap-2 rounded-[20px] ${h?"active:scale-[.97]":"pointer-events-none opacity-30"} ${a?"bg-[#edf9f4]":""}`}><span className={`grid h-10 w-10 place-items-center rounded-full ${a?"bg-[#0aa36f] text-white":"bg-[#f7f5fb] text-[#57358e]"}`}><I className="h-5 w-5"/></span><b className="text-[11px]">{l}</b></a>)}</div></section>
 <div className="space-y-4 px-4 pb-8 pt-4 md:px-10">{(profile||store)?<section className="grid grid-cols-2 overflow-hidden rounded-[22px] border border-[#e7ece9] bg-white">{profile?<a href={profile} target="_blank" className="flex min-h-[78px] items-center gap-3 border-l border-[#edf0ee] px-4"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#edf9f4] text-[#0a9b6a]"><FileText className="h-5 w-5"/></span><span><b className="block text-[12px]">الملف التعريفي</b><small className="mt-1 block text-[10px] text-[#8a9490]">تعرف علينا</small></span></a>:<div/>}{store?<a href={store} target="_blank" className="flex min-h-[78px] items-center gap-3 px-4"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#edf9f4] text-[#0a9b6a]"><ShoppingBag className="h-5 w-5"/></span><span><b className="block text-[12px]">المتجر الإلكتروني</b><small className="mt-1 block text-[10px] text-[#8a9490]">تسوق خدماتنا</small></span></a>:null}</section>:null}
 <div className="md:grid md:grid-cols-12 md:gap-4"><section className="rounded-[24px] border border-[#e5ebe7] bg-white p-5 md:col-span-7 md:p-6"><div className="flex items-center justify-between"><div><span className="text-[10px] font-bold text-[#0b9b6b]">نبذة مختصرة</span><h2 className="mt-1 text-[18px] font-black">عن المنشأة</h2></div><span className="grid h-11 w-11 place-items-center rounded-2xl bg-[#edf9f4] text-[#0b9b6b]"><Building2 className="h-5 w-5"/></span></div><p className="mt-4 text-[13px] leading-7 text-[#64706b]">{about}</p><button className="mt-3 inline-flex items-center gap-1 text-[11px] font-bold text-[#0a9869]">عرض المزيد <ChevronDown className="h-4 w-4"/></button></section>
 <section id="hee-directory" className="mt-4 rounded-[24px] border border-[#e5ebe7] bg-white p-5 md:col-span-5 md:mt-0 md:p-6"><div className="flex items-center justify-between"><div><span className="text-[10px] font-bold text-[#0b9b6b]">تواصل مباشرة</span><h2 className="mt-1 text-[18px] font-black">الجهة المناسبة</h2></div><span className="grid h-11 w-11 place-items-center rounded-2xl bg-[#f4f1fa] text-[#59378d]"><Headphones className="h-5 w-5"/></span></div><div className="mt-4 space-y-2">{contacts.length?contacts.slice(0,4).map(c=><div key={c.id} className="flex items-center gap-3 rounded-[18px] border border-[#edf0ee] bg-[#fbfcfb] p-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[#edf9f4] text-[#0a9c6b]"><UserRound className="h-5 w-5"/></span><div className="min-w-0 flex-1"><b className="block truncate text-[12px]">{c.name}</b><span className="mt-0.5 block truncate text-[10px] text-[#929b97]">{tx(c.jobTitle)||c.department}</span></div><div className="flex gap-1">{c.w?<a href={`https://wa.me/${c.w}`} className="grid h-9 w-9 place-items-center rounded-xl bg-[#eaf8f2] text-[#079d69]"><MessageCircle className="h-4 w-4"/></a>:null}{c.p?<a href={`tel:${c.p}`} className="grid h-9 w-9 place-items-center rounded-xl bg-[#f3f0f9] text-[#59388d]"><Phone className="h-4 w-4"/></a>:null}{c.e?<a href={`mailto:${c.e}`} className="grid h-9 w-9 place-items-center rounded-xl bg-[#f3f0f9] text-[#59388d]"><Mail className="h-4 w-4"/></a>:null}</div></div>):<p className="rounded-[18px] bg-[#f8faf9] p-4 text-center text-[11px] text-[#8f9994]">لم تُضف جهات تواصل بعد</p>}</div></section></div>
 {services.length?<section className="rounded-[24px] border border-[#e5ebe7] bg-white p-5"><div className="mb-4"><span className="text-[10px] font-bold text-[#0b9b6b]">اكتشف ما نقدمه</span><h2 className="mt-1 text-[18px] font-black">خدماتنا</h2></div><div className="-mx-5 flex snap-x gap-3 overflow-x-auto px-5 [scrollbar-width:none] md:mx-0 md:grid md:grid-cols-4 md:px-0">{services.map((s,i)=>{const img=ur(s.imageUrl)||ur(gallery[i%Math.max(gallery.length,1)]?.imageUrl);return <article key={s.id} className="min-w-[190px] snap-start overflow-hidden rounded-[20px] border border-[#e8ecea] bg-white md:min-w-0"><div className="h-[126px] overflow-hidden bg-[#e1eee9]">{img?<img src={img} alt={s.name} className="h-full w-full object-cover"/>:<div className="grid h-full place-items-center"><Building2 className="h-9 w-9 text-[#6b9c8b]/50"/></div>}</div><div className="p-3.5"><b className="block text-[12px]">{s.name}</b></div></article>})}</div></section>:null}
 <section className="overflow-hidden rounded-[24px] border border-[#e5ebe7] bg-white"><button onClick={()=>setBranchesOpen(v=>!v)} className="flex w-full items-center justify-between p-5"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-[#edf9f4] text-[#0a9b6a]"><MapPin className="h-5 w-5"/></span><div className="text-right"><h2 className="text-[17px] font-black">فروعنا</h2><p className="mt-1 text-[10px] text-[#8c9691]">{branches.length?`${branches.length} فروع متاحة`:"لم تُضف فروع بعد"}</p></div></div><ChevronDown className={`h-5 w-5 transition ${branchesOpen?"rotate-180":""}`}/></button>{branchesOpen&&branches.length?<div className="space-y-2 border-t border-[#edf0ee] p-4">{branches.map(b=><article key={b.id} className="rounded-[18px] bg-[#f8faf9] p-4"><b className="text-[13px]">{b.name}</b><p className="mt-1 text-[10px] leading-5 text-[#7d8883]">{[tx(b.city),tx(b.district),tx(b.address)].filter(Boolean).join("، ")||"تفاصيل الموقع غير مضافة"}</p></article>)}</div>:null}</section></div></div></div></div>
 <nav className="fixed inset-x-0 bottom-0 z-[90] mx-auto max-w-[430px] px-3 pb-[max(8px,env(safe-area-inset-bottom))] md:hidden"><div className="grid h-[72px] grid-cols-5 items-center rounded-[24px] border border-[#e3e9e6] bg-white/95 px-2 shadow-[0_-10px_35px_-20px_rgba(0,50,35,.35)] backdrop-blur-xl"><a href="#hee-directory" className="flex flex-col items-center gap-1 text-[#4e3a76]"><UsersRound className="h-5 w-5"/><span className="text-[9px] font-bold">التواصل</span></a><a href={tel?`tel:${tel}`:"#"} className={`flex flex-col items-center gap-1 text-[#59645f] ${tel?"":"pointer-events-none opacity-30"}`}><Phone className="h-5 w-5"/><span className="text-[9px] font-bold">اتصال</span></a><div className="relative h-full"><a href={wa?`https://wa.me/${wa}`:"#"} className={`absolute -top-4 left-1/2 flex h-[72px] w-[72px] -translate-x-1/2 flex-col items-center justify-center gap-1 rounded-[22px] bg-[#08a56f] text-white shadow-[0_12px_28px_-10px_rgba(8,165,111,.65)] ${wa?"":"pointer-events-none opacity-40"}`}><MessageCircle className="h-7 w-7"/><span className="text-[9px] font-black">واتساب</span></a></div><a href={map||"#"} target={map?"_blank":undefined} className={`flex flex-col items-center gap-1 text-[#59645f] ${map?"":"pointer-events-none opacity-30"}`}><MapPin className="h-5 w-5"/><span className="text-[9px] font-bold">الموقع</span></a><button onClick={()=>setShare(v=>!v)} className="flex flex-col items-center gap-1 text-[#59645f]"><MoreHorizontal className="h-5 w-5"/><span className="text-[9px] font-bold">المزيد</span></button></div></nav>
 </main>;
}
