import { Prisma } from "@prisma/client";
import Link from "next/link";
import { ArrowRight, ClipboardList, LockKeyhole, PackageCheck, ShieldCheck, Truck } from "lucide-react";
import { notFound } from "next/navigation";
import { transitionBusinessStoreOrderAdminAction } from "../../../actions/admin-business-store-orders";
import { requireAdmin } from "../../../lib/admin";
import { db } from "../../../lib/db";

type AuditRow = { id: string; fromStatus: string; toStatus: string; paymentStatus: string; note: string | null; createdAt: Date; actorName: string; actorEmail: string };
const resultMessages: Record<string, string> = { updated: "تم تحديث حالة الطلب وتسجيل العملية في سجل التدقيق.", "payment-required": "لا يمكن إدخال الطلب في دورة التنفيذ قبل أن تكون حالة الدفع paid.", "refund-required": "لا يمكن إلغاء طلب مدفوع إداريًا دون مسار refund/reversal موثق.", "invalid-transition": "الانتقال المطلوب غير صالح من الحالة الحالية.", conflict: "تغير الطلب بالتزامن مع العملية. أعد مراجعة حالته الحالية.", missing: "الطلب لم يعد موجودًا.", invalid: "الطلب أو الحالة المطلوبة غير صالحين." };
function sar(v:number){return new Intl.NumberFormat("ar-SA",{style:"currency",currency:"SAR",maximumFractionDigits:2}).format(v/100)}
function json(v:unknown){try{return JSON.stringify(v,null,2)}catch{return "{}"}}
function tone(v:string){if(["paid","fulfilled"].includes(v))return "bg-emerald-400/15 text-emerald-200 border-emerald-400/20";if(["failed","cancelled","refunded"].includes(v))return "bg-rose-400/15 text-rose-200 border-rose-400/20";return "bg-white/10 text-slate-200 border-white/10"}
export default async function AdminStoreOrderDetailPage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{result?:string}>}){
 await requireAdmin(); const {id}=await params; const result=String((await searchParams).result??"");
 const order=await db.businessStoreOrder.findUnique({where:{id},include:{business:{select:{id:true,name:true,slug:true,owner:{select:{name:true,email:true}}}},items:{orderBy:{createdAt:"asc"}}}}); if(!order)notFound();
 const audit=await db.$queryRaw<AuditRow[]>(Prisma.sql`SELECT a."id",a."fromStatus",a."toStatus",a."paymentStatus",a."note",a."createdAt",u."name" AS "actorName",u."email" AS "actorEmail" FROM "BusinessStoreOrderAudit" a JOIN "User" u ON u."id"=a."actorUserId" WHERE a."orderId"=${order.id} ORDER BY a."createdAt" DESC LIMIT 100`);
 const next=order.status==="draft"?["cancelled"]:order.status==="submitted"?["processing","cancelled"]:order.status==="processing"?["shipped","cancelled"]:order.status==="shipped"?["fulfilled"]:[];
 return <main className="min-h-screen bg-[#f6f9f9] px-4 py-7 text-[#10282c] sm:px-6" dir="rtl"><div className="mx-auto max-w-6xl space-y-5">
  <Link href="/admin/store-orders" className="inline-flex items-center gap-2 text-xs font-black text-[#087f78]"><ArrowRight className="h-4 w-4"/>ORDER COMMAND</Link>
  <header className="overflow-hidden rounded-[30px] bg-[#07181b] p-6 text-white shadow-[0_24px_70px_-38px_rgba(7,24,27,.7)] sm:p-8"><div className="flex flex-wrap items-start justify-between gap-6"><div><div className="flex items-center gap-2 text-[#35e4cb]"><ClipboardList className="h-5 w-5"/><span className="text-[11px] font-black tracking-[.18em]">INFRO · ORDER CONTROL ROOM</span></div><h1 className="mt-4 text-2xl font-black sm:text-3xl">{order.businessNameSnapshot}</h1><code className="mt-2 block text-[10px] text-slate-400" dir="ltr">{order.id}</code><div className="mt-5 flex flex-wrap gap-2"><span className={`rounded-full border px-3 py-1 text-[10px] font-black ${tone(order.status)}`}>{order.status}</span><span className={`rounded-full border px-3 py-1 text-[10px] font-black ${tone(order.paymentStatus)}`}>{order.paymentStatus}</span></div></div><div className="min-w-[180px] rounded-[24px] border border-white/10 bg-white/[.06] p-5 text-left"><span className="text-[10px] font-bold tracking-widest text-slate-400">ORDER VALUE</span><b className="mt-2 block text-3xl text-[#35e4cb]">{sar(order.total)}</b><span className="mt-2 block text-[10px] text-slate-400">Snapshot مالي تاريخي</span></div></div></header>
  {result&&resultMessages[result]?<div role="status" className={`rounded-2xl border px-4 py-3 text-sm font-bold ${result==="updated"?"border-emerald-200 bg-emerald-50 text-emerald-800":"border-amber-200 bg-amber-50 text-amber-800"}`}>{resultMessages[result]}</div>:null}
  <section className="grid gap-3 md:grid-cols-4"><Metric label="SUBTOTAL" value={sar(order.subtotal)}/><Metric label="VAT" value={sar(order.vatAmount)}/><Metric label="SHIPPING" value={sar(order.shippingAmount)}/><Metric label="TOTAL" value={sar(order.total)} accent/></section>
  <section className="grid gap-4 lg:grid-cols-2"><Card title="المنشأة والمالك" eyebrow="ACCOUNT"><Row label="المنشأة" value={order.business.name}/><Row label="Slug" value={order.business.slug}/><Row label="المالك" value={order.business.owner.name}/><Row label="البريد" value={order.business.owner.email}/><Row label="Public snapshot" value={order.publicUrlSnapshot}/></Card><Card title="وجهة الشحن" eyebrow="FULFILMENT"><Row label="الاسم" value={order.shippingName??"—"}/><Row label="الهاتف" value={order.shippingPhone??"—"}/><Row label="البريد" value={order.shippingEmail??"—"}/><Row label="العنوان" value={[order.shippingAddressLine1,order.shippingAddressLine2,order.shippingDistrict,order.shippingCity,order.shippingPostalCode,order.shippingCountry].filter(Boolean).join("، ")||"—"}/></Card></section>
  <section className="rounded-[26px] border border-[#dce8e7] bg-white p-5"><div className="flex items-start justify-between gap-4"><div><span className="text-[10px] font-black tracking-[.16em] text-[#008f87]">COMMERCIAL SNAPSHOT</span><h2 className="mt-1 font-black">العناصر التاريخية</h2></div><PackageCheck className="h-5 w-5 text-[#00bfae]"/></div><p className="mt-2 text-xs leading-6 text-slate-500">هذه snapshots للطلب وليست قراءة من الكتالوج الحالي؛ تغيير المنتج المركزي لا يغيّر التاريخ التجاري.</p><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[760px] text-right text-xs"><thead className="text-slate-400"><tr className="border-b"><th className="py-2">SKU</th><th>المنتج</th><th>الكمية</th><th>سعر الوحدة</th><th>الإجمالي</th><th>التخصيص</th></tr></thead><tbody>{order.items.map(item=><tr key={item.id} className="border-b border-[#edf3f2] last:border-0"><td className="py-3"><code dir="ltr">{item.sku}</code></td><td className="font-bold">{item.nameSnapshot}</td><td>{item.quantity}</td><td>{sar(item.unitPrice)}</td><td className="font-black text-[#087f78]">{sar(item.lineTotal)}</td><td><pre className="max-w-xs whitespace-pre-wrap text-[10px] text-slate-500">{json(item.customizationSnapshot)}</pre></td></tr>)}</tbody></table></div></section>
  <section className="grid gap-4 lg:grid-cols-2"><Card title="Identity snapshot" eyebrow="IDENTITY"><pre dir="ltr" className="max-h-72 overflow-auto whitespace-pre-wrap rounded-2xl bg-[#f5f9f8] p-3 text-[10px] text-slate-600">{json(order.identitySnapshot)}</pre></Card><Card title="Order customization snapshot" eyebrow="CUSTOMIZATION"><pre dir="ltr" className="max-h-72 overflow-auto whitespace-pre-wrap rounded-2xl bg-[#f5f9f8] p-3 text-[10px] text-slate-600">{json(order.customizationSnapshot)}</pre></Card></section>
  <section className="rounded-[28px] bg-[#07181b] p-5 text-white sm:p-6"><div className="flex items-start gap-3"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-[#35e4cb]/10 text-[#35e4cb]"><LockKeyhole className="h-5 w-5"/></span><div><span className="text-[10px] font-black tracking-[.16em] text-[#35e4cb]">SAFE TRANSITIONS</span><h2 className="mt-1 font-black">الانتقالات التشغيلية</h2><p className="mt-1 max-w-3xl text-xs leading-6 text-slate-400">لا يوجد تغيير حر للحالة. الانتقالات محددة مسبقًا وتنفذ داخل transaction مع locking وDB guard، وهذه الواجهة لا تغيّر حالة الدفع.</p></div></div><div className="mt-5 grid gap-3 md:grid-cols-2">{next.map(target=>{const blockedByPayment=["processing","shipped","fulfilled"].includes(target)&&order.paymentStatus!=="paid";const blockedRefund=target==="cancelled"&&order.paymentStatus==="paid";return <form key={target} action={transitionBusinessStoreOrderAdminAction} className="rounded-[22px] border border-white/10 bg-white/[.05] p-4"><input type="hidden" name="orderId" value={order.id}/><input type="hidden" name="nextStatus" value={target}/><b className="text-sm">{order.status} → <span className="text-[#35e4cb]">{target}</span></b><textarea name="note" maxLength={500} rows={2} placeholder="ملاحظة تشغيلية اختيارية" className="mt-3 w-full rounded-xl border border-white/10 bg-white/[.06] p-2 text-xs text-white outline-none placeholder:text-slate-500 focus:border-[#35e4cb]/50"/><button disabled={blockedByPayment||blockedRefund} className="mt-2 min-h-10 rounded-xl bg-[#35e4cb] px-4 text-xs font-black text-[#07181b] disabled:cursor-not-allowed disabled:bg-slate-700 disabled:text-slate-400">تنفيذ الانتقال</button>{blockedByPayment?<p className="mt-2 text-[10px] font-bold text-amber-300">يتطلب paymentStatus=paid.</p>:null}{blockedRefund?<p className="mt-2 text-[10px] font-bold text-amber-300">الطلب مدفوع؛ يلزم refund/reversal موثق قبل الإلغاء.</p>:null}</form>})}{!next.length?<div className="rounded-2xl border border-white/10 bg-white/[.05] p-5 text-sm text-slate-400">لا توجد انتقالات إدارية صالحة من الحالة الحالية.</div>:null}</div></section>
  <section className="grid gap-4 lg:grid-cols-[.8fr_1.2fr]"><Card title="الدفع والشحن" eyebrow="PROVIDERS"><div className="flex items-center gap-2 text-[#008f87]"><Truck className="h-4 w-4"/><b className="text-xs">Provider state</b></div><Row label="Payment provider" value={order.paymentProvider??"غير مربوط"}/><Row label="Provider reference" value={order.providerPaymentId??"غير موجود"}/><p className="mt-3 rounded-xl bg-amber-50 p-3 text-xs leading-6 text-amber-800">لا يوجد Shipment Provider أو tracking integration حقيقي حاليًا. shipped حالة تشغيلية فقط ولا نعرض رقم تتبع وهميًا.</p></Card><Card title="سجل التدقيق" eyebrow="AUDIT TRAIL"><div className="space-y-2">{audit.map((entry,index)=><div key={entry.id} className="rounded-2xl border border-[#e6efee] p-3 text-xs"><div className="flex flex-wrap justify-between gap-2"><b><span className="text-[#008f87]">{String(index+1).padStart(2,"0")}</span> · {entry.fromStatus} → {entry.toStatus}</b><span className="text-slate-400">{new Intl.DateTimeFormat("ar-SA",{dateStyle:"medium",timeStyle:"short"}).format(entry.createdAt)}</span></div><p className="mt-1 text-slate-500">الدفع: {entry.paymentStatus} · {entry.actorName} ({entry.actorEmail})</p>{entry.note?<p className="mt-2 rounded-lg bg-[#f5f9f8] p-2">{entry.note}</p>:null}</div>)}{!audit.length?<p className="text-xs text-slate-400">لا توجد انتقالات إدارية مسجلة بعد.</p>:null}</div></Card></section>
  <div className="flex gap-2 rounded-2xl border border-[#cfe7e4] bg-[#effaf8] p-4 text-xs leading-6 text-[#185e59]"><ShieldCheck className="mt-0.5 h-4 w-4 shrink-0"/><p><b>Financial integrity:</b> حالات الدفع تأتي من مسار الدفع الموثق ولا تُدار من شاشة العمليات.</p></div>
 </div></main>
}
function Card({title,eyebrow,children}:{title:string;eyebrow:string;children:React.ReactNode}){return <section className="rounded-[26px] border border-[#dce8e7] bg-white p-5"><span className="text-[10px] font-black tracking-[.16em] text-[#008f87]">{eyebrow}</span><h2 className="mb-4 mt-1 font-black">{title}</h2><div className="space-y-2">{children}</div></section>}
function Row({label,value}:{label:string;value:string}){return <div className="flex flex-wrap justify-between gap-3 border-b border-[#edf3f2] py-2 text-xs last:border-0"><span className="text-slate-400">{label}</span><b className="max-w-[70%] break-words text-left text-slate-700">{value}</b></div>}
function Metric({label,value,accent=false}:{label:string;value:string;accent?:boolean}){return <div className={`rounded-[22px] border p-4 ${accent?"border-[#b9e7e1] bg-[#eaf9f6]":"border-[#dce8e7] bg-white"}`}><span className="text-[10px] font-black tracking-widest text-slate-400">{label}</span><b className={`mt-1 block text-lg ${accent?"text-[#087f78]":"text-[#10282c]"}`}>{value}</b></div>}
