import { redirect } from "next/navigation";
import { FileClock, ShieldCheck, Sparkles, Activity, UserRound, CircleCheck, CircleX, Ban } from "lucide-react";
import { db } from "../../../lib/db";
import { getWhatsAppReadContext } from "../../../lib/whatsapp/rbac";

const exactActionLabel:Record<string,string>={"connection.signup.start":"بدء ربط رقم واتساب","connection.signup.complete":"إكمال ربط رقم واتساب","reply.enqueue":"إرسال رد إلى عميل","template.sync":"تحديث القوالب من Meta","campaign.create":"إنشاء حملة","campaign.launch":"بدء إرسال حملة","commerce.integration.register":"إضافة متجر","commerce.integration.disconnect":"فصل متجر","api_key.create":"إنشاء مفتاح تكامل","api_key.revoke":"إلغاء مفتاح تكامل"};
const outcomeLabel:Record<string,string>={success:"تمت",denied:"لم يُسمح بها",failed:"تعذرت",cancelled:"أُلغيت"};
const targetLabel:Record<string,string>={connection:"رقم واتساب",campaign:"حملة",automation:"أتمتة",template:"قالب",contact:"جهة اتصال",conversation:"محادثة",integration:"متجر مرتبط",api_key:"مفتاح تكامل"};
function actionLabel(action:string){if(exactActionLabel[action])return exactActionLabel[action];if(action.startsWith("campaign."))return"تحديث حملة";if(action.startsWith("automation."))return"تحديث أتمتة";if(action.startsWith("contact.")||action.startsWith("contacts."))return"تحديث جهات الاتصال";if(action.startsWith("template."))return"تحديث القوالب";if(action.startsWith("connection."))return"تحديث ربط واتساب";if(action.startsWith("commerce."))return"تحديث ربط متجر";if(action.startsWith("reply."))return"إجراء على محادثة";return"إجراء داخل واتساب"}
function actorLabel(actorType:string,name:string|null|undefined){if(name)return name;return actorType==="user"?"أحد أعضاء الفريق":"INFRO"}
export default async function WhatsAppAuditPage(){const context=await getWhatsAppReadContext("audit.view");if(!context)redirect("/dashboard/whatsapp/inbox?access=denied");const logs=await db.whatsAppAuditLog.findMany({where:{businessId:context.businessId},orderBy:[{createdAt:"desc"},{id:"desc"}],take:100,select:{id:true,action:true,targetType:true,outcome:true,actorType:true,createdAt:true,actorUser:{select:{name:true}}}});const date=(value:Date)=>new Intl.DateTimeFormat("ar-SA",{dateStyle:"medium",timeStyle:"short",timeZone:"Asia/Riyadh"}).format(value);const successCount=logs.filter(l=>l.outcome==="success").length;const issueCount=logs.filter(l=>l.outcome==="failed"||l.outcome==="denied").length;
return <div className="space-y-5 pb-6"><header className="relative overflow-hidden rounded-[28px] bg-[#07181b] p-6 text-white sm:p-7"><div className="absolute -left-20 -top-24 h-64 w-64 rounded-full bg-[#00e5a8]/10 blur-3xl"/><div className="relative flex flex-col gap-6 xl:flex-row xl:items-end xl:justify-between"><div className="max-w-3xl"><span className="inline-flex items-center gap-2 text-[9px] font-black tracking-[.18em] text-[#58e6d2]" dir="ltr"><Sparkles className="h-4 w-4"/>INFRO AUDIT TRAIL</span><h1 className="mt-3 text-2xl font-black sm:text-3xl">كل إجراء مهم له أثر واضح</h1><p className="mt-2 text-sm leading-7 text-slate-300">راجع آخر 100 عملية حساسة على واتساب بدون إظهار مفاتيح أو بيانات ربط سرية. السجل يعكس ما حدث فعليًا لهذا النشاط.</p></div><div className="grid grid-cols-3 gap-2"><HeroStat label="عمليات" value={logs.length}/><HeroStat label="ناجحة" value={successCount}/><HeroStat label="تحتاج مراجعة" value={issueCount}/></div></div></header>
<section className="overflow-hidden rounded-[26px] border border-slate-200 bg-white shadow-[0_22px_60px_-48px_rgba(7,24,27,.55)]"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 px-5 py-4"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-[#e9fbf8] text-[#008f87]"><FileClock className="h-5 w-5"/></span><div><h2 className="text-sm font-black text-slate-950">النشاط الأخير</h2><p className="mt-1 text-[10px] text-slate-400">الترتيب من الأحدث إلى الأقدم</p></div></div><span className="inline-flex items-center gap-1.5 rounded-full bg-[#effbf9] px-3 py-1.5 text-[9px] font-black text-[#007f78]"><ShieldCheck className="h-3.5 w-3.5"/>بدون أسرار حساسة</span></div><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-right text-xs"><thead className="bg-[#fafcfc] text-slate-400"><tr><th className="p-3.5">الوقت</th><th>النشاط</th><th>بواسطة</th><th>على</th><th>النتيجة</th></tr></thead><tbody>{logs.map(log=><tr key={log.id} className="border-t border-slate-100 transition hover:bg-[#fbfdfd]"><td className="p-3.5 text-slate-500">{date(log.createdAt)}</td><td><div className="flex items-center gap-2"><Activity className="h-3.5 w-3.5 text-[#00a99d]"/><span className="font-black text-slate-800">{actionLabel(log.action)}</span></div></td><td className="text-slate-600"><span className="inline-flex items-center gap-1.5"><UserRound className="h-3.5 w-3.5 text-slate-400"/>{actorLabel(log.actorType,log.actorUser?.name)}</span></td><td className="text-slate-600">{targetLabel[log.targetType]||"واتساب"}</td><td><Outcome outcome={log.outcome}/></td></tr>)}{!logs.length?<tr><td colSpan={5} className="p-12 text-center"><span className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-[#effbf9] text-[#008f87]"><ShieldCheck className="h-6 w-6"/></span><b className="mt-3 block text-sm text-slate-900">لا يوجد نشاط مسجل بعد</b><span className="mt-1 block text-xs text-slate-500">عند ربط الرقم أو إدارة الحملات والقوالب ستظهر العمليات المهمة هنا تلقائيًا.</span></td></tr>:null}</tbody></table></div></section></div>}
function HeroStat({label,value}:{label:string;value:number}){return <div className="min-w-[84px] rounded-2xl border border-white/10 bg-white/[.06] px-3 py-3 text-center"><b className="block text-xl text-white">{value}</b><span className="text-[8px] font-bold text-slate-400">{label}</span></div>}
function Outcome({outcome}:{outcome:string}){const success=outcome==="success",cancelled=outcome==="cancelled";const Icon=success?CircleCheck:cancelled?Ban:CircleX;return <span className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 font-black ${success?"bg-emerald-50 text-emerald-700":cancelled?"bg-slate-100 text-slate-600":"bg-rose-50 text-rose-700"}`}><Icon className="h-3.5 w-3.5"/>{outcomeLabel[outcome]||"تحتاج مراجعة"}</span>}
