import Link from "next/link";
import { redirect } from "next/navigation";
import { Prisma } from "@prisma/client";
import { Link2, MousePointer2, Plus, ExternalLink, Search, RefreshCw } from "lucide-react";
import { db } from "../../../lib/db";
import { getWhatsAppReadContext } from "../../../lib/whatsapp/rbac";
import { hasActiveWhatsAppMarketingEntitlement } from "../../../lib/whatsapp/feature-entitlement";
import { shortLinkFilters, shortLinkUrl } from "../../../lib/short-link-domain";
import { ConfirmSubmitButton } from "../../../../components/dashboard/confirm-submit-button";
import { CsvExportLink } from "../_components/csv-export-link";
import { CopyLinkButton } from "./copy-link-button";
import { createShortLinkAction, updateShortLinkAction } from "./actions";

const panel = "min-w-0 rounded-2xl border border-slate-200 bg-white p-4 sm:p-6";
const control = "min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm text-slate-900 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-teal-500";
const button = "inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-slate-300 px-3 py-2 text-sm font-bold text-slate-800 focus-visible:ring-2 focus-visible:ring-teal-500";
const messages: Record<string, string> = { created: "أُنشئ الرابط. انسخه وشاركه في رسائلك وحملاتك.", updated: "تم تحديث الرابط.", invalid: "أدخل اسمًا ورابط HTTPS عامًا صالحًا. لا يمكن اختصار رابط مختصر آخر من INFRO.", limited: "طلبات كثيرة خلال دقيقة. حاول بعد قليل.", unavailable: "الرابط غير متاح في مساحة عملك.", denied: "ليس لديك صلاحية إدارة الروابط." };
const date = (value: Date) => value.toLocaleString("ar-SA", { timeZone: "Asia/Riyadh", dateStyle: "medium", timeStyle: "short" });
export default async function ShortLinksPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const actor = await getWhatsAppReadContext("campaign.manage");
  if (!actor) redirect("/dashboard/whatsapp?access=denied");
  if (!await hasActiveWhatsAppMarketingEntitlement({ businessId: actor.businessId })) redirect("/dashboard/billing/manage?feature=whatsapp-marketing");
  const params = await searchParams, { q, page, size } = shortLinkFilters(params);
  const scope = { businessId: actor.businessId, status: { not: "deleted" } };
  const where: Prisma.BusinessShortLinkWhereInput = { ...scope, ...(q ? { OR: [{ title: { contains: q, mode: "insensitive" } }, { destination: { contains: q, mode: "insensitive" } }, { code: { contains: q } }] } : {}) };
  const [links, total, stats, active] = await Promise.all([
    db.businessShortLink.findMany({ where, orderBy: [{ createdAt: "desc" }, { id: "desc" }], take: size, skip: (page - 1) * size }),
    db.businessShortLink.count({ where }),
    db.businessShortLink.aggregate({ where: scope, _count: { _all: true }, _sum: { clicks: true } }),
    db.businessShortLink.count({ where: { businessId: actor.businessId, status: "active" } }),
  ]);
  const href = (next = page) => `/dashboard/whatsapp/links?${new URLSearchParams({ q, page: String(next), size: String(size) })}`;
  const result = typeof params.result === "string" ? messages[params.result] : null;
  return <div dir="rtl" className="min-w-0 space-y-5 pb-6">
    <header className="rounded-[28px] bg-[#07181b] p-6 text-white sm:p-8"><Link2 className="h-8 w-8 text-teal-300" aria-hidden="true"/><h1 className="mt-4 text-2xl font-black sm:text-3xl">الروابط المختصرة</h1><p className="mt-3 max-w-2xl text-sm leading-7 text-slate-200">رابط قصير لهوية أعمالك. اختصر روابط المنتجات والحجز وواتساب، وشاركها ثم تابع النقرات من مساحة عملك.</p><p className="mt-3 text-xs text-teal-200" dir="ltr">ir.sa/s/…</p></header>
    {result ? <p role="status" className={`${panel} text-sm text-slate-800`}>{result}</p> : null}
    <section aria-label="إحصاءات الروابط" className="grid grid-cols-1 gap-3 sm:grid-cols-3">{[{ label: "إجمالي الروابط الحالية", value: stats._count._all, icon: Link2 }, { label: "روابط نشطة", value: active, icon: ExternalLink }, { label: "النقرات المسجلة", value: stats._sum.clicks ?? BigInt(0), icon: MousePointer2 }].map(item => <div key={item.label} className={panel}><item.icon className="mb-3 h-5 w-5 text-teal-700" aria-hidden="true"/><span className="block text-sm text-slate-600">{item.label}</span><b className="mt-2 block text-3xl text-slate-900">{item.value.toLocaleString("ar-SA")}</b></div>)}</section>
    <section className={panel}><h2 className="text-lg font-black text-slate-900">إنشاء رابط جديد</h2><form aria-label="إنشاء رابط مختصر" action={createShortLinkAction} className="mt-4 grid gap-3 lg:grid-cols-[1fr_2fr_auto]"><label className="text-sm text-slate-700">اسم الرابط<input name="title" required maxLength={100} placeholder="مثل: حجز موعد الصيانة" className={`mt-2 ${control}`}/></label><label className="min-w-0 text-sm text-slate-700">الرابط الأصلي<input name="destination" type="url" required maxLength={2048} placeholder="https://ir.sa/sada" dir="ltr" className={`mt-2 ${control}`}/></label><button className="inline-flex min-h-11 items-center justify-center gap-2 self-end rounded-xl bg-[#07181b] px-5 py-3 text-sm font-bold text-white focus-visible:ring-2 focus-visible:ring-teal-500"><Plus className="h-4 w-4" aria-hidden="true"/>إنشاء رابط</button></form><p className="mt-3 text-xs leading-6 text-slate-500">استخدم رابط HTTPS عامًا. يبقى الرابط المختصر نفسه عند تعديل الوجهة. يلزم اشتراك التسويق النشط لتشغيل الروابط.</p></section>
    <section className={panel}><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-lg font-black text-slate-900">كل الروابط المختصرة</h2><div className="flex flex-wrap gap-2"><CsvExportLink key={q} href={`/api/dashboard/short-links/export?${new URLSearchParams({ q })}`} filename="infro-short-links.csv" label="تصدير CSV" className={button}/><a href={href()} className={button}><RefreshCw className="h-4 w-4" aria-hidden="true"/>تحديث</a></div></div>
      <form className="my-5 grid gap-3 sm:grid-cols-[1fr_auto_auto]"><label className="sr-only" htmlFor="link-search">البحث في الروابط</label><input id="link-search" name="q" defaultValue={q} maxLength={100} placeholder="ابحث بالاسم أو الرابط…" className={control}/><label className="flex items-center gap-2 text-xs text-slate-600">عدد النتائج<select name="size" defaultValue={String(size)} className={control}>{[10, 25, 50].map(value => <option key={value} value={value}>{value}</option>)}</select></label><button className={button}><Search className="h-4 w-4" aria-hidden="true"/>بحث</button></form>
      <div className="space-y-4">{links.map(link => <article key={link.id} aria-label={`رابط ${link.title}`} className="min-w-0 rounded-2xl border border-slate-200 p-4"><div className="grid min-w-0 gap-4 xl:grid-cols-[minmax(0,1fr)_auto]"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h3 className="break-words text-base font-black text-slate-900">{link.title}</h3><span className="rounded-full bg-slate-100 px-3 py-1 text-xs text-slate-700">{link.status === "active" ? "نشط" : "متوقف"}</span></div><a href={shortLinkUrl(link.code)} target="_blank" rel="noopener noreferrer" dir="ltr" className="mt-3 block select-all break-all text-right text-base font-bold text-teal-700 underline decoration-teal-200 underline-offset-4">{shortLinkUrl(link.code)}</a><p dir="ltr" className="mt-2 break-all text-right text-xs leading-6 text-slate-500">{link.destination}</p></div><div className="text-sm leading-7 text-slate-600"><b className="block text-lg text-slate-900">{link.clicks.toLocaleString("ar-SA")} نقرة</b><p>أُنشئ: <time dateTime={link.createdAt.toISOString()}>{date(link.createdAt)}</time></p>{link.lastClickedAt ? <p>آخر نقرة: {date(link.lastClickedAt)}</p> : null}</div></div>
        <div className="mt-4 flex flex-wrap items-start gap-2"><CopyLinkButton url={shortLinkUrl(link.code)}/><a href={shortLinkUrl(link.code)} target="_blank" rel="noopener noreferrer" className={button}><ExternalLink className="h-4 w-4" aria-hidden="true"/>فتح</a><form action={updateShortLinkAction}><input type="hidden" name="id" value={link.id}/><input type="hidden" name="operation" value={link.status === "active" ? "disable" : "enable"}/><button className={button}>{link.status === "active" ? "تعطيل" : "تفعيل"}</button></form><form action={updateShortLinkAction}><input type="hidden" name="id" value={link.id}/><input type="hidden" name="operation" value="delete"/><ConfirmSubmitButton label="حذف" confirmMessage="سيتوقف هذا الرابط نهائيًا ويُحذف من قائمتك، ولن يُعاد استخدام رمزه. هل تريد المتابعة؟" className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-rose-300 px-3 text-sm font-bold text-rose-700"/></form></div>
        <details className="mt-4 rounded-xl bg-slate-50 p-3"><summary className="cursor-pointer text-sm font-bold text-slate-700">تعديل الاسم أو الوجهة</summary><form action={updateShortLinkAction} className="mt-4 grid gap-3 sm:grid-cols-2"><input type="hidden" name="id" value={link.id}/><input type="hidden" name="operation" value="edit"/><label className="text-sm text-slate-700">اسم الرابط<input name="title" required maxLength={100} defaultValue={link.title} className={`mt-1 ${control}`}/></label><label className="min-w-0 text-sm text-slate-700">الرابط الأصلي<input name="destination" type="url" required maxLength={2048} defaultValue={link.destination} dir="ltr" className={`mt-1 ${control}`}/></label><button className={`${button} sm:col-span-2`}>حفظ التعديل</button></form></details>
      </article>)}</div>
      {!links.length ? <div className="rounded-2xl border border-dashed border-slate-300 p-8 text-center text-sm leading-7 text-slate-500">{q ? "لا توجد روابط تطابق البحث." : "روابط أعمالك تبدأ هنا. أضف رابط منتج أو موعد أو واتساب من النموذج أعلاه."}</div> : null}
      <nav aria-label="صفحات الروابط" className="mt-5 flex flex-wrap items-center justify-between gap-3 text-sm text-slate-600"><span>{total.toLocaleString("ar-SA")} رابط · الصفحة {page}</span><div className="flex gap-2">{page > 1 ? <Link href={href(page - 1)} className={button}>السابق</Link> : null}{page * size < total ? <Link href={href(page + 1)} className={button}>التالي</Link> : null}</div></nav>
      <p className="mt-5 text-xs leading-6 text-slate-500">النقرات ليست عدد أشخاص فريدين، وقد تشمل تكرار الزيارة. نستبعد طلبات HEAD والروبوتات والمعاينات المعروفة، ولا نخزن عنوان IP أو رقم جوال الزائر. التصدير يشمل جميع نتائج البحث الحالية.</p>
    </section>
  </div>;
}
