"use client";
import Link from "next/link";
import { useState, useTransition } from "react";
import { submitProductCarouselAction } from "../../../actions/whatsapp-product-carousel";
export function CarouselEditor({ connections }: { connections: { id: string; label: string }[] }) {
  const [body, setBody] = useState("تعرّف على منتجاتنا المختارة وتصفح تفاصيلها من البطاقات أدناه.");
  const [notice, setNotice] = useState("");
  const [stop, setStop] = useState(false);
  const [pending, startTransition] = useTransition();
  return <div className="wa-split"><form className="wa-panel wa-stack" onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); startTransition(async () => { const result = await submitProductCarouselAction(form); setNotice(result.message); setStop(result.stop ?? false); }); }}><h2>إنشاء قالب كاروسيل منتجات</h2><label>الرقم الرسمي<select name="connectionId" required>{connections.map(c => <option key={c.id} value={c.id}>{c.label}</option>)}</select></label><label>اسم القالب<input name="name" dir="ltr" pattern="[a-z][a-z0-9_]{0,99}" maxLength={100} placeholder="featured_products" required/></label><label>اللغة<select name="language"><option value="ar">العربية</option><option value="en_US">English</option></select></label><label>نص الرسالة<textarea name="body" value={body} onChange={event => setBody(event.target.value)} rows={5} maxLength={1024} required/><small>{body.length} / 1024 · متغيرات اختيارية مثل {"{{1}}"}.</small></label><label>أمثلة المتغيرات<input name="examples" maxLength={8000} placeholder="أحمد | خصم الصيف"/><small>مثال لكل متغير بالترتيب، مفصولًا بعلامة |.</small></label><p className="wa-note">الفئة: تسويق. يُقدّم القالب ببطاقتين وزر عرض المنتج. بعد الاعتماد، تختار من 2 إلى 10 منتجات عند تجهيز الحملة.</p><label className="wa-check"><input name="confirm" type="checkbox" required/>أوافق على تقديم القالب إلى Meta للمراجعة.</label><button className="wa-button" disabled={pending || stop || !connections.length}>{pending ? "جارٍ تقديم القالب…" : "تقديم للمراجعة"}</button><p role="status" aria-live="polite">{notice}</p>{stop ? <Link className="wa-text-link" href="/dashboard/whatsapp/templates">متابعة القالب ومزامنته من Meta ←</Link> : null}</form>
    <aside className="wa-stack"><section className="wa-panel wa-stack"><span className="wa-badge">معاينة هيكل القالب</span><p className="wa-bot-answer">{body}</p><ol className="wa-carousel-preview">{[1, 2].map(number => <li key={number}><span className="wa-carousel-placeholder">منتج {number}</span><strong>بطاقة من كتالوجك</strong><small>الصورة والسعر من Meta</small><span className="wa-badge">عرض المنتج</span></li>)}</ol><p className="wa-note">هذه معاينة توضيحية. تحدد المنتجات الفعلية في الحملة بعد اعتماد القالب.</p></section><section className="wa-panel wa-stack"><h2>من الكتالوج إلى العميل</h2><ol className="wa-guide-steps"><li>اربط كتالوج Meta بحساب واتساب التجاري.</li><li>قدّم قالب الكاروسيل وانتظر اعتماد Meta.</li><li>أنشئ حملة واختر القالب والمنتجات والجمهور الموافق.</li><li>راجع الحملة ثم أرسلها أو جدولها.</li></ol><Link className="wa-text-link" href="/dashboard/whatsapp/campaigns?new=1#new-campaign">فتح محرر الحملات ←</Link></section></aside></div>;
}
